- README.md
Added a new badge for Matrix. 
Sorry for the muddy commit history. I believe a "Squash and Merge" might be good here.
> Added badge for Matrix to README.md

- defaults/keymaps-linux.toml
- defaults/keymaps-macos.toml
- defaults/keymaps-windows.toml
- lapce-data/src/command.rs
- lapce-data/src/editor.rs
Resubmitted because I messed up my branching with the previous PR. Hope spelling fixes are okay.
> Fix spelling of "forward"

- .github/workflows/cargo.yml
- README.md
please consider running a CI build on every push to reduce chances of merging changes that break the build
> add Github Action to do a build on push

- lapce-data/src/data.rs
- lapce-data/src/state.rs
> Fix bug in hex_to_color and remove unnecessary allocations

- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-ui/src/activity.rs
- lapce-ui/src/status.rs
> Fix click-to-toggle panels

- lapce-core/src/language.rs
- lapce-core/src/style.rs
- lapce-data/src/buffer.rs
- lapce-data/src/command.rs
- lapce-data/src/completion.rs
- lapce-data/src/data.rs
- lapce-data/src/editor.rs
- lapce-data/src/keypress/loader.rs
- lapce-data/src/keypress/mod.rs
- lapce-data/src/movement.rs
- lapce-data/src/search.rs
- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/plugin.rs
- lapce-proxy/src/terminal.rs
- lapce-ui/src/editor.rs
- lapce-ui/src/explorer.rs
- lapce-ui/src/keymap.rs
- lapce-ui/src/palette.rs
- lapce-ui/src/panel.rs
- lapce-ui/src/search.rs
- lapce-ui/src/settings.rs
- lapce-ui/src/window.rs
```
$ cargo clippy
Checking lapce-proxy v0.0.12 (/tmp/lapce/lapce-proxy)
Checking lapce-core v0.0.12 (/tmp/lapce/lapce-core)
Checking lapce-data v0.0.12 (/tmp/lapce/lapce-data)
Checking lapce-ui v0.0.12 (/tmp/lapce/lapce-ui)
Checking lapce v0.0.12 (/tmp/lapce)
Finished dev [unoptimized + debuginfo] target(s) in 4.85s
```
> Apply all suggested Clippy lints

- lapce-ui/src/code_action.rs
> Cancel code actions when cancelling completion

- defaults/dark-theme.toml
- defaults/light-theme.toml
- lapce-data/src/config.rs
- lapce-data/src/explorer.rs
- lapce-ui/src/explorer.rs
- lapce-ui/src/picker.rs
Selected item has priority, like in VSCode.
https://user-images.githubusercontent.com/977627/160257205-ee3d5493-06b0-4cf9-8948-925c259e4d5e.mp4
> Highlight hovered list item in file explorer

- Makefile
I see some `Alacritty.dmg` in `Makefile`, so I create this PR to update that.
> update typo in Makefile comment

- README.md
> List python3 as dependency

- Cargo.lock
- lapce-data/Cargo.toml
- lapce-data/src/data.rs
- lapce-data/src/lib.rs
- lapce-data/src/palette.rs
- lapce-ui/Cargo.toml
- lapce-ui/src/activity.rs
- lapce-ui/src/completion.rs
- lapce-ui/src/editor/gutter.rs
- lapce-ui/src/editor/header.rs
- lapce-ui/src/editor/tab.rs
- lapce-ui/src/editor/tab_header.rs
- lapce-ui/src/editor/tab_header_content.rs
- lapce-ui/src/explorer.rs
- lapce-ui/src/find.rs
- lapce-ui/src/lib.rs
- lapce-ui/src/palette.rs
- lapce-ui/src/panel.rs
- lapce-ui/src/picker.rs
- lapce-ui/src/problem.rs
- lapce-ui/src/search.rs
- lapce-ui/src/settings.rs
- lapce-ui/src/source_control.rs
- lapce-ui/src/split.rs
- lapce-ui/src/status.rs
- lapce-ui/src/svg.rs
- lapce-ui/src/terminal.rs
- lapce-ui/src/title.rs
Fixes https://github.com/lapce/lapce/issues/359
After moving the two functions mentioned in my comment on that issue, it was just a question  of fixing up all the imports.
> Move svg.rs from the data crate to the UI crate

- lapce-data/src/buffer.rs
This PR replaces some handwritten code with more "rustic" equivalents.
> Clean up parts of `move_offset`

- lapce-ui/src/editor/gutter.rs
Mostly just some readability improvements in the main painter function.
> Clean up gutter painting a bit

- lapce-proxy/src/dispatch.rs
> Don't panic if terminal does not exist

- CONTRIBUTING.md
> Fixed Spelling errors in CONTRIBUTING.md

- lapce-data/src/config.rs
- lapce-data/src/data.rs
We don't need it, there is an equivalent in Piet.
So long my beautiful tests, it was nice knowing you.
> Remove custom hex_to_color fn.

- README.md
Added some more parity with the website and some changes to make it easier to read.
Closes #401
Closes #37 
Co-authored-by:  James Munger @bajuba
> Added more parity with the website

- lapce-ui/src/settings.rs
This is the reason of https://github.com/lapce/lapce/pull/305#issuecomment-1082048184
> Release cursor request when settings panel is closed

- Cargo.lock
- lapce-core/Cargo.toml
- lapce-core/src/language.rs
> Add HTML tree-sitter support

- lapce-data/src/palette.rs
> feat: Add exclusion list to command palette to remove command palette open directive

- lapce-data/src/buffer.rs
- lapce-data/src/buffer/data.rs
- lapce-data/src/editor.rs
- lapce-data/src/editor/commands/indent_line.rs
- lapce-data/src/editor/commands/outdent_line.rs
- lapce-data/src/editor/commands/redo.rs
- lapce-data/src/editor/commands/undo.rs
- lapce-data/src/keypress/mod.rs
- lapce-ui/src/tab.rs
- lapce-ui/src/title.rs
I was just poking around and noticed some easy looking clippy warnings, so I went ahead and fixed them
> Fix clippy warnings

- Cargo.lock
- lapce-core/Cargo.toml
- lapce-core/src/language.rs
This is a cleaned-up version of #266
> Add Java syntax

- lapce-data/src/data.rs
This PR removes a possible panic and a few unnecessary conversions
> Clean up open folder/file

- defaults/keymaps-common.toml
- lapce-data/src/terminal.rs
- lapce-ui/src/terminal.rs
> Fix cursor movement in non-vi mode terminal

- lapce-ui/src/status.rs
> Display problem type icon in front of counter

- .github/workflows/pr.yml
- lapce-data/src/container.rs
- lapce-ui/src/app.rs
Issue: https://github.com/lapce/lapce/issues/483
> Run fmt on PRs

- lapce-data/src/terminal.rs
> Special-case non-modifier ansi sequences

- lapce-ui/src/status.rs
- lapce-ui/src/svg.rs
A drop in the ocean, but there's no reason to allocate for this :)
Built on top of #493
> Optimize svg access

- defaults/keymaps-common.toml
- lapce-core/src/command.rs
- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-data/src/editor.rs
- lapce-ui/src/editor/view.rs
to complement center_of_window
> implement top_of_window and bottom_of_window

- CONTRIBUTING.md
- README.md
- docs/new-contributor-guide-developer.md
- docs/new-contributor-guide-user.md
Initial work on #563 
This PR includes: 
Outline documents for:
1. New developer contributors
2. New user contributors
Refresh of:
1. Readme.md
2. contributing.md
Please also specifically see point 5 in docs/new-contributor-guide-developer.md
> Be aware that unless you explicitly state otherwise, contributions you make to this project will be under the Apache License Version 2.
I'm unsure if Lapce allows contributions under another licence, but Apache-2.0 has legalese wording in clause 5.
> Developer documentation

- README.md
- docs/new-contributor-guide-developer.md
Suggest closing #572.
(also added single whitespace docs)
> Indicate minimum toolchain version preventing #572

- defaults/keymaps-common.toml
- defaults/keymaps-macos.toml
- defaults/keymaps-nonmacos.toml
Signed-off-by: Ryan Russell <git@ryanrussell.org>
> Fix `Language` in toml files

- lapce-ui/src/plugin.rs
if plugin data is empty, display the message.
> Add `Plugin load failed` message

- lapce-core/src/language.rs
> Add tests for LapceLanguage variants Swift, QL, and Haskell

- lapce-data/src/data.rs
- lapce-data/src/proxy.rs
- lapce-proxy/src/dispatch.rs
- lapce-rpc/src/proxy.rs
- lapce-ui/src/app.rs
Fixes https://github.com/lapce/lapce/issues/110
> Implement checking out

- .github/workflows/ci.yml
- .github/workflows/pr.yml
- lapce-core/src/buffer.rs
- lapce-core/src/editor.rs
- lapce-data/src/command.rs
- lapce-data/src/config.rs
- lapce-data/src/data.rs
- lapce-proxy/src/plugin.rs
- lapce-ui/src/app.rs
- lapce-ui/src/editor.rs
- lapce-ui/src/editor/gutter.rs
- lapce-ui/src/editor/tab.rs
- lapce-ui/src/editor/tab_header.rs
- lapce-ui/src/editor/tab_header_content.rs
- lapce-ui/src/find.rs
- lapce-ui/src/settings.rs
- lapce-ui/src/title.rs
Hi all!
I started looking around in the source code while checking out [this issue](https://github.com/lapce/lapce/issues/603) I opened, and noticed that there are some compilation warnings, and there's no clippy running here.
So I took the liberty to:
1. Run `cargo clippy -- -D warnings` and fix all warnings
2. Fix some of Intellij's analysis warnings
3. Add clippy to the `ci.yml` and `pr.yml` workflows
4. Fix a small bug I detected, which is that the `ToggleTerminalFocus` was not available in the command palette - and now it is :-)
Hope you guys will find this PR beneficial 🙂
> some tech touchups (mainly clippy)

- lapce-core/Cargo.toml
- lapce-core/src/language.rs
- lapce-ui/Cargo.toml
Enable [Harelang](https://harelang.org/) syntax highlighting support
> add Hare tree sitter

- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-data/src/proxy.rs
- lapce-proxy/src/dispatch.rs
- lapce-rpc/src/proxy.rs
Minor command addition to initialize a git repository in the current folder.
> Add git init command to workbench

- README.md
Installation info for Arch Linux, Flatpak, Homebrew, Scoop and winget for better visibility
> Add Installation info

- .github/workflows/pr.yml
I added steps for caching in #645. However, I missed it.
> Add a missing step for caching to CI

- lapce-data/src/palette.rs
Fixes #679   
The issue was that it would incorrectly use the previous palette type in determining whether it should stay in the workspace-symbol-search palette type, which was of course the workspace-symbol-search. This has the prefix and the code assumes that the type it currently has is correct (and that it implies its prefix has to exist). This fixes that through moving the code to get the appropriate palette type out (so it can be called before we set the input).
> Fix crashing on workspace symbol search

- Cargo.lock
- lapce-core/Cargo.toml
- lapce-core/src/language.rs
- lapce-ui/Cargo.toml
> add syntax highlighting support for Bash and Zig

- lapce-ui/src/editor.rs
- lapce-ui/src/editor/view.rs
Fixes positioning of  
- diagnostics
- snippet parts
- other minor bits  
I think this should get most of them, but there might be some lingering in modal mode?  
Fixes #718
> Fix various inlay hint position bugs

- defaults/keymaps-common.toml
See Issue #700
Simply changed keymaps-common.toml
> Make ctrl+c=esc

- lapce-proxy/src/plugin.rs
resolves #331 from lapce side
plugin(s) need to implement `system_lsp` option to just pass lsp server executable name
> feat: add option to use lsp from PATH

- lapce-core/src/language.rs
- lapce-ui/src/status.rs
> feat: add language name to status bar

- lapce-core/src/language.rs
- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-data/src/document.rs
- lapce-data/src/palette.rs
- lapce-ui/src/palette.rs
- lapce-ui/src/tab.rs
> feat: add command to change file syntax language

- lapce-proxy/src/lsp.rs
add LSP stderr output to log and sort imports
> feat: add LSP stderr output to log

- README.md
> Add Instructions for fedora installation

- lapce-proxy/src/lsp.rs
Some LSPs want to know the current project folder when they start up, most notably the Julia LSP. This sets the directory that the LSP is started in to the workspace directory. This should hopefully work in general.
> Set the current directory when starting the LSP

- lapce-proxy/src/buffer.rs
Fixes https://github.com/lapce/lapce/issues/823 .. sort of.  
Though not perfectly. We currently don't really handle non-utf8 files that well.  
This will make so that the file will be able to read and rendered properly. However, it will mean that editing the file and then saving will keep the replacement character rather than the copyright character. I'll open a separate issue for this.  
VSCode does the same when opening the file as UTF8, but it supports multiple different encodings and so you can just tell it to use the right encoding.
> Read files lossily, in case they are not utf8

- lapce-data/src/command.rs
- lapce-data/src/data.rs
Intended as a starting point to discuss #904.
> Add command to toggle inlay hints

- Cargo.lock
- lapce-core/Cargo.toml
- lapce-core/src/language.rs
- lapce-ui/Cargo.toml
depends on https://github.com/szebniok/tree-sitter-wgsl/pull/2
> feat: add tree-sitter-wgsl

- lapce-ui/src/problem.rs
Fixes #947.  
The primary issue was that the line-height stored in the structure was the default editor line height, but it uses the configuration editor line height when painting. The mouse down checking would use the stored line height, which was incorrect for changed line-heights.  
There was also some other minor problems in the matching of the line calculation of the paint function.
> Fix calculation of problem mouse down position

- lapce-data/src/markdown/mod.rs
This fixes a small issue where the hover would have extra padding at the bottom. This was due to unconditionally inserting a newline after some tags. However, this is not desirable at the end, because it adds extra padding.  
I remember there being an open issue about this, but I was unable to find it.  
This also fixes a TODO I left about using smallvec for that tag processing, which I can now do since we have smallvec accessible.  
Before:  
After:
> Decrease padding in hover; fix todo

- docs/new-contributor-guide-developer.md
> Correct Wikipedia link

- lapce-data/src/proxy.rs
(since I'm dumb and just threw in conditional compilation instead of platform check)
> fix: proper unix mkdir -p fix

- lapce-proxy/src/buffer.rs
make most extensions matching case-insensitive and add case-sensitive
matching
sort extensions alphabetically (like in LSP spec page)
> feat: add remaining language IDs

- .github/workflows/ci.yml
> ci: don't fail other jobs on clippy/rustfmt fail

- README.md
fixes #846 
fixes #973 
Pronunciation poll: https://discord.com/channels/946858761413328946/1010249749565276160
> docs: add pronunciation hint to README.md

- lapce-data/src/about.rs
- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-data/src/lib.rs
- lapce-ui/src/about.rs
- lapce-ui/src/alert.rs
- lapce-ui/src/lib.rs
- lapce-ui/src/tab.rs
- lapce-ui/src/title.rs
this is annoying but oh well, it can be fixed later
> feat: add about dialog & add hover effect for alert

- Cargo.lock
> cargo update -p tree-sitter-yaml

- lapce-data/src/data.rs
> Only set toml language on the theme doc if enabled

- lapce-ui/src/tab.rs
This makes so the bottom panel can't be resized past the title or editor-header.
> Limit how far the bottom panel can be resized

- lapce-proxy/src/terminal.rs
This improves the usability of Lapce significantly for people unaware of the `$ flatpak-spawn --host bash` trick. With this, the Lapce Flatpak's default terminal runs on the host outside of the container and has access to all your regular programs. Without this patch, what you get is a sandboxed shell that only has access to whatever is available inside of the Flatpak container, which can be unexpected and confusing.
> Use host shell in terminal when running inside Flatpak

- defaults/keymaps-common.toml
- defaults/keymaps-macos.toml
- lapce-data/src/command.rs
- lapce-data/src/data.rs
> app: quit on custom key shortcut.

- lapce-data/src/terminal.rs
Fixes https://github.com/lapce/lapce/issues/1119
> Consider Alt + Backspace for deletion too

- lapce-proxy/src/buffer.rs
Adds entries for DLang as needed by https://github.com/LunaTheFoxgirl/lapce-dlang
> Add support for adding support for DLang LSPs

- Cargo.lock
- defaults/dark-theme.toml
- defaults/light-theme.toml
- lapce-core/queries/julia/highlights.scm
- lapce-core/src/style.rs
Adds a "variable" to the theme keywords 
Uses the highlight.scm from Helix
I think this _mostly_ solves the Julia highlighting issue
> Update Julia highlighting

- Cargo.lock
- lapce-core/Cargo.toml
- lapce-core/src/language.rs
- lapce-core/src/syntax/highlight.rs
- lapce-ui/Cargo.toml
Hello, great codebase you got, it's become my favorite editor in about 2 days of use. Even though there are some bugs it's FOSS & speed > anything else for me. 
I'm here today because I do flutter + rust development and I found a tree_sitter_dart crate. So I followed the EXTREMELY WELL Documented instructions on how to add a language in lapce-core/Language.rs
I did everything. But I'm getting this one problem I can't solve: 
Followed the web on this one and found this: 
[Answer to the error](https://stackoverflow.com/questions/27895946/expected-fn-item-found-a-different-fn-item-when-working-with-function-pointer)
But couldn't seem to work it out as the answer had primitive function return types and in this case it's a struct return type. tree_sitter::Language.
So, I've rattled a bit and …
> Adding support for the dart language (help needed)

- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-data/src/problem.rs
- lapce-ui/src/problem.rs
- lapce-ui/src/tab.rs
Supersedes #611 
Resolves #609
> Collapsible problem groups

- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-ui/src/explorer.rs
- lapce-ui/src/tab.rs
Doesn't actually reveal/select item, since it's currently not possible to do it in druid, but it opens directory fine.
> feat: add command to reveal item in system file explorer

- Cargo.lock
- lapce-core/Cargo.toml
- lapce-core/queries/latex/highlights.scm
- lapce-core/queries/latex/injections.scm
- lapce-core/src/language.rs
- lapce-core/src/syntax/highlight.rs
- lapce-ui/Cargo.toml
Signed-off-by: Jakub Panek <me@panekj.dev>
> feat: add Svelte & LaTeX

- lapce-data/src/proxy.rs
This implementation shouldn't block ssh like previous one did
> fix: add ssh debug, grab latest proxy & early start CM

- lapce-core/queries/elm/highlights.scm
- lapce-core/queries/jsx/highlights.scm
- lapce-core/src/language.rs
fixes #1186 and https://www.reddit.com/r/lapce/comments/x63pud/jsx_support/
> add new highlights for elm, jsx and fix tsx highlights

- Cargo.lock
- lapce-data/Cargo.toml
- lapce-data/src/data.rs
- lapce-proxy/Cargo.toml
- lapce-proxy/src/lib.rs
> fix: replace process_path with stdlib current_exe()

- extra/proxy.ps1
- extra/proxy.sh
- lapce-data/src/proxy.rs
Potential workaround for #1096 
Fixes #1315
> fix: use script to install proxy

- lapce-data/src/config.rs
- lapce-ui/src/settings.rs
This PR also cleans up the code a bit.
> Fix crash when changing themes while Settings is open

- Cargo.lock
- lapce-core/Cargo.toml
- lapce-core/queries/lua/highlights.scm
- lapce-core/src/language.rs
- lapce-core/src/syntax/highlight.rs
- lapce-ui/Cargo.toml
> Lua support

- lapce-core/src/language.rs
> Add sticky headers for json files

- Cargo.lock
- lapce-core/Cargo.toml
- lapce-core/src/language.rs
- lapce-core/src/syntax/highlight.rs
- lapce-ui/Cargo.toml
This way our highlight.scm will be pretty :)
> Add Scheme tree-sitter support

- lapce-core/src/language.rs
> add sticky headers to ruby and elixir

- lapce-core/src/cursor.rs
- lapce-ui/src/status.rs
selection range
Cursor pos
Multiple Cursors:
> Add cursor position/current selection in status bar

- .github/workflows/release.yml
- lapce-data/Cargo.toml
- lapce-data/src/update.rs
- lapce-ui/Cargo.toml
Closes #1351
Unfortunately I couldn't make `start` not create a console window, but otherwise this should work.
> Fix self-update for installed Lapce

- lapce-ui/src/editor/tab_header_content.rs
> Refactor mouse_up handling into a function to keep the code consistent

- lapce-ui/src/editor/tab.rs
Closes: https://github.com/lapce/lapce/issues/556
> Delete scratch_docs when deleting scratch documents

- lapce-proxy/src/lib.rs
- lapce-ui/src/app.rs
> fix: canonicalize paths

- lapce-data/src/command.rs
- lapce-data/src/settings.rs
- lapce-ui/src/settings.rs
- lapce-ui/src/tab.rs
> Plugin settings load fix

- CHANGELOG.md
- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-ui/src/tab.rs
> feat: add command to un/install lapce from/to PATH

- lapce-core/src/buffer/mod.rs
- lapce-core/src/editor.rs
- lapce-core/src/selection.rs
- lapce-core/src/syntax/edit.rs
- lapce-core/src/syntax/mod.rs
- lapce-data/src/completion.rs
- lapce-data/src/data.rs
- lapce-data/src/document.rs
- lapce-data/src/editor.rs
- lapce-ui/src/completion.rs
- lapce-ui/src/tab.rs
> Style Crash fix

- .gitignore
Generated by JetBrains's Fleet IDE.
> Added .fleet/ to .gitignore

- CHANGELOG.md
- lapce-core/src/buffer/mod.rs
- lapce-data/src/hover.rs
- lapce-data/src/markdown/mod.rs
- lapce-data/src/plugin.rs
- lapce-ui/src/completion.rs
- lapce-ui/src/editor/tab.rs
> scratch buffer fix

- lapce-data/src/document.rs
> fix whitespace on end of line

- defaults/settings.toml
- lapce-data/src/document.rs
- lapce-data/src/history.rs
- lapce-ui/src/editor.rs
> fix error lens

- CHANGELOG.md
- defaults/dark-theme.toml
- defaults/light-theme.toml
- defaults/settings.toml
- lapce-core/src/syntax/mod.rs
- lapce-data/src/config.rs
- lapce-data/src/document.rs
- lapce-data/src/history.rs
- lapce-ui/src/editor.rs
> add indent guide

- .github/workflows/ci.yml
- .github/workflows/release.yml
Removing actions using `node12` since it's deprecated
> ci: bump checkout action

- .github/ISSUE_TEMPLATE/config.yml
> github: add github issues config

- CHANGELOG.md
- Cargo.lock
- lapce-core/Cargo.toml
- lapce-core/src/language.rs
- lapce-core/src/syntax/highlight.rs
- lapce-ui/Cargo.toml
> feat(tree-sitter): add sql language

- CHANGELOG.md
- lapce-data/src/palette.rs
> order palette items according to last execute time

- Cargo.lock
- lapce-core/src/buffer/mod.rs
- lapce-core/src/syntax/edit.rs
- lapce-core/src/syntax/mod.rs
- lapce-data/Cargo.toml
- lapce-data/src/terminal.rs
- lapce-proxy/Cargo.toml
- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/terminal.rs
- lapce-ui/Cargo.toml
> fix tree sitter edit once more

- defaults/icon-theme.toml
- defaults/settings.toml
- lapce-data/src/config.rs
> fix: correct icons used

- lapce-ui/src/about.rs
It could be optimized further to use a static array because we know its going to be 5 elements.
> Clear commands every time we paint which will regenerate it back

- lapce-ui/src/about.rs
1. Fix an issue wherein the mouse cursor is always set to Pointer
2. Tighten the UI a bit so it doesn't overflow.
> Several fixes to the About modal

- CHANGELOG.md
- defaults/dark-theme.toml
- defaults/icon-theme.toml
- defaults/light-theme.toml
- defaults/settings.toml
- lapce-data/src/config.rs
- lapce-ui/src/editor/tab.rs
- lapce-ui/src/window.rs
> multiple fixes

- CHANGELOG.md
- defaults/dark-theme.toml
- defaults/light-theme.toml
- defaults/settings.toml
- lapce-data/src/config.rs
- lapce-ui/src/editor/tab.rs
- lapce-ui/src/tab.rs
> fix: rename drag/drop colour, use it for panels

- lapce-ui/src/title.rs
- lapce-ui/src/window.rs
Signed-off-by: panekj <me@panekj.dev>
> fix: correct svg icons

- CHANGELOG.md
- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-proxy/src/dispatch.rs
- lapce-rpc/src/proxy.rs
- lapce-ui/src/explorer.rs
- lapce-ui/src/tab.rs
> Add ability to copy active editor remote file url to clipboard

- Cargo.toml
Fixes #1490
Fixes #1480
Fixes #1405
> fix: bump required rust-version

- .github/dependabot.yml
- .github/workflows/ci.yml
> fix: update rust-cache action

- .github/workflows/release.yml
> ci: remove unmaintained action

- CHANGELOG.md
- lapce-ui/src/source_control.rs
> Add ability to open file/file diff from source control context menu

- lapce-ui/src/plugin.rs
> Plugin tab now accepts keyboard inputs

- lapce-core/src/word.rs
> fix: update xi_rope import name

- lapce-core/src/directory.rs
- lapce-core/src/editor.rs
- lapce-data/src/db.rs
- lapce-proxy/src/plugin/lsp.rs
- lapce-proxy/src/plugin/mod.rs
- lapce-proxy/src/plugin/wasi.rs
- lapce-ui/src/editor/header.rs
- lapce-ui/src/editor/tab_header.rs
- lapce-ui/src/find.rs
- lapce-ui/src/palette.rs
- lapce-ui/src/panel.rs
- lapce-ui/src/picker.rs
- lapce-ui/src/search.rs
- lapce-ui/src/settings.rs
- lapce-ui/src/status.rs
- lapce-ui/src/terminal.rs
> clippy fix

- lapce-data/src/proxy.rs
> fix(clippy): needless borrow

- lapce-core/src/language.rs
> add sticky headers support to Julia

- CHANGELOG.md
- lapce-data/src/command.rs
- lapce-data/src/explorer.rs
- lapce-ui/src/editor/tab_header_content.rs
- lapce-ui/src/explorer.rs
Reveal in File Tree action for editor tabs.
> Implement "Reveal in File Tree"

- lapce-ui/src/app.rs
> fix: hide terminal window when launching lapce

- lapce-ui/src/editor/tab_header.rs
- lapce-ui/src/editor/tab_header_content.rs
- lapce-ui/src/explorer.rs
> feat: use respective icons for extension/settings tabs

- .github/workflows/release.yml
Newlines added so it's easier to read when editing
> ci: remove deprecated features

- CHANGELOG.md
- defaults/dark-theme.toml
- defaults/light-theme.toml
- defaults/settings.toml
- lapce-data/src/data.rs
- lapce-ui/src/app.rs
- lapce-ui/src/window.rs
> remember panels when open folder

- defaults/dark-theme.toml
- defaults/icon-theme.toml
- defaults/light-theme.toml
- defaults/settings.toml
- extra/schemas/color-theme.json
- extra/schemas/icon-theme.json
- extra/schemas/settings.json
* added schema definitions for settings and themes
* sorted base colours as they appear in lapce
* fixed light theme
> fix: add schemas, sort base colours, fix light theme

- Cargo.lock
- lapce-data/src/command.rs
- lapce-data/src/plugin.rs
- lapce-data/src/proxy.rs
- lapce-proxy/src/plugin/mod.rs
- lapce-proxy/src/plugin/wasi.rs
- lapce-rpc/src/core.rs
- lapce-ui/Cargo.toml
- lapce-ui/src/plugin.rs
- lapce-ui/src/tab.rs
> render installed plugin icons

- .github/workflows/release.yml
> ci: fix importing codesign certs

- CHANGELOG.md
- lapce-core/queries/svelte/highlights.scm
- lapce-core/queries/svelte/indents.scm
- lapce-core/queries/svelte/injections.scm
- lapce-core/src/language.rs
> added queries for svelte

- Cargo.lock
- lapce-core/Cargo.toml
- lapce-ui/Cargo.toml
> fix: update lockfile

- CHANGELOG.md
- lapce-core/src/syntax/mod.rs
- lapce-core/src/word.rs
- lapce-data/src/command.rs
- lapce-data/src/document.rs
- lapce-ui/src/settings.rs
- lapce-ui/src/tab.rs
> theme settings fix

- CHANGELOG.md
- lapce-ui/src/editor/view.rs
> Fix autosave trying to save scratch files

- CHANGELOG.md
- Cargo.lock
- lapce-proxy/Cargo.toml
- lapce-proxy/src/plugin/mod.rs
> add zstd support for plugin

- Cargo.lock
- lapce-proxy/Cargo.toml
- lapce-proxy/src/plugin/lsp.rs
- lapce-proxy/src/plugin/psp.rs
- lapce-proxy/src/plugin/wasi.rs
> add support for plugin request

- lapce-core/src/syntax/mod.rs
- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-data/src/editor.rs
- lapce-data/src/signature.rs
- lapce-proxy/src/plugin/lsp.rs
- lapce-ui/src/editor/view.rs
- lapce-ui/src/signature.rs
- lapce-ui/src/tab.rs
> signature position change

- CHANGELOG.md
- lapce-proxy/src/plugin/wasi.rs
> prevent volt loading on files and hidden file/folders

- CHANGELOG.md
- lapce-data/src/command.rs
- lapce-data/src/document.rs
- lapce-data/src/editor.rs
- lapce-data/src/plugin.rs
- lapce-ui/src/plugin.rs
- lapce-ui/src/tab.rs
> fix plugin can't upgrade issue

- lapce-data/src/completion.rs
- lapce-data/src/editor.rs
- lapce-proxy/src/plugin/mod.rs
> don't send completion request again before response is back

- lapce-data/src/config.rs
- lapce-data/src/data.rs
- lapce-data/src/db.rs
- lapce-data/src/palette.rs
- lapce-ui/src/window.rs
> put recent workspaces to db

- lapce-data/src/db.rs
- lapce-data/src/palette.rs
> fix recent workspace crash

- CHANGELOG.md
- Cargo.lock
- lapce-data/Cargo.toml
- lapce-data/src/config.rs
- lapce-data/src/data.rs
- lapce-data/src/palette.rs
- lapce-data/src/proxy.rs
- lapce-ui/src/editor.rs
- lapce-ui/src/palette.rs
- lapce-ui/src/tab.rs
- lapce-ui/src/title.rs
> ssh remote supports port

- CHANGELOG.md
- Cargo.lock
- lapce-core/Cargo.toml
> update dlang treesitter

- CHANGELOG.md
- lapce-core/src/language.rs
- lapce-core/src/syntax/highlight.rs
- lapce-core/src/syntax/mod.rs
- lapce-data/src/document.rs
- lapce-data/src/markdown/mod.rs
> Revert "(band-aid) fix opening some file types crashing lapce"

- defaults/keymaps-macos.toml
- defaults/keymaps-nonmacos.toml
Simple keymap adjustment requested by #608
> added meta+y/ctrl+y redo keymap

- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-proxy/src/lib.rs
- lapce-ui/src/terminal.rs
> switch terminal tabs

- docs/new-contributor-guide-developer.md
> Updated link to Ropes: An Alternative to Strings

- lapce-data/src/command.rs
- lapce-data/src/document.rs
- lapce-data/src/editor.rs
- lapce-ui/src/tab.rs
> Code action change

- lapce-data/src/config.rs
- lapce-data/src/db.rs
- lapce-data/src/document.rs
- lapce-data/src/explorer.rs
- lapce-data/src/keypress/mod.rs
- lapce-data/src/plugin.rs
- lapce-data/src/search.rs
- lapce-proxy/src/buffer.rs
- lapce-proxy/src/plugin/mod.rs
- lapce-rpc/src/file.rs
- lapce-ui/src/editor.rs
- lapce-ui/src/editor/gutter.rs
- lapce-ui/src/palette.rs
- lapce-ui/src/scroll.rs
- lapce-ui/src/split.rs
- lapce-ui/src/tab.rs
- lapce-ui/src/title.rs
It is that time again, when new Rust version is released which includes Clippy being annoyed by various random stuff
> Apply clippy recommendations

- lapce-core/src/lib.rs
- lapce-data/src/config.rs
- lapce-data/src/lib.rs
- lapce-proxy/src/lib.rs
- lapce-rpc/src/lib.rs
- lapce-ui/src/editor.rs
- lapce-ui/src/lib.rs
- lapce-ui/src/scroll.rs
- lapce-ui/src/split.rs
- lapce-ui/src/tab.rs
- lapce-ui/src/title.rs
> Revert "fix(clippy): clippy::manual_clamp"

- CHANGELOG.md
- Cargo.lock
- lapce-core/Cargo.toml
- lapce-core/queries/clojure/highlights.scm
- lapce-core/queries/clojure/injections.scm
- lapce-core/src/language.rs
- lapce-core/src/syntax/highlight.rs
- lapce-ui/Cargo.toml
This pull request adds language support for Clojure and its derivatives (like .edn and .cljs).
I also have a clojure-lsp plugin ready to publish, as soon as I get this approved.
> Add Clojure language support

- CHANGELOG.md
- defaults/dark-theme.toml
- defaults/light-theme.toml
- defaults/settings.toml
- lapce-data/src/config.rs
- lapce-ui/src/settings.rs
- lapce-ui/src/title.rs
> fix: add option to change remote svg icon colour

- lapce-ui/src/app.rs
> Add items to MacOS menu bar

- lapce-data/src/terminal.rs
Implement bracketed paste to Lapce Terminal. Fixes https://github.com/lapce/lapce/issues/1503
> Implement Bracketed Paste in Lapce Terminal

- .gitattributes
> fix: add gitattributes for scripts

- lapce-core/src/paragraph.rs
> fix: use lapce-xi-rope instead of xi-rope

- .github/workflows/ci.yml
> Stop previous CI runs if an update has been pushed

- lapce-ui/src/app.rs
> remove macos hotkey

- lapce-data/src/data.rs
- lapce-data/src/document.rs
- lapce-ui/src/editor/view.rs
**typo**: rename LocalBufferKind::PluginSeach to LocalBufferKind::PluginSearch
> typo: LocalBufferKind::PluginSeach

- Cargo.lock
- lapce-data/Cargo.toml
- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-data/src/plugin.rs
- lapce-data/src/proxy.rs
- lapce-data/src/terminal.rs
- lapce-proxy/Cargo.toml
- lapce-proxy/src/plugin/mod.rs
- lapce-proxy/src/terminal.rs
- lapce-rpc/src/core.rs
- lapce-ui/Cargo.toml
> no need for base64

- extra/linux/dev.lapce.lapce.desktop
Added mime-types (allows opening lapce from e.g. a file manager/browser, "Open With"), new window action, and generic name
> Add more info to .desktop file

- .github/workflows/ci.yml
- .github/workflows/release.yml
> ci: fetch only locked dependencies

- lapce-data/src/terminal.rs
> fix: add terminal title fallback

- Cargo.lock
- Cargo.toml
- lapce-core/Cargo.toml
- lapce-data/Cargo.toml
- lapce-proxy/Cargo.toml
- lapce-rpc/Cargo.toml
- lapce-ui/Cargo.toml
> cargo: migrate to workspace.dependencies

- lapce-core/src/buffer/mod.rs
- lapce-core/src/buffer/rope_text.rs
- lapce-data/src/data.rs
- lapce-data/src/document.rs
> Add some documentation and tests

- CHANGELOG.md
- lapce-core/src/command.rs
- lapce-data/src/editor.rs
> feat: ToggleHistory command

- lapce-proxy/Cargo.toml
- lapce-proxy/src/plugin/mod.rs
- lapce-proxy/src/plugin/wasi.rs
- lapce-proxy/src/plugin/wasi/tests.rs
> fix: pass volt dir to load_volt

- lapce-proxy/src/plugin/lsp.rs
> Propagate error in read_line

- lapce-data/src/document.rs
Same outcome with one less special case
> refactor: assume empty diff if history unavailable

- lapce-proxy/src/dispatch.rs
> always return response even when the job was cancelled

- CHANGELOG.md
- defaults/settings.toml
- lapce-data/src/config.rs
- lapce-ui/src/explorer.rs
Fixes https://github.com/lapce/lapce/issues/2031
The state machine is kinda shite. Does anyone have a prior art for something like this?
> Implement basic double click delay

- lapce.spec
> fix permissions; close #2037

- lapce-data/src/command.rs
- lapce-data/src/document.rs
- lapce-data/src/editor.rs
- lapce-data/src/find.rs
- lapce-proxy/src/dispatch.rs
- lapce-ui/src/find.rs
- lapce-ui/src/search.rs
- lapce-ui/src/tab.rs
1. Merge UpdateSearch and UpdateSearchWithCaseSensitivity
2. Fix GlobalSearch request_handler not responding to an expired search job
3. Fix not searching when there are no workspaces open
4. Fix not searching for files outside of workspace folders
> Some fixes to global search with files outside of workspaces

- lapce-data/src/proxy.rs
Found while trying to debug plugins. Will help with that significantly if we can have the logs.
> Actually logs LogMessage request from plugins

- lapce-data/src/completion.rs
- lapce-data/src/data.rs
- lapce-data/src/db.rs
- lapce-data/src/markdown/layout_content.rs
- lapce-data/src/palette.rs
- lapce-data/src/proxy.rs
- lapce-data/src/update.rs
- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/plugin/mod.rs
- lapce-proxy/src/plugin/wasi.rs
- lapce-proxy/src/plugin/wasi/tests.rs
- lapce-ui/src/editor.rs
- lapce-ui/src/editor/header.rs
- lapce-ui/src/editor/tab_header.rs
- lapce-ui/src/explorer.rs
- lapce-ui/src/plugin.rs
- lapce-ui/src/search.rs
- lapce-ui/src/settings.rs
- lapce-ui/src/status.rs
> fix(clippy): apply new lints

- extra/proxy.sh
> fix: missing newline

- CHANGELOG.md
- lapce-proxy/src/dispatch.rs
Fixes https://github.com/lapce/lapce/issues/2039
> fix: find repository if it's not in current workspace path

- lapce-proxy/src/dispatch.rs
> fix: remove regex, parse remote as URL

- CHANGELOG.md
- defaults/keymaps-macos.toml
- lapce-core/src/command.rs
- lapce-core/src/editor.rs
- lapce-data/src/palette.rs
> feat: add Ctrl+{a,e,k} keybinds on macOS

- lapce-ui/src/title.rs
fix https://github.com/lapce/lapce/issues/2079
clear filter when ShowGitBranches
> fix: branches filter not updating

- lapce-data/src/editor.rs
- lapce-ui/src/diff.rs
- lapce-ui/src/editor/view.rs
- lapce-ui/src/lib.rs
feature: add a navbar for diff view.
> feat: diff view navbar

- lapce-data/src/editor.rs
There's absolutely no reason to call the document formatting since it is going to get ignored anyways.
> If format-on-save is not enabled, save immediately

- lapce-proxy/src/plugin/wasi.rs
> Properly instantiate the WASM blob and let it live inside the thread

- lapce-proxy/src/plugin/lsp.rs
- lapce-proxy/src/plugin/psp.rs
- lapce-proxy/src/plugin/wasi.rs
> make wasi initilization async

- defaults/settings.toml
- lapce-data/src/config.rs
- lapce-ui/src/scroll.rs
Feature requested here: https://github.com/lapce/lapce/issues/2085
> Add settings to configure the scroll speed

- extra/proxy.sh
> fix: rewrite script + fix version comparison

- CHANGELOG.md
- lapce-proxy/src/buffer.rs
> fix: dont overwrite symlink

- lapce-ui/src/editor/gutter.rs
> Use abs_diff

- lapce-data/src/command.rs
- lapce-data/src/config.rs
- lapce-data/src/data.rs
- lapce-data/src/palette.rs
- lapce-data/src/proxy.rs
- lapce-ui/src/palette.rs
- lapce-ui/src/tab.rs
- lapce-ui/src/title.rs
> fix: build WSL backend only for Windows

- lapce-app/src/app.rs
- lapce-app/src/keypress.rs
- lapce-app/src/window_tab.rs
- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/plugin/dap.rs
Temporary code to make the floem branch compile
> Fix compilation of "floem" on windows (and linux)

- lapce-data/src/document.rs
> fix: use AND comparison instead of bitwise

- CHANGELOG.md
- lapce-proxy/src/terminal.rs
> revert back to old way of set_locale_enviroment

- lapce-core/src/char_buffer.rs
- lapce-core/src/mode.rs
> Fix new clippy warnings

- defaults/settings.toml
- extra/schemas/settings.json
- lapce-data/src/config.rs
- lapce-data/src/document.rs
- lapce-ui/src/editor.rs
feature: highlight all occurrences of the selected text
Fixes https://github.com/lapce/lapce/issues/2212
There is also a setting to disable this feature：
> feat: highlight all occurrences of the selected text

- lapce-ui/src/split.rs
feature: double-click for new file on home page (welcome view) 
issue: https://github.com/lapce/lapce/issues/2198
> feat: double-click for new file on home page

- CHANGELOG.md
- extra/linux/dev.lapce.lapce.desktop
> Add StartupWMClass to desktop entry

- CHANGELOG.md
> docs: add git branch filter input in changelog

- lapce-ui/src/tab.rs
> fix: typo in tab.rs

- .github/workflows/ci.yml
- lapce-core/Cargo.toml
- lapce-core/src/directory.rs
- lapce-ui/Cargo.toml
> fix: store lapce data next to lapce for portable install

- CHANGELOG.md
- lapce-core/src/movement.rs
- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-data/src/editor.rs
- lapce-proxy/src/cli.rs
- lapce-proxy/src/lib.rs
- lapce-ui/src/app.rs
- lapce-ui/src/search.rs
Fixes https://github.com/lapce/lapce/issues/1872
> Add option to open files at specific line/column

- lapce-ui/src/search.rs
Fix https://github.com/lapce/lapce/issues/2267
> fix: search result folding incorrectly

- lapce-data/src/command.rs
- lapce-data/src/data.rs
Would be nice to be able to assign a shortcut to this command. :+1:
> command: implemented RevealActiveFileInFileTree

- lapce-app/src/app.rs
- lapce-app/src/focus_text.rs
- lapce-app/src/title.rs
Depends on https://github.com/lapce/floem/pull/4
> Use Style builder style

- .github/workflows/release.yml
> ci: fix WiX install + use Cargo sparse protocol

- .github/workflows/ci.yml
> ci: copy cargo config from release workflow

- lapce-proxy/src/dispatch.rs
> Fixed copy remote file url

- docs/installing-with-package-manager.md
Still waiting for the ebuild to be merged into GURU main branch. Until then this is a draft.
Signed-off-by: Pascal Jäger <pascal.jaeger@leimstift.de>
> Add instructions for installing on Gentoo

- lapce-data/src/config.rs
- lapce-ui/src/editor.rs
- lapce-ui/src/editor/view.rs
> fix: limit lower bound of blink interval

- lapce-proxy/src/cli.rs
> fix: canonicalize path

- Cargo.lock
- Cargo.toml
- extra/proxy.sh
- lapce-core/Cargo.toml
- lapce-core/build.rs
- lapce-data/src/data.rs
- lapce-data/src/update.rs
- lapce-proxy/Cargo.toml
- lapce-proxy/src/lib.rs
- lapce-ui/src/app.rs
- lapce-ui/src/title.rs
> fix: proxy version comparison

- Cargo.lock
- Cargo.toml
- extra/proxy.sh
- lapce-core/Cargo.toml
- lapce-core/build.rs
- lapce-data/src/data.rs
- lapce-data/src/update.rs
- lapce-proxy/Cargo.toml
- lapce-proxy/src/lib.rs
- lapce-ui/src/app.rs
- lapce-ui/src/title.rs
> Revert "fix: proxy version comparison"

- docs/installing-with-package-manager.md
I also included the link to the package in NixOS Search btw.
> docs: add install instructions for nixpkgs

- .github/workflows/ci.yml
- lapce-app/Cargo.toml
> ci: fix builds

- lapce-app/Cargo.toml
> fix: unbreak whole repo

- lapce-app/src/window_tab.rs
reimplementing CloseFloder workbench commands
https://github.com/lapce/lapce/issues/2417
> fix: reimplementing CloseFloder command

- lapce-app/src/keypress.rs
- lapce-app/src/proxy/remote.rs
- lapce-app/src/proxy/ssh.rs
This just updates log strings referencing `lapce_data` to properly refer to `lapce_app`.
> Minor: Update log targets

- lapce-app/src/app.rs
> Fix reimpl show language in status

- lapce-app/src/app.rs
> fix: re-implement cursor info

- lapce-app/src/app.rs
- lapce-app/src/command.rs
- lapce-app/src/palette.rs
- lapce-app/src/palette/item.rs
- lapce-app/src/palette/kind.rs
- lapce-app/src/source_control.rs
- lapce-app/src/title.rs
- lapce-app/src/window_tab.rs
- lapce-proxy/src/dispatch.rs
- lapce-rpc/src/proxy.rs
- lapce-rpc/src/source_control.rs
> fix: re-implement reference checkout, include tags

- docs/installing-with-package-manager.md
> docs(nix): correct nix profile name

- docs/building-from-source.md
- docs/installing-with-package-manager.md
Updated build-from-source and installing-with-package-manager with steps for Void Linux.
> Updated documentation with steps for building or installing on Void Linux

- Cargo.lock
- lapce-app/Cargo.toml
- lapce-app/src/alert.rs
- lapce-app/src/app.rs
- lapce-app/src/command.rs
- lapce-app/src/doc.rs
- lapce-app/src/editor.rs
- lapce-app/src/editor/diff.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/editor_tab.rs
- lapce-app/src/lib.rs
- lapce-app/src/main_split.rs
- lapce-app/src/window_tab.rs
- lapce-data/src/editor.rs
- lapce-ui/src/editor.rs
- lapce-ui/src/editor/header.rs
- lapce-ui/src/split.rs
> scratch doc

- lapce-app/src/window_tab.rs
> fix: formatting

- lapce-proxy/src/buffer.rs
> fix: create a backup file before saving instead of creating new file

- Cargo.lock
- lapce-app/Cargo.toml
- lapce-app/src/app.rs
- lapce-app/src/db.rs
- lapce-app/src/palette.rs
- lapce-app/src/proxy.rs
- lapce-app/src/status.rs
- lapce-app/src/terminal/panel.rs
- lapce-app/src/window.rs
- lapce-app/src/window_tab.rs
- lapce-proxy/src/buffer.rs
> Move window tab

- Cargo.lock
- Cargo.toml
- lapce-app/Cargo.toml
- lapce-app/src/debug.rs
- lapce-app/src/settings.rs
- lapce-proxy/Cargo.toml
- lapce-proxy/src/plugin/wasi.rs
> fix: update toml_edit and use toml crate for easy parsing

- CHANGELOG.md
- lapce-app/src/panel/plugin_view.rs
> Fixed typo in the plugin view

- Cargo.lock
- lapce-app/Cargo.toml
- lapce-app/src/app.rs
- lapce-app/src/command.rs
- lapce-app/src/editor/diff.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/file_explorer/node.rs
- lapce-app/src/file_explorer/view.rs
- lapce-app/src/main_split.rs
- lapce-app/src/window_tab.rs
> move editor tab

- CHANGELOG.md
- Cargo.lock
- lapce-app/Cargo.toml
- lapce-app/src/app.rs
- lapce-app/src/doc.rs
- lapce-app/src/editor.rs
- lapce-app/src/editor/gutter.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/editor/view_data.rs
- lapce-app/src/editor_tab.rs
- lapce-app/src/find.rs
- lapce-app/src/main_split.rs
- lapce-app/src/panel/plugin_view.rs
- lapce-app/src/panel/source_control_view.rs
- lapce-app/src/settings.rs
- lapce-app/src/terminal/view.rs
- lapce-app/src/text_area.rs
- lapce-app/src/text_input.rs
- lapce-app/src/wave.rs
> add replace

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Cargo.lock
- docs/building-from-source.md
- lapce-app/Cargo.toml
- lapce-app/src/app.rs
- lapce-app/src/editor.rs
- lapce-app/src/title.rs
- lapce-app/src/window.rs
- lapce-app/src/window_tab.rs
> macos no titlebar

- Cargo.lock
- lapce-app/Cargo.toml
- lapce-app/src/config/editor.rs
- lapce-app/src/editor.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/main_split.rs
- lapce-app/src/text_input.rs
- lapce-app/src/window_tab.rs
> Blink cursor

- Cargo.lock
- lapce-app/Cargo.toml
- lapce-app/src/proxy/remote.rs
> Revert "Change how proxy script is ran"

- lapce-app/src/about.rs
- lapce-app/src/app.rs
- lapce-app/src/completion.rs
- lapce-app/src/db.rs
- lapce-app/src/doc.rs
- lapce-app/src/file_explorer/view.rs
- lapce-app/src/listener.rs
- lapce-app/src/palette.rs
- lapce-app/src/panel/debug_view.rs
- lapce-app/src/panel/global_search_view.rs
- lapce-app/src/panel/plugin_view.rs
- lapce-app/src/panel/problem_view.rs
- lapce-app/src/panel/source_control_view.rs
- lapce-app/src/panel/terminal_view.rs
- lapce-app/src/panel/view.rs
- lapce-app/src/proxy/wsl.rs
- lapce-app/src/settings.rs
- lapce-app/src/snippet.rs
- lapce-app/src/status.rs
- lapce-app/src/window.rs
- lapce-app/src/window_tab.rs
> Fix clippy and rustfmt lint errors

- extra/proxy.sh
> fix proxy script, create and switch to lapce dir before download/unpack

- Cargo.lock
- lapce-app/Cargo.toml
- lapce-app/src/app.rs
- lapce-app/src/editor/gutter.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/editor_tab.rs
- lapce-app/src/file_explorer/view.rs
- lapce-app/src/keymap.rs
- lapce-app/src/panel/source_control_view.rs
- lapce-app/src/text_input.rs
- lapce-app/src/window.rs
- lapce-app/src/window_tab.rs
> add open editors

- lapce-app/src/app.rs
- lapce-app/src/doc.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/text_input.rs
> ime support

- Cargo.lock
- lapce-app/Cargo.toml
- lapce-app/src/app.rs
- lapce-app/src/completion.rs
- lapce-app/src/doc.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/editor/view_data.rs
- lapce-app/src/file_explorer/data.rs
- lapce-app/src/file_explorer/node.rs
- lapce-app/src/file_explorer/view.rs
- lapce-app/src/palette.rs
- lapce-app/src/palette/item.rs
- lapce-app/src/status.rs
- lapce-app/src/window_tab.rs
- lapce-proxy/src/dispatch.rs
- lapce-rpc/src/core.rs
- lapce-rpc/src/file.rs
> show window message

- lapce-app/src/editor.rs
- lapce-app/src/main_split.rs
- lapce-app/src/palette.rs
- lapce-app/src/settings.rs
- lapce-proxy/src/dispatch.rs
- lapce-rpc/src/file.rs
> settings writing to file fix

- Cargo.lock
- lapce-app/Cargo.toml
- lapce-app/src/editor.rs
- lapce-app/src/main_split.rs
- lapce-app/src/palette.rs
- lapce-app/src/settings.rs
- lapce-proxy/src/dispatch.rs
- lapce-rpc/src/file.rs
> Reimplement file explorer

- lapce-app/src/doc.rs
- lapce-app/src/editor.rs
- lapce-app/src/editor/diff.rs
- lapce-app/src/editor_tab.rs
- lapce-app/src/file_explorer/data.rs
- lapce-app/src/file_explorer/node.rs
- lapce-app/src/file_explorer/view.rs
- lapce-app/src/main_split.rs
- lapce-app/src/window_tab.rs
- lapce-proxy/src/buffer.rs
- lapce-proxy/src/dispatch.rs
- lapce-rpc/src/file.rs
- lapce-rpc/src/proxy.rs
> change the way of displaying file explorer

- Cargo.lock
- lapce-app/Cargo.toml
- lapce-app/src/app.rs
- lapce-app/src/main_split.rs
- lapce-app/src/panel/data.rs
- lapce-app/src/panel/position.rs
- lapce-app/src/panel/view.rs
- lapce-app/src/status.rs
- lapce-app/src/title.rs
- lapce-app/src/window.rs
- lapce-app/src/window_tab.rs
> panel resize

- .github/workflows/ci.yml
> ci: clean disk space between build and doctest on windows

- lapce-app/src/app.rs
> feat: allow closing tab via mouse middle click

- defaults/settings.toml
- lapce-app/src/app.rs
- lapce-app/src/config.rs
- lapce-app/src/config/ui.rs
> feat: allow changing position of close button in editor tabs

- lapce-app/src/app.rs
Log files were just empty. This is due to the writer guard being dropped before even being used. This PR simply forwards the guard to the `launch` "main".
> Fix log files being empty

- lapce-app/src/app.rs
> fix margin when not using close button in tab

- Cargo.lock
- Cargo.toml
- defaults/settings.toml
- lapce-app/Cargo.toml
- lapce-app/src/app.rs
- lapce-app/src/command.rs
- lapce-app/src/config.rs
- lapce-app/src/config/terminal.rs
- lapce-app/src/palette.rs
- lapce-app/src/palette/item.rs
- lapce-app/src/palette/kind.rs
- lapce-app/src/terminal/data.rs
- lapce-app/src/terminal/panel.rs
- lapce-app/src/terminal/tab.rs
- lapce-app/src/window_tab.rs
- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/terminal.rs
- lapce-rpc/Cargo.toml
- lapce-rpc/src/proxy.rs
- lapce-rpc/src/terminal.rs
> feat: add terminal profiles

- lapce-app/src/db.rs
- lapce-app/src/doc.rs
- lapce-app/src/keypress.rs
- lapce-app/src/keypress/loader.rs
- lapce-app/src/panel/problem_view.rs
- lapce-core/src/char_buffer.rs
- lapce-core/src/editor.rs
- lapce-core/src/syntax/highlight.rs
- lapce-rpc/src/file.rs
> Fix new clippy/rust lints

- lapce-app/src/status.rs
> fix: make status text follow theme foreground key

- lapce-app/src/app.rs
> fix tab close button for good

- lapce-app/src/status.rs
> fix rest of status messages to have foreground colour

- Cargo.lock
- defaults/run.toml
- lapce-app/src/app.rs
- lapce-app/src/palette.rs
- lapce-app/src/panel/terminal_view.rs
- lapce-app/src/terminal/data.rs
- lapce-app/src/terminal/panel.rs
- lapce-app/src/terminal/view.rs
- lapce-app/src/window_tab.rs
- lapce-proxy/Cargo.toml
- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/plugin/dap.rs
- lapce-proxy/src/terminal.rs
- lapce-rpc/src/core.rs
- lapce-rpc/src/dap_types.rs
> terminal fixes

- .github/workflows/release.yml
- .gitignore
> ci: add vendor tarball

- defaults/settings.toml
- extra/schemas/settings.json
- lapce-app/src/config/editor.rs
- lapce-app/src/doc.rs
- lapce-core/src/editor.rs
> Auto-surround config

- Cargo.lock
- lapce-app/Cargo.toml
- lapce-app/src/about.rs
- lapce-app/src/app.rs
- lapce-app/src/editor/gutter.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/focus_text.rs
- lapce-app/src/terminal/view.rs
- lapce-app/src/text_input.rs
- lapce-app/src/wave.rs
This bumps Floem to the latest version.
This reduces lag when scrolling, but there's still some left.
> Bump Floem

- lapce-app/src/status.rs
Update the language in the status bar when the open file in the editor changes
> update the language in the status bar

- lapce-app/src/editor.rs
Implement the functionality for the `Format Document` command.
> feat: implement `Format Document` command

- lapce-app/src/config/terminal.rs
- lapce-app/src/terminal/data.rs
- lapce-app/src/window_tab.rs
Fixes https://github.com/lapce/lapce/issues/2812
> fix using default terminal profile

- lapce-core/src/language.rs
Fixes https://github.com/lapce/lapce/issues/1873
> fix: add cmakelists to cmake lang

- docs/installing-with-package-manager.md
Closes https://github.com/lapce/lapce/pull/2509
Fixes https://github.com/lapce/lapce/issues/2508
> docs: cleanup distro specific info

- Cargo.lock
- Cargo.toml
- lapce-app/Cargo.toml
- lapce-app/src/app.rs
- lapce-app/src/lib.rs
> add windows-sys, add error popup on panic, bring back panic hook to logfile

- Cargo.toml
- lapce-app/Cargo.toml
- lapce-proxy/Cargo.toml
> fix: move globset to workspace deps

- extra/linux/docker/debian/Dockerfile
- extra/linux/docker/ubuntu/Dockerfile
> fix: include .desktop and logo in debian packages

- .github/dependabot.yml
> Allow Dependabot to open more PRs

- lapce-proxy/src/plugin/mod.rs
- lapce-proxy/src/plugin/wasi.rs
> fix: announce support for workspace_folders in lsp/psp

- Cargo.lock
Closes https://github.com/lapce/floem/pull/335
> fix: update softbuffer

- Cargo.lock
- Cargo.toml
- lapce-app/Cargo.toml
> chore(deps): bump clap from 3 to 4

- defaults/run.toml
- lapce-app/src/app.rs
- lapce-core/src/language.rs
- lapce-proxy/src/plugin/psp.rs
- lapce-rpc/src/file.rs
> fix some comments

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- defaults/settings.toml
- lapce-app/Cargo.toml
- lapce-app/src/app.rs
- lapce-app/src/command.rs
- lapce-app/src/config/editor.rs
- lapce-app/src/doc.rs
- lapce-app/src/editor.rs
- lapce-app/src/focus_text.rs
- lapce-app/src/palette.rs
- lapce-app/src/palette/item.rs
- lapce-app/src/palette/kind.rs
- lapce-app/src/status.rs
- lapce-app/src/text_input.rs
- lapce-app/src/window_tab.rs
This is a companion PR to https://github.com/lapce/floem/pull/353, that pr has most of the commentary.  
Fixes #3029 (todo: there's probably some general line ending switching issue)  
Normalizing the file's newlines is done on saving of the file.  
This adds a LF/CRLF button to the status bar.
~~(Once the other PR is merged, I'll have to update this PR's floem)~~
> Implement line-ending switching

- lapce-app/src/file_explorer/view.rs
This fixes a bug where the file explorer wouldn't have a scrollbar.    
The issue was that I made the file explorer view `.height_full()` so that you could right click on the empty are below the files, but this behaves badly with scroll (not 100% sure why? maybe because the parents have full height too it just gets arbitrary height? is it not limited by window height?)  
The fix for this is just moving `scroll` into the file nodes view function so that the on right click listener can be attached to that instead, thus allowing the scroll be to 100% height and the inner file node list without.
> Fix scrolling in file explorer

- defaults/settings.toml
should Fix #3075 
I forgot to add it to settings.toml (probably should just remove color theme stuff from that file!)
> Add tooltip coloring to settings.toml

- lapce-app/src/terminal/view.rs
> add underline for hyperlink

- lapce-app/src/config/terminal.rs
- lapce-app/src/proxy/remote.rs
> fix(clippy): fix new clippy lints

- .github/workflows/ci.yml
- Cargo.toml
- Makefile
- lapce-app/Cargo.toml
- lapce-core/Cargo.toml
- lapce-proxy/Cargo.toml
- lapce-rpc/Cargo.toml
> fix: update msrv

- lapce-app/src/app.rs
- lapce-app/src/panel/view.rs
> fix panel resizing bug

- .taplo.toml
- Cargo.toml
- lapce-app/Cargo.toml
- lapce-core/Cargo.toml
- lapce-proxy/Cargo.toml
- lapce-rpc/Cargo.toml
> style: format Cargo manifests

- README.md
> docs: remove matrix button

- Cargo.lock
- Cargo.toml
- lapce-app/Cargo.toml
- lapce-app/src/plugin.rs
- lapce-app/src/window_tab.rs
> fix: bump dependencies, remove indexmap/parking_lot duplicates

- lapce-app/src/terminal/view.rs
The effect is shown in the figure:
> add selection function for terminal

- Cargo.lock
- lapce-app/Cargo.toml
> fix: bump config

- Cargo.lock
- Cargo.toml
- lapce-app/Cargo.toml
- lapce-app/src/config.rs
- lapce-app/src/window_tab.rs
- lapce-proxy/Cargo.toml
- lapce-proxy/src/plugin/dap.rs
- lapce-proxy/src/plugin/lsp.rs
- lapce-proxy/src/plugin/psp.rs
- lapce-proxy/src/plugin/wasi.rs
- lapce-rpc/src/core.rs
> fix: improve observability for plugins

- lapce-app/src/app.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/file_explorer/view.rs
- lapce-app/src/panel/debug_view.rs
- lapce-app/src/panel/global_search_view.rs
- lapce-app/src/panel/plugin_view.rs
- lapce-app/src/panel/terminal_view.rs
- lapce-app/src/panel/view.rs
- lapce-app/src/status.rs
- lapce-app/src/title.rs
> fix: add event propagation to certain buttons

- Cargo.lock
- Cargo.toml
- lapce-app/Cargo.toml
- lapce-app/benches/visual_line.rs
- lapce-app/src/app.rs
- lapce-app/src/doc.rs
- lapce-app/src/editor.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/panel/plugin_view.rs
- lapce-app/src/panel/terminal_view.rs
- lapce-app/src/text_input.rs
Depends on https://github.com/lapce/floem/pull/402
> Update floem for editor styling

- Cargo.lock
- lapce-app/Cargo.toml
- lapce-app/src/db.rs
> swap sled to plain text file for db

- lapce-app/src/config.rs
- lapce-app/src/config/color_theme.rs
This should (hopefully) fully fix theme fallback. It also adds a basic test.  
I'm keeping the default to hotpink that pj added, because avoiding crashing is nice even if it did make it far easier to know when there were problems. (#3121 being the original issue)
The issue was that we wouldn't actually include the default theme as a fallback.  
While I could've fixed the old check, it seems like it should just be in merge config rather than doing two merges.  
I believe this works right from testing.
> Fix theme fallback

- lapce-app/src/settings.rs
> fix settings page navigation issue

- Cargo.lock
- Cargo.toml
- lapce-app/Cargo.toml
- lapce-app/src/about.rs
- lapce-app/src/code_action.rs
- lapce-app/src/command.rs
- lapce-app/src/doc.rs
- lapce-app/src/editor.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/file_explorer/data.rs
- lapce-app/src/global_search.rs
- lapce-app/src/keypress.rs
- lapce-app/src/keypress/condition.rs
- lapce-app/src/keypress/keymap.rs
- lapce-app/src/keypress/press.rs
- lapce-app/src/main_split.rs
- lapce-app/src/palette.rs
- lapce-app/src/plugin.rs
- lapce-app/src/rename.rs
- lapce-app/src/settings.rs
- lapce-app/src/source_control.rs
- lapce-app/src/terminal/data.rs
- lapce-app/src/window_tab.rs
> treat altgr as modifier

- lapce-app/src/terminal/view.rs
> fix terminal bg drawing

- Cargo.lock
- lapce-app/Cargo.toml
> fix: remove unused tokio dependency

- Cargo.lock
- lapce-app/Cargo.toml
- lapce-app/src/completion.rs
- lapce-app/src/palette.rs
> fix: upgrade nucleo, remove unused futures dependency

- Cargo.lock
- lapce-app/Cargo.toml
- lapce-app/src/markdown.rs
> fix: upgrade pulldown-cmark

- .github/workflows/release.yml
> fix: use pre-installed wix

- CHANGELOG.md
- lapce-app/src/config.rs
> Fallback to default theme if key is wrong

- lapce-app/src/config.rs
- lapce-app/src/config/editor.rs
- lapce-app/src/config/terminal.rs
- lapce-app/src/editor.rs
- lapce-app/src/proxy/remote.rs
- lapce-app/src/window_tab.rs
- lapce-proxy/src/dispatch.rs
- lapce-rpc/src/counter.rs
> fix clippy lints

- .github/workflows/ci.yml
- .github/workflows/release.yml
- lapce-app/src/command.rs
- lapce-app/src/window_tab.rs
> fix: reimplement path un/install for macos

- .github/workflows/release.yml
> use macos-14 for release

- .github/workflows/ci.yml
> clean-up ci jobs, fix codecov

- lapce-app/src/app.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/file_explorer/view.rs
- lapce-app/src/panel/plugin_view.rs
- lapce-app/src/panel/problem_view.rs
- lapce-app/src/panel/source_control_view.rs
- lapce-app/src/panel/terminal_view.rs
- lapce-app/src/panel/view.rs
- lapce-app/src/plugin.rs
- lapce-app/src/status.rs
- lapce-app/src/title.rs
- lapce-app/src/window_tab.rs
> disable selection on editor tabs

- defaults/settings.toml
- lapce-app/src/app.rs
- lapce-app/src/config.rs
- lapce-app/src/config/ui.rs
> Make editor tab separator height configurable

- lapce-app/src/terminal/raw.rs
- lapce-app/src/terminal/view.rs
- lapce-core/src/language.rs
1. Terminal file jump: change the judgment point to Ctrl + left mouse click.
2. Optimize some code according to clippy.
> Terminal file jump: change the judgment point to Ctrl + left mouse click.

- lapce-app/src/app.rs
- lapce-app/src/command.rs
- lapce-app/src/main_split.rs
- lapce-app/src/window_tab.rs
> 1. add right-click function for the tab of editor

- Cargo.lock
- Cargo.toml
- lapce-app/Cargo.toml
- lapce-app/src/app.rs
- lapce-app/src/app/grammars.rs
- lapce-app/src/command.rs
- lapce-app/src/tracing.rs
- lapce-core/Cargo.toml
- lapce-core/build.rs
- lapce-proxy/Cargo.toml
- lapce-proxy/src/dispatch.rs
> re-implement grammar/queries update system

- lapce-app/src/command.rs
- lapce-app/src/panel/terminal_view.rs
- lapce-app/src/window_tab.rs
like this:
https://github.com/user-attachments/assets/9290b954-05d9-49bc-94df-324b1a736cff
> Terminal: right-click to add "clear all" function

- lapce-app/src/panel/terminal_view.rs
the effect is as follows
https://github.com/user-attachments/assets/d2a1be3f-8190-43c5-9e2d-3a51a6b111aa
> terminal: double-click to maximize bottom

- lapce-app/src/command.rs
- lapce-app/src/editor.rs
- lapce-app/src/file_explorer/data.rs
- lapce-app/src/file_explorer/view.rs
- lapce-app/src/window_tab.rs
- lapce-rpc/src/file.rs
The effect is as follows:
https://github.com/user-attachments/assets/a9dacfc3-1135-4e8b-954f-8307fff6189e
> editor: Right-click add command "Select in File Explorer"

- .github/workflows/release.yml
- docker-bake.hcl
- extra/linux/docker/alpine/Dockerfile
> fix lapce-proxy build

- Cargo.lock
- Cargo.toml
- lapce-app/src/app/logging.rs
- lapce-app/src/editor.rs
https://github.com/user-attachments/assets/6e2c5587-6f2c-4a43-8eb8-01025bd92bfb
> support to click hint

- lapce-app/src/command.rs
- lapce-app/src/editor.rs
- lapce-app/src/editor_tab.rs
- lapce-app/src/window_tab.rs
- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/plugin/mod.rs
- lapce-proxy/src/plugin/psp.rs
- lapce-rpc/src/proxy.rs
1. editor: Right-click add command "Show Call Hierarchy".Currently, only the interaction with the lsp is complete, and the result is not rendered
2. fixed warnings in clippy report
> 1. editor: Right-click add command "Show Call Hierarchy"

- lapce-app/src/doc.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/editor_tab.rs
- lapce-app/src/main_split.rs
- lapce-app/src/window_tab.rs
Show code lens, but the click event has not been implemented
https://github.com/user-attachments/assets/9c6f7d98-1861-4715-b2bb-528df42392fe
> show code lens

- Cargo.lock
- Cargo.toml
- defaults/keymaps-common.toml
- defaults/keymaps-macos.toml
- defaults/keymaps-nonmacos.toml
- defaults/settings.toml
- lapce-core/Cargo.toml
- lapce-core/src/language.rs
- lapce-core/src/syntax/mod.rs
- lapce-core/src/syntax/util.rs
`remain` crate added to keep the language sorting in check
> add more languages, cleanup code

- Cargo.lock
- lapce-proxy/Cargo.toml
> fix: upgrade locale_config to non-panic version

- lapce-app/src/window_tab.rs
https://github.com/user-attachments/assets/fbba7b60-d8e9-4ce1-acf8-a919face2272
> Optimize "Reveal in File Tree".

- lapce-app/src/panel/plugin_view.rs
- lapce-app/src/plugin.rs
- lapce-app/src/window_tab.rs
2. Display error message after request failure.
> load_available_volts: 1. Add proxy and retry count.

- lapce-app/src/command.rs
- lapce-app/src/editor.rs
- lapce-app/src/main_split.rs
- lapce-app/src/panel/call_hierarchy_view.rs
- lapce-app/src/panel/data.rs
- lapce-app/src/panel/kind.rs
- lapce-app/src/panel/mod.rs
- lapce-app/src/panel/view.rs
- lapce-app/src/window_tab.rs
1. show call hierarchy and jump to location
2. Some styles need further optimization.
https://github.com/user-attachments/assets/e69f2dbf-6166-40a3-8129-80652219dffe
> show call hierarchy and jump to location

- lapce-proxy/src/plugin/lsp.rs
- lapce-proxy/src/plugin/psp.rs
- lapce-proxy/src/plugin/wasi.rs
- lapce-rpc/src/core.rs
> Add error message display for plugins and LSP server.

- lapce-app/src/app.rs
- lapce-app/src/window.rs
#1181
https://github.com/user-attachments/assets/77be80df-e6e2-4802-8881-06dca159b107
> Implement the drag-and-drop to open file feature.

- lapce-app/src/command.rs
- lapce-app/src/editor.rs
- lapce-app/src/window_tab.rs
https://github.com/user-attachments/assets/04152756-4833-4c9c-b8aa-69969868dca1
> Implement feature "Run in Terminal"

- lapce-app/src/command.rs
- lapce-app/src/editor.rs
- lapce-app/src/window_tab.rs
https://github.com/user-attachments/assets/93b0963b-0d57-4235-92c9-a5dd6662f221
> Implement 'Go To Location' functionality in the Diff editor.

- lapce-app/src/doc.rs
- lapce-app/src/main_split.rs
- lapce-app/src/panel/call_hierarchy_view.rs
- lapce-app/src/panel/data.rs
- lapce-app/src/panel/document_symbol.rs
- lapce-app/src/panel/kind.rs
- lapce-app/src/panel/mod.rs
- lapce-app/src/panel/view.rs
- lapce-app/src/window_tab.rs
- lapce-proxy/src/plugin/mod.rs
- lapce-proxy/src/terminal.rs
https://github.com/user-attachments/assets/6e62d1ec-d412-4000-9f51-3a744612b52b
> implement document symbol

- lapce-app/src/file_explorer/data.rs
- lapce-app/src/file_explorer/view.rs
https://github.com/user-attachments/assets/f8d29f3a-b440-47fc-907e-d0b04f690a99
> Implement a selection visual effect in the File Explorer.

- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/plugin/dap.rs
- lapce-rpc/src/dap_types.rs
1. add some log
2. add seq field to response msg
3. support runInTerminal in Windows
4. Changed ConfigurationDone to an asynchronous request
> about dap:

- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/plugin/mod.rs
- lapce-proxy/src/plugin/psp.rs
- lapce-rpc/src/proxy.rs
> support codeLens/resolve of lsp

- lapce-app/src/keymap.rs
Fix the video display issue:
https://github.com/user-attachments/assets/1f9627d1-ef6c-41b5-9939-e7cf30ae74a1
> Ensure the line height is not too small.

- lapce-app/src/command.rs
- lapce-app/src/editor.rs
- lapce-app/src/window_tab.rs
https://github.com/user-attachments/assets/602405e9-bd63-4282-bd89-128a96a760b1
> implement "Open in GitHub" command

- lapce-app/src/terminal/panel.rs
- lapce-app/src/window_tab.rs
- lapce-proxy/src/terminal.rs
- lapce-rpc/src/core.rs
> Closing a terminal tab should also close the underlying terminal.

- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/lib.rs
- lapce-proxy/src/plugin/catalog.rs
- lapce-proxy/src/plugin/dap.rs
- lapce-proxy/src/plugin/lsp.rs
- lapce-proxy/src/plugin/mod.rs
- lapce-proxy/src/plugin/psp.rs
- lapce-proxy/src/plugin/wasi.rs
- lapce-proxy/src/terminal.rs
- lapce-proxy/src/watcher.rs
> add error log

- lapce-app/src/app.rs
- lapce-app/src/config.rs
- lapce-app/src/config/watcher.rs
- lapce-app/src/db.rs
- lapce-app/src/proxy.rs
> 1. add some error log for lapce-app

- lapce-app/src/editor.rs
- lapce-app/src/keypress/keymap.rs
- lapce-app/src/palette.rs
- lapce-app/src/plugin.rs
- lapce-app/src/proxy/remote.rs
- lapce-app/src/terminal/data.rs
- lapce-app/src/terminal/event.rs
- lapce-app/src/terminal/raw.rs
- lapce-app/src/update.rs
- lapce-app/src/window.rs
- lapce-app/src/window_tab.rs
> 1. add another error log for lapce-app

- lapce-core/src/directory.rs
- lapce-core/src/syntax/mod.rs
> 1. add error log for lapce-core

- lapce-rpc/src/core.rs
- lapce-rpc/src/proxy.rs
> 1. add error log for lapce-rpc

- lapce-app/src/palette.rs
- lapce-app/src/palette/kind.rs
This makes it more convenient for the user.
> Set the Palette to default to the Help Palette.

- lapce-app/src/app.rs
- lapce-app/src/config/watcher.rs
> add some error logging

- lapce-app/src/code_lens.rs
- lapce-app/src/terminal/data.rs
- lapce-app/src/terminal/raw.rs
- lapce-app/src/window_tab.rs
- lapce-rpc/src/dap_types.rs
CodeLens will use this feature to complete the debugging information.
> Supports tracing the output of the task.

- lapce-app/src/terminal/panel.rs
- lapce-app/src/window_tab.rs
> When running a task, display the terminal(debug) panel

- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/plugin/mod.rs
- lapce-proxy/src/plugin/psp.rs
- lapce-rpc/src/proxy.rs
> Implement the LSP implementation method.

- lapce-app/src/app/logging.rs
- lapce-app/src/command.rs
- lapce-app/src/config/icon.rs
- lapce-app/src/editor.rs
- lapce-app/src/main_split.rs
- lapce-app/src/panel/kind.rs
- lapce-app/src/panel/mod.rs
- lapce-app/src/panel/references_view.rs
- lapce-app/src/panel/view.rs
- lapce-app/src/window_tab.rs
The effect is as shown in the following video:
https://github.com/user-attachments/assets/c3f4e14e-dbf8-4e50-804d-63f3f18960bc
the desired final effect is as shown in the image:
> 1. Preliminary implementation of the "Find References" panel

- lapce-app/src/db.rs
- lapce-app/src/editor.rs
- lapce-app/src/panel/data.rs
- lapce-app/src/panel/kind.rs
- lapce-app/src/panel/references_view.rs
> 1. Add default position.

- defaults/settings.toml
- lapce-app/src/app.rs
- lapce-app/src/config/editor.rs
- lapce-proxy/src/plugin/lsp.rs
2. Add some LSP logs.
The effect is as shown in the following video:
https://github.com/user-attachments/assets/4ff4d18b-6912-4f1f-9685-62aa2e020abf
> 1. Add the editor setting completion_item_show_detail.

- lapce-proxy/src/plugin/catalog.rs
Add an error prompt "Debugger not found. Please install the appropriate plugin."
> Add an error prompt.

- lapce-app/src/app.rs
- lapce-core/src/language.rs
> optimize some logs

- lapce-app/src/app.rs
> Fix loading the shell environment in Windows.

- lapce-app/src/command.rs
- lapce-app/src/editor.rs
- lapce-app/src/palette.rs
- lapce-app/src/window_tab.rs
Add a right-click command "Add Run Debug Config" to quickly add a configuration to the run.toml file
the effect is as shown in following video:
https://github.com/user-attachments/assets/043a28c6-cf18-4382-957d-34b8b16d927a
> Right click

- lapce-app/src/terminal/data.rs
- lapce-app/src/terminal/raw.rs
> Reimplement the functionality to capture terminal output.

- lapce-proxy/src/buffer.rs
- lapce-proxy/src/dispatch.rs
- lapce-rpc/src/file_line.rs
- lapce-rpc/src/lib.rs
- lapce-rpc/src/proxy.rs
This is part of optimizing get_references.
> Add the 'references_resolve' method to the proxy.

- lapce-app/src/editor.rs
- lapce-app/src/file_explorer/view.rs
- lapce-app/src/main_split.rs
- lapce-app/src/panel/implementation_view.rs
the effect is as shown in following video:
https://github.com/user-attachments/assets/b1014d69-fc5c-43f8-95b5-894c0928c31a
> Optimize the display of implementations

- lapce-app/src/app.rs
- lapce-app/src/db.rs
- lapce-app/src/palette.rs
- lapce-app/src/plugin.rs
- lapce-app/src/proxy.rs
- lapce-app/src/proxy/remote.rs
- lapce-app/src/window_tab.rs
> Add thread names for easier tracking and troubleshooting.

- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/plugin/psp.rs
- lapce-rpc/src/core.rs
- lapce-rpc/src/proxy.rs
> Implement the LSP $/cancelRequest notification

- lapce-app/src/file_explorer/view.rs
> Fix the issue where the width is too short.

- defaults/settings.toml
- lapce-app/src/config/core.rs
- lapce-app/src/file_explorer/data.rs
- lapce-core/build.rs
> 1.fix typo

- lapce-app/src/panel/call_hierarchy_view.rs
- lapce-app/src/panel/document_symbol.rs
- lapce-app/src/panel/implementation_view.rs
> change GoToLocation to JumpToLocation

- lapce-app/src/editor.rs
- lapce-app/src/editor/gutter.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/panel/references_view.rs
https://github.com/user-attachments/assets/ae2c7629-1ee3-49ac-824a-d9d6dea4fc6a
> Navigate to the location when clicking the sticky header.

- lapce-app/src/doc.rs
> Format the document before auto-saving.

- lapce-proxy/src/plugin/dap.rs
> Launch DAP with environment variables.

- lapce-app/src/main_split.rs
- lapce-proxy/src/dispatch.rs
- lapce-rpc/src/core.rs
> Handle the file deletion event.

- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/plugin/mod.rs
- lapce-proxy/src/plugin/psp.rs
- lapce-rpc/src/proxy.rs
> Implement the `foldingRange` request in the LSP

- lapce-app/src/doc.rs
- lapce-app/src/panel/document_symbol.rs
> add the `file` symbol to document symbol panel

- lapce-app/src/panel/implementation_view.rs
> fix debug name

- lapce-app/src/doc.rs
- lapce-app/src/editor.rs
- lapce-app/src/editor/gutter.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/main_split.rs
- lapce-app/src/window_tab.rs
1. The styling needs further optimization.
2. The effect is shown in the following video.
https://github.com/user-attachments/assets/3b492c3a-d2db-4e47-8bac-1b97eb245e53
> display folding icon

- lapce-app/src/doc.rs
- lapce-app/src/window_tab.rs
> Update the inlay hint after receiving the notification.

- lapce-app/src/panel/implementation_view.rs
> Sort and filter `Reference`

- defaults/run.toml
- lapce-app/src/terminal/data.rs
> `program` support ${workspace}

- lapce-app/src/settings.rs
https://github.com/user-attachments/assets/7d0cec47-21eb-444d-90bd-e2528dc26a7d
> The setting value should update when the settings file changes.

- lapce-app/src/doc.rs
> cancel to get folding range

- lapce-app/src/app.rs
> fix: hide process window when sourcing shell env

- lapce-app/src/app.rs
> Focus window when open file in a existing window

- lapce-app/src/app.rs
- lapce-proxy/src/lib.rs
Opinionated way of resolving #3646 by only mutating PATH if exe dir not already present.
> only register lapce dir in PATH if not already present

- Makefile
- README.md
- lapce.spec
I have added the header comment to the `Makefile`.
Also, slightly improved RPM package description, and README.md description of Lapce.
I have also removed '?' from the AWK regex in `make help`. Non-greediness can't be achieved by using '?' like that.
> Docs improvement (minor)

- lapce-app/src/app.rs
> Fix pointer events getting intercepted.

- Cargo.lock
- Cargo.toml
> fix: git2 linking on windows

- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
> ci: re-enable vendor, add workaround for dpi crate

- .github/workflows/release.yml
- docker-bake.hcl
> ci: remove ubuntu oracular, add plucky
