- icons/unsaved.svg
- lapce-data/src/editor.rs
This displays a circle icon when the file is not saved, making it easier to know what needs to be saved and what doesn't that you have open.  
Similar to vscode, if you hover over the tab the dot-icon is replaced with the close-icon.  
Note that this does not add any alert when closing a file that has not been saved, which is a feature that should also be added.
> Add icon when file has not been saved

- Cargo.toml
Close #58 
If the version of `rustc` is lower than 1.58, it will give a hint like this:
```
cannot be built because it requires rustc 1.58 or newer, while the currently active rustc version is 1.57.0
```
> Set msrv as 1.58

- .github/workflows/pr.yml
This PR tries to prevent broken code from getting merged. I've chosen `cargo check` instead of build for quick completion. If this change is acceptable, it should be enabled in the master branch protection rules.
The workflow does not run for drafts.
> Run `cargo check` for each pull request that is ready for review

- Cargo.lock
- defaults/keymaps-common.toml
- defaults/keymaps-linux.toml
- defaults/keymaps-macos.toml
- defaults/keymaps-windows.toml
- lapce-data/Cargo.toml
- lapce-data/src/keypress.rs
- lapce-data/src/keypress/keypress.rs
- lapce-data/src/keypress/loader.rs
- lapce-data/src/keypress/mod.rs
- lapce-data/src/state.rs
- lapce-ui/src/keymap.rs
This PR:
- Adds an empty common keymap file, to allow deduplicating existing default keymaps
- Cleans up the keymap parsing function to use simpler code and avoid several unnecessary allocations.
These changes came up while trying to figure out the cause of #116 and #185 - I didn't make any progress on that front, but these changes might make the parser code slightly easier to understand. Maybe, hopefully :)
> Keymap parsing and keypress handling improvements

- Cargo.lock
- lapce-data/Cargo.toml
- lapce-data/src/config.rs
This adds the ability to load `.toml` themes from a folder (the same folder that `settings.toml` resides in) named `themes`. The name of the theme is the same as its filename but with out the `.toml` extension, note that this means it is case-sensitive on platforms where case-sensitivity matters.  
Example (bad) theme I threw together:  
I added a `Themes` structure because that felt more reasonable for a `load_theme` function to be on, and allows adding more later on rather than putting them on `Config`. I also added a type alias `Theme` to make it more clear what the hashmap is in places that use themes.
> Implement ability to load themes from folder

- Cargo.lock
- lapce-data/Cargo.toml
- lapce-ui/Cargo.toml
This upgrades the UUID create up a version, and removes the listing of it in lapce-ui since it is unused. This gets rid of a good number of dependencies that need to be built (640 -> 622 on my system). The reason is that the current version of the UUID crate depends on an older version of Rand and by default brought in several different RNG algorithms that we didn't use in the first place. The latest crates.io version, however, uses a smaller crate `getrandom` and so has far less unneeded dependencies.  
As well, `getrandom` was already depended upon by other crates we use so it doesn't even make the number go up.
> Upgrade UUID

- Cargo.lock
- lapce-data/Cargo.toml
- lapce-data/src/data.rs
- lapce-data/src/proxy.rs
- lapce-proxy/Cargo.toml
- lapce-proxy/src/plugin.rs
- lapce-ui/Cargo.toml
Rather than using reqwest, this PR switches to using the smaller crate ureq (https://crates.io/crates/ureq). This is primarily because not many features are needed, and so a smaller library helps to decrease the number of dependencies to hopefully make it faster to build (both for the initial build and incremental). Ureq is a blocking api, while reqwest does not have to be, but the editor only uses the blocking api (which makes sense at the current time). Due to the simplicity of the changes, if the more versatile features of reqwest are legitimately needed, moving back would be easy.  
This made me go from 640 -> 623 dependencies (with the 'update uuid' pr, this becomes 606 dependencies).  
Note that I would appreciate testing the gz decoder path for downloading lapce-proxy. I don't …
> Switch to using ureq instead of reqwest

- lapce-ui/src/settings.rs
This fixes a weird rendering issue, as shown in the screen shot below.
Without this patch, depending on the size and position of the window, sometimes I got a settings window like this (worst case):
> Round widget coordinates in Settings

- lapce-ui/src/bin/lapce.rs
This PR disabled the windows subsystem attribute in debug builds, enabling console output for debug purposes.
> Allow console output on windows debug builds

- lapce-data/src/editor.rs
- lapce-ui/src/editor.rs
Either I was just lucky, ~or this improves memory usage considerably~ no, I was just lucky. Either way, there's little point in cloning this hashmap multiple times on every keypress.
> Stop cloning the panel hashmap

- lapce-data/src/editor.rs
- lapce-ui/src/editor.rs
This fixes minor issues where completion would remain when clicking in the editor, and when cutting/pasting text.  
I'm sure more of the commands have this issue, and should cancel/update completion within them, but this PR does it for a few common commands.
> Fix some places where completion would remain when it should not

- defaults/keymaps-common.toml
- lapce-data/src/code_action.rs
- lapce-data/src/command.rs
- lapce-data/src/editor.rs
- lapce-data/src/menu.rs
- lapce-data/src/palette.rs
- lapce-data/src/settings.rs
- lapce-ui/src/code_action.rs
- lapce-ui/src/menu.rs
- lapce-ui/src/settings.rs
- lapce-ui/src/window.rs
This adds support for hiding the completion by pressing esc, similar to vscode. I often rely on this since I navigate with the arrow keys, and use esc to quickly hide completion if I decide to move down/up. This is also useful if there is a bug in which the completion menu remains when it should not (such as #227 ).
> Implement more general closing of modals

- Cargo.lock
- lapce-core/Cargo.toml
- lapce-core/src/language.rs
Seems to work fine :)
The code lens I don't understand enough to implement proper support for, it replaces the entire file like this atm:
> Add PHP syntax highlighting

- lapce-ui/src/tab.rs
This PR fixes the following crash:
I don't know why this happened, though, so this might not be the root cause of the issue.
> Fix crash caused by overflow

- lapce-data/src/editor.rs
- lapce-data/src/proxy.rs
- lapce-proxy/src/lsp.rs
- lapce-ui/src/problem.rs
- lapce-ui/src/tab.rs
Fixes #187
This PR fixes code navigation features where the LSP returns a file path in the form of `file:///<drive letter>:/...`.
> Fix incorrect file path parsing on windows

- lapce-ui/src/code_action.rs
I got a crash when trying to apply a refactoring assist (replace if-let with match, in my case). This PR ignores the edit, instead of crashing on it.
> Don't crash when code action does not exist

- Cargo.lock
- lapce-core/Cargo.toml
- lapce-core/src/language.rs
- Supports "c" and "h" filename extensions
Linked in encompassing issue: https://github.com/lapce/lapce/issues/272
> Add tree-sitter C support

- lapce-ui/src/app.rs
- lapce-ui/src/bin/lapce.rs
> Renamed "pub fn lanuch" to "pub fn launch"

- lapce-data/src/editor.rs
This fixes a crash that I introduced when making undo/redo update completion. This would update the completion _before_ the mouse cursor was updated, which would let the offset be in an invalid location. This merely fixes that by updating the completion after the update of the cursor.
> Fix crash when offset does not exist in undo/redo

- Cargo.lock
- lapce-core/Cargo.toml
- lapce-core/src/language.rs
Add tree-sitter Cpp support to cpp, cxx, cc, hpp, hxx file name extensions.
Tree Sitter Support Issue: https://github.com/lapce/lapce/issues/272
> Add Cpp tree-sitter support

- lapce-data/src/movement.rs
Some of the new test cases failed with the old code. Namely, `Movement::Up.update_index(0, 1, 1, true);` previously gave `1` which resulted in the crash worked around in https://github.com/lapce/lapce/pull/269
This issue is visible when the language server offers a single code assist. In this case, when the assist list is visible, the up key allows switching selection between the actual code assist, and an invalid item that causes a visual glitch. Selecting this invalid item previously (before #269) crashed Lapce.
A demonstration of the issue:
https://user-images.githubusercontent.com/977627/160213054-e6315242-e04e-47e2-8d71-d7bc1a018db1.mp4
With this PR applied, this behaviour does not occur, and pressing the up/down arrows has no visual effect (because of this, I did not record a video, …
> Fix and simplify `Movement::update_index`

- lapce-data/src/completion.rs
- lapce-data/src/keypress/mod.rs
- Use `fuzzy_match` where the indexes are not used
- Remove unnecessary copying
> Fuzzy filtering related cleanups

- lapce-ui/src/editor/tab_header_content.rs
Clicking/dragging with right or middle mouse button is confusing, and https://github.com/lapce/lapce/pull/100 would use the middle button to close a tab, so let's limit the "normal" interactions to the left mouse button.
> Only react to left clicks on editor tabs headers

- defaults/dark-theme.toml
- defaults/light-theme.toml
- defaults/settings.toml
- lapce-data/src/command.rs
- lapce-data/src/config.rs
- lapce-data/src/data.rs
- lapce-data/src/editor.rs
- lapce-data/src/hover.rs
- lapce-data/src/lib.rs
- lapce-data/src/proxy.rs
- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/lsp.rs
- lapce-rpc/src/proxy.rs
- lapce-ui/src/editor.rs
- lapce-ui/src/hover.rs
- lapce-ui/src/lib.rs
- lapce-ui/src/tab.rs
This implements hover support for language servers.  
Currently this is limited in some ways. (These could be opened as issues)  
- No markdown support. RA doesn't produce good plaintext output as well. This would not be too challenging to add.
- Could look better
- Would be useful to be able to select text inside them
- Able to show hover with a keybind
- Hide when mouse moves from the target word in document, similar to vscode
> Implement hover support

- lapce-ui/src/window.rs
This fixes the (incorrectly) silenced clippy warning about mutable borrow reservation conflict. (See: https://github.com/rust-lang/rust/issues/59159 )
> Avoid mutable borrow reservation conflict

- lapce-data/src/data.rs
- lapce-data/src/editor.rs
- lapce-ui/src/editor/header.rs
Part 3 or the refactor started in #295, containing the commits from #296
This is a smaller step, and one not strictly necessary.
> Refactor towards testability, step 3: Remove `workspace` field from `LapceEditorBufferData`

- lapce-data/src/buffer.rs
- lapce-data/src/config.rs
- lapce-ui/src/svg.rs
This PR tries to clean up syntax highlighting by not creating temporary strings just to look up in a hashmap. Besides that, this PR extracts some Theme related operations from Config.
> Don't allocate strings for syntax highlight lookups

- Cargo.lock
- lapce-data/Cargo.toml
- lapce-data/src/command.rs
- lapce-data/src/config.rs
- lapce-data/src/data.rs
- lapce-data/src/palette.rs
- lapce-data/src/proxy.rs
- lapce-data/src/state.rs
- lapce-ui/src/tab.rs
- lapce-ui/src/title.rs
This PR adds support for remote workspaces using WSL on Windows. This works similarly to the ssh functionality but uses the `wsl` command to interact with the remote instead of ssh.
Closes #198
> Add support for WSL

- lapce-ui/src/editor/tab_header_content.rs
Add support for closing tab by clicking middle mouse button. This is the default behavior of vscode, firefox and chrome. But feel free to reject it, since it's just a small tweak.
> Close the tab by clicking middle mouse button

- lapce-ui/src/tab.rs
- lapce-ui/src/title.rs
Fixes #337
Includes a bonus fix when the path is not a valid `str`
> Fix window title crash on opening volume root (e.g. `C:\`)

- lapce-ui/src/explorer.rs
Druid seems to generate a mouse move event **after** updating the lifecycle to no longer hot. This unexpected event set the `hovered` field back to some value, instead of leaving it `None`, so the hover styling did not get cleared on mouse leave. This PR only handles mouse events if the file list widget is hot, to ignore this additional event.
> Fix explorer hover effect not resetting on mouse leave

- lapce-ui/src/panel.rs
- lapce-ui/src/terminal.rs
Fixes https://github.com/lapce/lapce/issues/348
Screen now looks like this
Code is not super-elegant, this is my best shot without refactoring a lot more. From the user's perspective the terminal is everything below and including the header that contains the word "Terminal", as that is where the separator bar is, that can be moved with the mouse. In the code base, the background for these areas is split between the terminal-proper and the PanelMainHeader struct BUT the same code in PanelMainHeader is also used to paint the "File Explorer", "Source Control" headings etc. Luckily there was a `kind` member which allowed me to just pick out the terminal and preserve current behaviour for the other UI elements.
It does beg the question of how the theme files should correspond to the UI areas. …
> Make terminal paint in proper background color

- lapce-ui/src/tab.rs
Resolves #344
@dzhou121 ~do you have a better idea? This PR is pretty bad, in that it's not the widgets that pass focus back to the main split (I couldn't get that to work, only for FileExplorer). This means, if one of the panels will support any kind of keyboard input in the future, the implementor needs to know about this special casing.~
> Pass unhandled key events through the default handler

- lapce-data/src/state.rs
- lapce-proxy/src/terminal.rs
This leaves just one Counter struct definition, in the RPC crate.
> Delete unused Counters

- defaults/keymaps-common.toml
This adds an alternative keymap to `normal_mode` when modal editing is enabled.
> Adds alternative keymap to normal_mode

- lapce-data/src/buffer.rs
- lapce-data/src/editor.rs
This PR uses `Option::as_deref()` to turn `Option<String>` into `Option<&str>`, allowing to remove unnecessary cloning.
> Avoid cloning compare strings

- lapce-data/src/config.rs
- lapce-data/src/data.rs
- lapce-data/src/editor.rs
- lapce-ui/src/editor.rs
- lapce-ui/src/editor/gutter.rs
- lapce-ui/src/editor/view.rs
- lapce-ui/src/terminal.rs
Make text measurement more efficient and regularise the calls to these methods.
cc @bugadani 
There are still some direct calls to `new_text_layout` - I will tackle them in another PR if this is OK. The diff is a bit confused, you might want to look at `config.rs` by itself.
> Improve text measurement

- lapce-data/src/config.rs
- lapce-ui/src/keymap.rs
- lapce-ui/src/palette.rs
- lapce-ui/src/settings.rs
Such calls are not necessary when passing a static string.
I also included a few comments from my previous PR that I intended to do but it was merged before I could get round to it :-)
> Remove some unnecessary calls of to_string when calling new_text_layout

- lapce-ui/src/tab.rs
One more case found for #337 that happens using multiple window-scale tabs
> Fix crash when tab title is root or invalid

- lapce-data/src/buffer.rs
- lapce-data/src/buffer/data.rs
- lapce-data/src/buffer/decoration.rs
- lapce-data/src/data.rs
- lapce-data/src/db.rs
- lapce-data/src/editor.rs
- lapce-data/src/movement.rs
- lapce-data/src/palette.rs
- lapce-ui/src/editor.rs
- lapce-ui/src/editor/gutter.rs
- lapce-ui/src/editor/header.rs
- lapce-ui/src/editor/tab.rs
- lapce-ui/src/editor/view.rs
- lapce-ui/src/settings.rs
- lapce-ui/src/tab.rs
This PR splits up Buffer into three parts:
- `BufferData`, which contains everything strictly necessary for edits and undo/redo.
- `BufferDecoration` which holds the special sauce provided by Buffer, e.g. syntax highlighting. This is split off so it can be wrapped into a decorator type for the fancy edit operations that e.g. trigger commands.
- the rest - some of the `Buffer` data the other two groups didn't need (yet).
This PR introduces the `BufferDataListener` trait to observe and control the edit apply process, `EditableBufferData` that exposes the actual low-level edit operations, combined with a listener object, and `BufferEditListener` that is used by `Buffer` to glue things together.
Names are bad and are subject to change.
> Refactor buffer editing to allow testing

- lapce-ui/src/editor/tab_header_content.rs
- Only start actually dragging on mouse move
- Fix an edge case: when the user drags a tab to the top menubar and releases left mouse button, then moves the cursor back to the editor, the tab is no longer dragged.
- Only close tabs on `MouseUp` to allow cancelling
- Changes cursor to Pointer when it is inside a tab, not just in the close icon. (VSCode behavior)
For whatever reason, clicking the right mouse button during a drag cancels the drag. This behaviour does not come from the tab header component and was there previously.
> Close tabs on mouse up, don't start dragging until tab is actually dragged

- lapce-core/src/language.rs
- lapce-ui/src/svg.rs
Lapce should recognize more C++ file extensions, this PR adds those missing extensions.
This is the most "official" list I could find for C++ extensions: https://gcc.gnu.org/onlinedocs/gcc-4.4.1/gcc/Overall-Options.html#index-file-name-suffix-71 and I've basically only added the extensions that are recognized by other popular editors (specifically VSCode).
> Add support for more C++ extensions

- lapce-data/src/keypress/mod.rs
- lapce-ui/src/terminal.rs
As the terminal current only has one mode to consider it should handle all interactions that are addressed to it.
Because the terminal is not handling all interactions some commands that should not be called (such as palette.line) are being handled by another dialogue and thus executed even if the mode is not supported.
Fixes: #423
> fix: Terminal should swallow interactions

- lapce-ui/src/terminal.rs
Closes #221 
This change reflects the behavior I get in xfce4-terminal and I tested it with both zsh and bash.
> Fixed backspace in terminal erasing whole word

- lapce-data/src/buffer.rs
- lapce-data/src/buffer/data.rs
- lapce-data/src/buffer/decoration.rs
- lapce-data/src/editor.rs
- lapce-data/src/editor/commands/insert_chars.rs
- lapce-data/src/editor/commands/insert_tab.rs
- lapce-data/src/editor/commands/mod.rs
- lapce-data/src/editor/commands/test/mod.rs
May be extremely broken.
This PR, besides extracting character insertion, refactors the algorithm to deal with individual selection regions separately, because each region may have different behavior requirements.
> Turn typing into an edit command

- lapce-data/src/data.rs
Target the source window for the 'OpenFolder' operation.
Fixes: #388
> fix: Open the Folder in the current window rather than a different one

- lapce-core/src/syntax.rs
- lapce-data/src/command.rs
- lapce-data/src/explorer.rs
- lapce-ui/src/editor/tab.rs
- lapce-ui/src/editor/tab_header_content.rs
- lapce-ui/src/explorer.rs
- lapce-ui/src/picker.rs
Part 1 of #383
This PR adds an event that is fired when the user clicka file in file explorer, or switches tabs. This event is handled by the file explorer file list, and sets the active highlighted file's path.
This PR does not open a folder structure if the file is in a closed folder.
> Highlight active file on tab change, pt 1

- lapce-data/src/buffer.rs
- lapce-data/src/data.rs
- lapce-data/src/editor.rs
- lapce-data/src/movement.rs
- lapce-data/src/palette.rs
- lapce-data/src/proxy.rs
- lapce-data/src/terminal.rs
- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/lsp.rs
- lapce-ui/src/code_action.rs
- lapce-ui/src/palette.rs
- lapce-ui/src/scroll.rs
- lapce-ui/src/tab.rs
I consider this attribute somewhat dangerous as it might hide variables that shouldn't be. This was the reason why in #426 the `tab_id` variable wasn't marked as unused, indirectly leading to a bug.
> Remove `allow(unused_variables)` attributes

- Cargo.lock
- lapce-core/Cargo.toml
- lapce-core/src/language.rs
Add the tree-sitter crate for ruby and integrate into the language setup.
Currently against a fork of 'tree-sitter-ruby' till a pr to bump the pinned tree-sitter version.
> [TreeSitter] Add ruby language support

- Cargo.lock
- Cargo.toml
- lapce-data/Cargo.toml
- lapce-ui/Cargo.toml
I noticed that recently the dev builds of lapce are running slower than they used to, perhaps because of the rendering engine change. It is possible to get the best of both worlds with cargo - a good debugging experience with fast builds for your own code, AND release-optimised code for your dependencies. I find this to be nice and speedy and yet still debuggable, this works well when you don't care about stepping into your dependencies.
To demonstrate, I have created a new `fastdev` profile in the root `Cargo.toml`. Alternatively, if nobody cares about stepping into the dependencies for debugging purposes, it is possible to configure the `dev` profile this way.
> Create the fastdev profile

- lapce-ui/src/panel.rs
- lapce-ui/src/window.rs
Before: note the drop shadow over the inactive tab, and that the hovered file overlaps the bottom drop shadow
After:
> File explorer header UI fixes

- lapce-ui/src/editor.rs
- lapce-ui/src/menu.rs
- lapce-ui/src/title.rs
- Don't assume local and window coordinates are equal
- Re-layout menu if origin changes
- Use the proper transform method instead of manually implementing it
> Menu improvements

- lapce-ui/src/editor/tab.rs
- lapce-ui/src/tab.rs
Every close button on the UI uses the close icon svg, except for window tabs. This PR "fixes" this inconsistency.
> Use svg as the close icon in window tabs

- lapce-ui/src/explorer.rs
- lapce-ui/src/panel.rs
- lapce-ui/src/plugin.rs
- lapce-ui/src/problem.rs
- lapce-ui/src/search.rs
- lapce-ui/src/source_control.rs
- lapce-ui/src/tab.rs
- lapce-ui/src/terminal.rs
There are probably more places where this could be used, but for now, Panel headers only.
This PR introduces a read-only string type that is either a `&'static str` or a cheap to clone `Arc<str>`. This PR implements `TextStorage` for this type so it can be used in text layouts.
> Introduce `ReadOnlyString`

- Cargo.lock
- lapce-data/src/data.rs
- lapce-data/src/split.rs
- lapce-ui/src/keymap.rs
- lapce-ui/src/split.rs
This isn't an ideal solution as there is no way to see the end of the command names, but it's still a lot better than the ugly overdrawing that existed previously.
> Don't draw shortcut names outside of the cells

- README.md
On Ubuntu 22.04 LTS:
```
$ apt show libfontconfig1-dev 
Package: libfontconfig1-dev
Version: 2.13.1-4.2ubuntu5
Priority: optional
Section: libdevel
Source: fontconfig
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian freedesktop.org maintainers <pkg-freedesktop-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 26.6 kB
Depends: libfontconfig-dev (= 2.13.1-4.2ubuntu5)
Homepage: https://www.freedesktop.org/wiki/Software/fontconfig/
Download-Size: 1,836 B
APT-Sources: http://us.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
Description: generic font configuration library - dummy package
Fontconfig is a font configuration and customization library, which
does not depend on …
```
> Doc: do not specify a transitional package

- extra/linux/dev.lapce.lapce.desktop
- extra/linux/dev.lapce.lapce.metainfo.xml
During my attempt to publish [Lapce on Flathub](https://github.com/flathub/flathub/pull/3155), it was suggested to add the .desktop file and AppStream metadata upstream.
Both files can be used by all distribution maintainers and therefore make it easier to package Lapce for different Linux distributions. So it makes sense to hve these in the Lapce repository.
Here is more info on Appstream: https://www.freedesktop.org/software/appstream/docs/
There is one caveat: The release-tags in metainfo.xml should be updated with every release by adding a child like `<release version="0.1.0" date="2022-05-12"/>` ([sorted latest-to-oldest](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-releases), or just keep one child with the latest release).
If that isn't desired, it's …
> add Linux .desktop file and Appstream metadata

- extra/linux/dev.lapce.lapce.metainfo.xml
It appears that AppStream metadata must be under certain reviewed licenses:
https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-metadata_license
Therefore `flatpak run org.freedesktop.appstream-glib validate extra/linux/dev.lapce.lapce.metainfo.xml` complains when Apache-2.0 is used.
This change is solely for the metadata, the project license remains unaffected.
> Change Appstream metadata license

- lapce-data/src/editor.rs
- lapce-data/src/hover.rs
- lapce-ui/src/hover.rs
This lets the user hover over a diagnostic in the editor and have the text displayed in the hover window.  
I decided to put the diagnostics before the documentation (VSCode does after) because typically they are small and more pertinent anyway, though making a config setting to support both would not be hard.  
There are some improvements that could be made, such as showing related things (ex, I believe: if you use a non-mutable variable in a way that needs it to be mutable, and rustc will provide an extra underline under the definition of that variable along with the diagnostic where you use it incorrectly), but this works as an initial impl.
I drew a rect for the separator since I don't know of any other place that uses a separator like that, so I was unsure if there was existing …
> Show diagnostics on hover

- lapce-data/src/data.rs
- lapce-data/src/db.rs
- lapce-data/src/document.rs
- lapce-data/src/editor.rs
- lapce-ui/src/editor.rs
- lapce-ui/src/editor/header.rs
- lapce-ui/src/editor/tab_header.rs
- lapce-ui/src/editor/tab_header_content.rs
- lapce-ui/src/editor/view.rs
This PR addresses [my comment](https://github.com/lapce/lapce/issues/447#issuecomment-1128085250) in #447 about using unique buffer names for the scratch buffers.
I basically just added a String to the `BufferContent::Scratch` enum and fixed the compilation errors, discards being all that was required with the exception of the `save_as_success` function in `data.rs`.
> Implement 'new N' names for scratch buffers.

- lapce-data/src/data.rs
No longer allocates multiple strings. It was not a big deal but I prefer to avoid allocation as a best practice when I can.
> Improve get name for new file

- lapce-proxy/src/buffer.rs
Currently lapce overwrites permissions whenever file is saved
I've noticed that when my scripts lost exec bits
Don't know if it's proper fix in correct place
> fix: don't overwrite permissions

- Cargo.lock
- lapce-data/Cargo.toml
- lapce-data/src/data.rs
- lapce-data/src/proxy.rs
- lapce-proxy/Cargo.toml
- lapce-proxy/src/plugin.rs
Lapce's plugin list is hosted on github pages. Some users need proxy to be able to access github sites. ureq doesn't read system proxy settings, which will cause an empty plugin list for some users. Switch it back to reqwest to fix that.
> switch ureq to reqwest for system proxy support

- defaults/settings.toml
- lapce-data/src/config.rs
- lapce-ui/src/editor/gutter.rs
Fixed #35  
This just allows the user to change the line numbering in modal mode to the more typical sequential method.  
This leaves the default as relative, like it is now.  
Though, I do think it would be a nice future feature to have this more customizable (ex: relative line mode in insert mode?), but this covers the case where people want it always sequential.
> Add a setting to toggle relative line numbering in modal mode

- lapce-ui/src/palette.rs
Fixes #614 
The issue was that it was just having the end of the range `i+1` rather than the length of the character which panics (though the docs for `range_attribute` only indirectly allude to indexing like a slice) on multibyte characters.  
There's still a bit of a bug (unicode characters will hit that `log::warn`) because of fuzzy-matcher's indices not working for unicode, which I mentioned in the discord, but that just stops it from highlighting them properly.
> Handle unicode characters in palette line-search

- lapce-ui/src/editor.rs
- lapce-ui/src/find.rs
Added the amount of results found for the query into the `FindBox` widget in this fashion:
Does not relate to any github issue I can find, but was a thing someone was looking for.
> Added result numbers to the FindBox widget.

- lapce-core/src/command.rs
- lapce-data/src/editor.rs
This adds the ability to use `ctrl+space` (and meta+space) to display the completions without having any text.  
I believe Lapce had this before, and there was already keymaps for it in the code, but I guess it got removed?  
Though, this is imperfect, because the sorting that Rust Analyzer provides for us by default isn't great. See #628
> Add GetCompletion command to display completion even with no input

- defaults/settings.toml
- lapce-data/src/command.rs
- lapce-data/src/config.rs
- lapce-data/src/data.rs
- lapce-data/src/editor.rs
- lapce-ui/src/tab.rs
This gives the user the ability to decide whether they want the editor to format the document when they save the file. It keeps the current default of `true`.
> Add an option for whether to format on save

- Cargo.lock
- lapce-core/Cargo.toml
- lapce-core/src/language.rs
- lapce-ui/Cargo.toml
> Add tree-sitter langs Haskell, CodeQL, and Swift

- Cargo.lock
- lapce-ui/Cargo.toml
- lapce-ui/build.rs
This uses the `winres` crate https://docs.rs/winres/latest/winres/ to set an icon.
I based this on nu's usage - see https://github.com/nushell/nushell/blob/9f07bcc66f50f8dd63471f3ae6b697e6832ce89f/build.rs
This brings the 'portable' version to parity with the installer based version, as well as manually installed versions.
> Add an executable icon on Windows

- lapce-data/src/document.rs
Previously, pressing <kbd>Home</kbd> would always return to the first non-indent character
However, a nicer behaviour once you are at that character is to move to the start of the line instead.
This is consistent with the behaviour of vscode.
> Improve the behaviour of Home in non-vim mode

- lapce-data/src/editor.rs
Currently the rust-url crate doesn't handle windows drive letters. Compare to e.g. [vscode-uri](https://github.com/microsoft/vscode-uri/blob/96acdc0be5f9d5f2640e1c1f6733bbf51ec95177/src/uri.ts#L182-L183), which does do this normalisation.
Note that our handling of cross-drive paths is not very robust, so we need to consider what assumptions are made about paths being on the host. (Since at the moment, code actions are run in the client rather than in the proxy)
However, this strictly improves the situation for current usage.
> Use file path comparison which normalises drive letters for code actions

- lapce-data/src/keypress/keypress.rs
- lapce-ui/src/app.rs
- lapce-ui/src/split.rs
There are still a few 'missing set_layout' warnings which I haven't tracked down, but this significantly improves visibility.
> Remove the sources of some warnings, and log to stderr

- .github/workflows/ci.yml
- .github/workflows/pr.yml
This patch adds GitHub Actions steps for caching. For example, rust-cache action sets `CARGO_INCREMENTAL: 0` to disable incremental compilation.
ref: Fast Rust Builds - https://matklad.github.io/2021/09/04/fast-rust-builds.html
> Speed up CI workflows

- Cargo.lock
- lapce-core/Cargo.toml
- lapce-core/src/language.rs
- lapce-ui/Cargo.toml
Partially fixes https://github.com/lapce/lapce/issues/272. 
I haven't tested any of these, and they really should be tested. We could @ some people in the discord server who have the OS testing roles but I doubt a lot of them read that the roles were for testing...
> Add various tree-sitter languages

- Cargo.lock
- lapce-data/src/editor.rs
- lapce-proxy/Cargo.toml
- lapce-proxy/src/buffer.rs
- lapce-proxy/src/lsp.rs
- lapce-proxy/src/plugin.rs
- lapce-rpc/src/plugin.rs
This is a new version of the Golang support PR, up to date and cleaner than the old #385, as discussed with @dzhou121.
Here is a paste of the previous PR message:
This PR pushes the LSP client to a state where the Golang LSP server (`gopls`) is usable.
While lapce might be missing plenty of capabilities (some of which might already be implemented and wirable), the goal of this PR is not to fill this gap but to make sure the base client is robust enough for any LSP server to run without any primary issues.
This PR should allow starting proper work on #365 and #374, and any other LSP server support.
*Note: A very basic and hacky gopls plugin can be found [here](https://github.com/nheuillet/lapce-go) for the time being.* 
closes #365 
-  [X] Implement response on …
> Golang Support

- defaults/keymaps-common.toml
Fixes #662 
(I'm assuming these keybinds are the same on MacOS?)
> Add shift-delete/shift-backspace to keymaps

- defaults/keymaps-macos.toml
- defaults/keymaps-nonmacos.toml
- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-data/src/palette.rs
- lapce-data/src/proxy.rs
- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/lsp.rs
- lapce-rpc/src/proxy.rs
- lapce-ui/src/palette.rs
This implements the ability to search for symbols in the entire workspace.  
Uses the `#` prefix and Ctrl+T keybinding, like VSCode.  
There's an LSP command for searching for a symbol in the workspace, though it behaves differently compared to document search since there can be a *lot* of symbols so it doesn't provide them all. It does some of the filtering for you. That required a bit of a different implementation of it in the palette, since it needs to resend the request whenever the input changes.
> Impl searching for symbols in workspace

- Cargo.lock
- lapce-core/Cargo.toml
- lapce-core/src/language.rs
- lapce-ui/Cargo.toml
- Enable CSS highlighting using fork https://github.com/syntacti/tree-sitter-css until upstream merge [this](https://github.com/tree-sitter/tree-sitter-css/pull/22) to enable highlights for Rust binding
- bump trees-sitter, it has a lot of improvements https://github.com/tree-sitter/tree-sitter/commits/master
- Fixed warning/error when compiling with clang -Os https://github.com/tree-sitter/tree-sitter/commit/150eb2966b68bce87e7125d9c2f630f6944277f9
- tags: fix incorrect uses of i8 instead of c_char https://github.com/tree-sitter/tree-sitter/commit/cdf2ecd176fe9ac8876092dfd385875d6e280139
- lib: fix incorrect int ptr cast on big-endian architectures https://github.com/tree-sitter/tree-sitter/commit/fe33599f4695c4ab442e1e5f8682cfda11321308
- Fix build and tests on alternative architectures …
> Enable css syntax highlighting, bump tree-sitter and tree-sitter-python

- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-data/src/proxy.rs
- lapce-proxy/src/dispatch.rs
- lapce-rpc/src/proxy.rs
Related to #682 but does not add the ability to apply it to files (such as in the context menu) but adds the code to handle multiple files at once for when that's added.
I am unsure as to if this is the most correct method for resetting uncommitted files back to what they were, but it appears to work in my tests.
> Impl discarding git changes per file/workspace

- Cargo.lock
- defaults/dark-theme.toml
- defaults/light-theme.toml
- defaults/settings.toml
- lapce-data/Cargo.toml
- lapce-data/src/command.rs
- lapce-data/src/config.rs
- lapce-data/src/document.rs
- lapce-data/src/editor.rs
- lapce-data/src/proxy.rs
- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/lsp.rs
- lapce-rpc/src/proxy.rs
- lapce-ui/src/editor.rs
- lapce-ui/src/editor/view.rs
- lapce-ui/src/tab.rs
This PR implements inlay hints.  
Question: Where is the best place to initialize inlay hints on open documents? Currently it waits until you press a key, but that's not the best time to do it. Adding the code for when an editor-view is opened could work, but would also want it to work on editor views that are open before the LSP begins initializing?  
Notes:  
- This does not implement a custom background color for inlay hints. The code provides an iterator so it would be relatively easy to implement later.
- Does not implement commands that are activated by clicking on the inlay hints; does not implement tooltips for inlay hints
- Adds `smallvec` as a direct dependency. This makes the code nicer and lets us avoid extra allocs in an area where speed is nice.
> Implement inlay hints

- Cargo.lock
- lapce-proxy/Cargo.toml
- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/lsp.rs
The current implementation of the LSP only sends `didSave` events when the file's language id matches the LSP's language id.  
For LSPs like Rust-Analyzer, they also handle that event for other documents. For RA, it wants to hear about `Cargo.toml` and `Cargo.lock` specifically; so that it can update based on the changed results. While it will get the changed values the next time the user saves a Rust file, this isn't as good as it could be.  
This just tells the LSP that we are willing to hear dynamic registration of what files it wants to hear updates about. The LSP protocol has these defined as globs, so I use the `globset` crate to match against those (which we already depended on through another dependency).  
Currently it keeps the code for sending the updates to the client if their …
> Handle LSP requests for hearing about file saving of specific files

- defaults/settings.toml
- lapce-data/src/config.rs
- lapce-ui/src/hover.rs
This adds a setting to change the hover's font family and/or font size.  
This still uses the editor font inside the code blocks.
> Add setting for hover font family/size

- lapce-data/src/data.rs
- lapce-data/src/proxy.rs
- lapce-ui/src/app.rs
fixes #734 
fixes #157 
I decided to not add any arg handling library as we are already
heavy on deps and I don't expect much cli options for now
TODO:
> feat: parse commandline args

- lapce-data/src/data.rs
it cannot be used to check for WSL session since it's set even for
non-WSL sessions
> fix: remove check for WSLENV envvar

- lapce-ui/src/plugin.rs
Try to fix #779 
Use `LapceScroll` to wrap the original `Plugin` component.
> fix plugin panel scroll bar

- lapce-proxy/src/buffer.rs
- lapce-proxy/src/lsp.rs
This makes  so we check the `server_capabilities` fields before actually sending anything. RA supports all of the requests we have implemented right now, but not all LSPs do, and some don't handle unknown requests gracefully (such as crashing). This also makes so they aren't sent until the LSP has told us it has initialized, which is what the LSP docs say we are supposed to do.  
Includes a fix for `window/workDoneProgress/create` which is supposed to send back nothing, not an empty object. (or at least the Julia LSP seems to want it to be empty?)  
Also adds Julia language id.
> Check lsp capabilities before sending commands

- lapce.spec
Addresses #121 (in relation to Fedora)
Adds a `.spec` file that can be used to compile the latest git version of Lapce for Fedora in copr. 
I need to do some testing and add possibly it to my [copr repository](https://copr.fedorainfracloud.org/coprs/titaniumtown/lapce) which I mentioned in #121
Corresponding package for master builds can be found here: <https://copr.fedorainfracloud.org/coprs/titaniumtown/lapce/package/lapce-git/>
> Add fedora spec for packaging

- lapce-ui/src/plugin.rs
This PR implements #808 . The added code calculates if the `text_layout` is larger than the current plugin panel width. If so, it will add ... to the truncation point using `hit_test_point`. The code is designed and tested against unicode characters to make sure it will not panic when dealing with unicode characters.
> add ellipsis to plugin description

- lapce-core/src/command.rs
- lapce-data/src/editor.rs
- lapce-data/src/proxy.rs
- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/lsp.rs
- lapce-rpc/src/proxy.rs
Closes #790   
This adds a command for going to the type definition variable if the LSP supports it.  
Ex:  
```rust
fn thing(text: String) {
let a = text|.trim();
}
```
where `|` is the cursor
The command will then go to the file where `String` is defined. This is faster, especially in cases where the variable is a field that you'd have to jump to to then jump to the actual type that it is.  
This does not set a keybind for it as VSCode does not set one. (Personally, I think this should have a keybind, but I don't know what would be a good default)
> Add LSP Goto Type Definition support

- lapce-core/src/style.rs
This checks if the line is at the `max_line` (1 past the end of the file) or greater, and if it is then it doesn't return any styles. Previously it would panic if the LSP gave a diagnostic at one past the end of the document (so the `line + 1` would then be 2 lines past the end of the document, which crashes).
> Check if line is at the max in line styles

- defaults/keymaps-macos.toml
- defaults/keymaps-nonmacos.toml
- lapce-core/src/command.rs
- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-ui/src/editor/tab.rs
- lapce-ui/src/editor/tab_header.rs
This adds commands for going to the next/previous editor tab using ctrl+tab.  
It would be good to have the more typical form of the feature where the editor keeps track of the previously focused tabs (on each split too?), but this is the simple form that is easier to implement.
> Add next/previous tab commands and keybindings

- lapce-proxy/src/lsp.rs
This is a basic patch which fixed utf16 offsets being wrong when interpreted as utf8, by just requesting utf8 from language servers that support this extension. (Ex: Rust Analyzer and Clangd)  
This of course does not fix the actual underlying issue, but this should serve to at least lessen the amount of problems from that until I implement the full fix.
> Request utf8 from LSP if possible

- lapce-proxy/src/lsp.rs
There is a crash where on a large project (like lapce, I typically did testing in the middle of lsp.rs) it would crash if you typed quickly (easy method: hold down enter). I believe this is a timing related crash.  
This sort of fixes the issue by just stopping the processing of the semantic tokens request if there is a newer revision of the buffer. This works because we just do a full semantic tokens request each time, and so if there's newer buffer (different rev) then we can just stop processing. This is probably a minor perf benefit in of itself.  
My theory as to what was happening:  
I noticed that it crashed when it processed (`request_semantic_tokens` finishing) a newer revision *before* an older revisions request. You'd be going through a bunch of revisions as you're typing …
> Fix crashing on semantic tokens going past last line

- lapce-data/src/command.rs
- lapce-data/src/editor.rs
- lapce-ui/src/tab.rs
Fixes where goto reference would show the palette when there was only a single entry to jump to. (it would jump and then show palette for a single entry)
Also fixes a bug where it would swap out the current editor for the destination file when there was a single entry. This just makes so it uses the same command that the palette would use.
> Fix goto ref on single references

- lapce-proxy/src/lsp.rs
This specifies a field to avoid a bug in lsp-types where it serializes the field even if it is `None`. RA has a less strict deserialization than the Julia LSP and so it was not noticed. I've opened a PR on lsp-types, so we should probably be able to remove the minor fix soon.
> Specify a field so that LSPs to avoid minor lsp-types bug

- lapce-proxy/src/lsp.rs
`root_uri` is deprecated, and so we should specify workspace folder as well (if we can). I don't think there's any LSPs that actually require it currently, but it might be useful in the future.
Note: I was a bit uncertain about the name of the workspace passed to the LSP. At a glance I didn't nice function on `Url` to get the basename, and I'm not sure it matters much beyond the case of if an LSP decides to use it in an error message?
> Specify the workspace folder of the root uri if available

- .github/workflows/release.yml
apt indexes should always be updated
before installing packages to prevent
situations where packages have been
removed from mirror
> ci: add index update before installing deps

- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-data/src/db.rs
- lapce-data/src/editor.rs
- lapce-data/src/palette.rs
- lapce-ui/src/problem.rs
- lapce-ui/src/search.rs
- lapce-ui/src/tab.rs
This switches much of the code over to using utf8 offsets rather than `lsp_types::Position` (line & column). This does not include the utf8 <-> utf16 changes, but will make them easier.   
There are a few places where I could changed `lsp_types::Position` (such as for the `next_error` code) but they're likely to be continuing to use the lsp `Position` for comparison purposes with stored `lsp_types::Position` and so it is better to leave them as they are.  
I introduced a `EditorLspLocation` and `JumpToLspLocation` which use `Position`. This will make so code that has `Position` types doesn't have to translate them itself, making it a bit easier to just use them. (and in some places, you might want to jump but you don't have access to data, and so this makes so you don't have to create a …
> Use utf8 offsets instead of lsp_types Position

- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-data/src/document.rs
- lapce-data/src/editor.rs
- lapce-data/src/palette.rs
- lapce-ui/src/problem.rs
- lapce-ui/src/tab.rs
In my PR to split the positions, I hadn't realized that the buffer wasn't loaded immediately. (That I was able to get the document made me think it was fine, oops)  
I incorrectly translated the lsp Position to an offset when we first get the buffer, which would just produce an offset of `0` for files that weren't already open. This broke goto definition / workspace references / etcetera.  
Fixing it proved a bit rough, since I realized I had to wait until the file was requested and gotten. I didn't want to duplicate the whole function `go_to_location`, and so I made `EditorLocation` generic over the type of position. This made so that rather than having `EditorLocation` and `EditorLspLocation` we had `EditorLocation<usize>` and `EditorLocation<Position>`. This helps avoiding duplication …
> Use generic parameter instead of separate structures

- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-data/src/plugin.rs
- lapce-data/src/proxy.rs
- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/lsp.rs
- lapce-proxy/src/plugin.rs
- lapce-rpc/src/core.rs
- lapce-rpc/src/plugin.rs
- lapce-rpc/src/proxy.rs
- lapce-ui/src/plugin.rs
- lapce-ui/src/tab.rs
This PR adds a basic functionality to make wasm plugins able to be enabled, disabled or removed. When disabling a plugin, if the wasm plugin provides a `stop` function, it will be called. Otherwise, the added code will try to find the LSP started by the plugin and stop it. The PR adds a context menu to the plugin panel to provide enable/disable and remove options. It also fixes the loading problem mentioned in #848 by adding a enum to keep track of the plugin loading status.
.
> Add functionalities to enable, disable and remove plugins

- lapce-data/src/data.rs
- lapce-ui/src/editor/tab.rs
- lapce-ui/src/editor/tab_header_content.rs
- lapce-ui/src/panel.rs
- lapce-ui/src/tab.rs
This is my idea of how to fix #886. The drag data keeps track of the start position, and we don't paint the editor tab unless it's 5px away from the initial mouse down event.  It would need to be updated to include other draggable items, mainly the file picker tab. Right now it does still paint the stationary tab highlight, which isn't as jarring as seeing the entire tab move a tiny bit when you just meant to click on it. It should be cleaned up a bit.
It now handles the file picker tabs, but the rectangle indicating the drag target still flashes sometimes on small drags.
> don't paint tiny tab drags

- Cargo.lock
- lapce-core/src/buffer.rs
- lapce-core/src/encoding.rs
- lapce-core/src/lib.rs
- lapce-data/src/data.rs
- lapce-data/src/document.rs
- lapce-data/src/editor.rs
- lapce-proxy/Cargo.toml
- lapce-proxy/src/buffer.rs
- lapce-proxy/src/lsp.rs
This PR adds an `encoding.rs` file for switching between UTF16 and UTF8 offsets given just an iterator over the char indices (which lets us work with both `&str` and a `Rope` without allocating).   
- Query: I put the `encoding.rs` in `lapce-core` so that it could be accessed by `lapce-core/src/buffer.rs` and `lapce-proxy/src/buffer.rs`, but that required making `lapce-proxy` depend on `lapce-core`. I could add a separate crate `lapce-encoding` (or `lapce-util` if we want it to be more general), so that we don't make it as tightly interlinked?  
This removes the `offset_encoding` field on the lsp capabilities, because supporting the UTF8 extension for LSP clients would be challenging. It is easier and less complex for the code to just use UTF16 offsets.  
This PR became much easier after …
> Use UTF16 encoding for LSPs

- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-data/src/editor.rs
- lapce-ui/src/search.rs
- lapce-ui/src/tab.rs
This fixes *another* issue I introduced in that move to offsets PR.  
Search would jump to a line column but it tried translating that before the buffer was guaranteed to be available, and so opening a search in a file that did not exist would just put you at the start.  
This fixes that, using the generics for `EditorPosition` (now I'm very glad I didn't duplicate the code, the generics make it easier).  
This also makes so the jump-to-line (or, rather, jump to first character on line) uses `EditorPosition` too. This doesn't help much at the moment, because Ctrl+G is always used on a file you already have open, but it will avoid that being a confusing bug later on if we allow syntax like Ctrl+P, `file.rs:42`.  
It also makes the `InitBufferContent` commands call a function, because they …
> Properly jump to line-col for search; Make line jumping not rely on the buffer being immediately open

- lapce-data/src/data.rs
- lapce-proxy/src/dispatch.rs
- lapce-ui/src/plugin.rs
- lapce-ui/src/tab.rs
Temporarily fix #900 by preventing the initial call to update the plugin list in the dispatcher when lapce starts. The editor will still freeze for a while when installing/removing plugins. When the proxy refactor is done I'll move the code from the UI thread to the proxy to prevent blocking the UI thread.
Edit: the previous patch will cause the plugin panel to be blank when opening a new folder. Instead, I introduce a small delay in the dispatcher to allow the plugin loading thread in lapce-data to load the plugin in the background first so the editor will still be responsive when starts for the first time. The editor will still freeze when opening new folders, and installing and removing plugins.
> temporary patch for slow start

- lapce-proxy/src/plugin.rs
The channel receiving code for the plugins (introduced to allow enabling/disabling them) was using `try_recv` (which would unnecessarily execute nothing when there was no messages, and it is on a separate thread so `recv` is the better choice since we just want to wait for a message). As well, it would ignore the error of the channel closing on the other end, which would cause it to do nothing forever in an infinite loop. This would cause 100% CPU usage for that thread.
> Use recv when receiving messages and stop checking when the channel closes

- Cargo.lock
- lapce-data/Cargo.toml
- lapce-data/src/config.rs
- lapce-data/src/data.rs
- lapce-data/src/keypress/loader.rs
- lapce-data/src/keypress/mod.rs
- lapce-proxy/Cargo.toml
- lapce-proxy/src/plugin.rs
- lapce-ui/Cargo.toml
- lapce-ui/src/tab.rs
toml-rs is abandoned and not fixed anymore, it also has a bug
that in certain cases might prevent plugins getting installed
because of struct serialization, where `Value` is seralized
in alphabetical order and certain keys end after table which
is incorrect in Toml
this is also the reason why `cargo` switched to `toml_edit`
and I think it would be good to follow same dependencies as
cargo
> fix: replace toml-rs with toml_edit

- defaults/keymaps-common.toml
- defaults/keymaps-macos.toml
- defaults/keymaps-nonmacos.toml
- lapce-data/src/keypress/keypress.rs
- lapce-data/src/keypress/mod.rs
On Mac when a character is pressed along with shift and
command, the character returned is not the upper case
variant.  This code allows recognition of "Redo", command-
shift-z, to work.
> Fix hotkey for redo

- lapce-data/src/editor.rs
Fixes #742
Check for whitespace command in `run_edit_command` and `receive_char` before triggering autocomplete.
> Don't show autocomplete after whitespace keys

- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-data/src/document.rs
- lapce-data/src/editor.rs
- lapce-ui/src/editor/view.rs
- lapce-ui/src/tab.rs
This makes so when applying edits via code actions it will open files that it references.  
Previously, we would just ignore edits that reference other files, which was incorrect.  
One example where this occurs is:
- Create a new file in a rust project
- `Ctrl+.` inside that new file gives code actions to add `mod filename;` to the `lib.rs`/`main.rs` file so that it is recognized as part of the rust project.  
- Previously this would simply do nothing. With the PR, it will open the file if it isn't already open (because we need the file to apply the edit!) and apply the edit, letting the user save with the edits if they wish.  
The first commit switches to using a structure for `InitBufferContent`, since they were sharing literally all fields (and I was going to be adding yet another). …
> Open editors when applying text edits via code actions

- defaults/keymaps-common.toml
- lapce-core/src/command.rs
- lapce-data/src/completion.rs
- lapce-data/src/editor.rs
- lapce-data/src/palette.rs
- lapce-ui/src/completion.rs
- lapce-ui/src/palette.rs
Fixes #924.  
This makes so using page-up/page-down work in completion and in the palette.
> Make completion and palette pay attention to page-up/down

- lapce-data/src/editor.rs
This prevents the crash described in #929, but I'm not certain it makes sense for the save command to be sent to anything but the front window. I'm also unsure how the path from the front window ends up getting sent to the empty, rear window.
I'm opening this PR for some guidance on what the right fix is in this case.
> Prevent crash on save

- lapce-data/src/editor.rs
Fixes #743 
Added `EditCommand::DeleteBackward` and `EditCommand::DeleteForward` to the match statement that checks for whitespace commands. On receiving one of these commands the deleted string gets checked if it's all whitespace.
Added `EditCommand::Undo` and `EditCommand::Redo` to the check, because i think it's not necessary to show autocompletion after an undo or redo.
Maybe it would make sense to extract this into a function?
> Don't show autocomplete after backspacing over whitespace

- lapce-data/src/editor.rs
This makes the code more paranoid about whether the entries in the deltas exist. There was a crash when you began editing on an empty file, and so it would use an out of bounds index.
> Fix crash on completion

- lapce-data/src/split.rs
- lapce-ui/src/explorer.rs
- lapce-ui/src/keymap.rs
- lapce-ui/src/panel.rs
- lapce-ui/src/plugin.rs
- lapce-ui/src/problem.rs
- lapce-ui/src/search.rs
- lapce-ui/src/settings.rs
- lapce-ui/src/source_control.rs
- lapce-ui/src/split.rs
- lapce-ui/src/terminal.rs
This PR adds the ability to resize the editor, fixing #741. As well, since it is a general addition of being able to resize `LapceSplit`, this extends to being able to resize the terminal and various other places (like the plugin installed/uninstalled split).  
- You can resize the editor, and it avoids letting you go off the edge, so the editor should always stay visible.  
- You can shift nearby editors by dragging your editor (like, with three editors, dragging the last one to the left will cause the second editor to move once you reach it)    
- Adds the ability to specify if the thing should be able to be resized. Some parts of the display simply shouldn't be resized, as we're only really using the split to segment the area for things like the keymap.  
Though, there are some bugs …
> Add the ability to resize splits

- lapce-data/src/update.rs
- lapce-ui/src/app.rs
- lapce-ui/src/window.rs
`target_family = "unix"` includes all Unix-like systems, like *BSD, etc.
> fix: add *bsd targets

- Cargo.lock
- lapce-data/src/command.rs
- lapce-ui/Cargo.toml
- lapce-ui/src/tab.rs
This is base for multiple other commands we can have in future like `Open Setting location`, `Reveal this file/folder in File Explorer` etc. and URLs in terminal/editor/UI
This was originally part of icon theme PR but I'm trying to decouple it into more smaller PRs so they can get merged already
> feat: add LapceUICommand::OpenURI

- .github/workflows/release.yml
ubuntu-18.04 is being deprecated and will soon be unavailable
https://github.com/actions/runner-images/issues/6002
Test run: https://github.com/panekj/lapce/runs/7954568797?check_suite_focus=true
> ci: switch to ubuntu-latest

- .github/workflows/ci.yml
rustfmt formats code no matter if it's behind specific #[cfg] attributes, so it can run on linux only
> ci: rustfmt doesn't need to run on all platforms

- defaults/settings.toml
- lapce-data/src/config.rs
- lapce-ui/src/app.rs
- lapce-ui/src/tab.rs
- lapce-ui/src/title.rs
- lapce-ui/src/window.rs
- moved `custom-titlebar` into `lapce` otherwise theme plugins will modify that setting
- adjusted other icons sizes in titlebar to match with minimise/maximise/close
- added hover effect for window controls, with close button having distinct red background color
- replaced font based icons on Windows with SVGs
- activate buttons on left click **only**
fixes #997
> fix: rework titlebar

- lapce-ui/src/title.rs
> fix: align settings button size to window controls

- lapce-ui/src/split.rs
Current implementation doesn't work, presumably because paint is not requested and it gets reset to default cursor in drag logic later.
> fix: hover on empty split links

- lapce-data/src/config.rs
My first pull request!
Currently, there is an issue #918 where if you leave the font family field in the Editor Settings empty, Lapce keeps trying to open an empty font which doesn't exist, causing the editor to become unusable. The problem was that this font_family function didn't have a guard for the field being empty like the font_family function in the UI settings.
> Add emptiness check for editor font family field

- lapce-core/src/language.rs
.cjs and .mjs extensions are not recognized as JS/TS files.
More info: https://www.typescriptlang.org/docs/handbook/esm-node.html#new-file-extensions
> Add JS/TS ESM and CJS extensions

- lapce-data/src/data.rs
The usual papercut perf thingy :)
> Don't clone paths when collecting diag items

- lapce-data/src/config.rs
The strings are immediately converted into an `Arc<str>` so this should save an allocation on each call.
> Don't clone strings when looking up font family

- lapce-ui/src/settings.rs
There's no reason to copy a bunch of static data into vectors. This PR cleans up these clones and deduplicates converting structured data into hashmap form.
> Clean up settings update

- lapce-data/src/config.rs
Uppercase the abbreviation. Consistent with naming throughout the rest of the config.
> Uppercase "UI" in config descriptions

- lapce-proxy/src/terminal.rs
Users may have manually removed the org.freedestkop.Flatpak session
bus talk name from permissions, in which case flatpak-spawn --host
won't work.
Closes https://github.com/lapce/lapce/issues/1133
---
This is not the cleanest solution to this problem, but without pulling in something like zbus I think this is the best we can do.
> Check if flaptak-spawn --host works before attempting to use it

- lapce-proxy/src/plugin/mod.rs
Fixes plugin installation when `wasm` specifies any kind of directory tree
> fix: create directory tree before plugin download

- Cargo.lock
- lapce-core/Cargo.toml
Replacing crate with git repo because maintainers have no permission to publish new crate versions
> dep: replace tree-sitter-json crate with git repo

- lapce-proxy/src/terminal.rs
Supersedes #1157 and #1151
This PR
- cleans up a block comment (a bit of style consistency)
- only executes the flatpak command if the info file exists
- does not crash on error
> lapce-proxy: fix flatpak host detection

- lapce-ui/src/app.rs
- lapce-ui/src/tab.rs
- lapce-ui/src/window.rs
- Prevent window tabs "sticking" when released
- Fix undraggable area right of tabs
- Turn magic numbers into constants
- Prevent dragged tab overdrawing others
- Swap tabs if dragged tab's center gets inside another tab (instead of mouse). This might be a controversial change.
Window tab code is a bit confusing as it's not obvious at all, what handles tab drags, for example. There are a number of small bugs around this area, this PR (when finished) attempts fixing those I found.
> Window Tab improvements

- defaults/dark-theme.toml
Before:
After:
I didn't touch the light theme as I think it's less obnoxious there. Disclaimer: I'm not a designer, so let's put this up to a vote.
> Tone down inlay hint background color in lapce dark theme

- lapce-ui/src/editor/tab.rs
Currently, neither `LapceTheme::LAPCE_ACTIVE_TAB` nor `LapceTheme::LAPCE_INACTIVE_TAB` are utilized in the [Lapce codebase](https://github.com/lapce/lapce/search?q=LAPCE_ACTIVE_TAB).
Though it would probably be more feasible to give theme color keys a well-thought rework, this quick patch would at least allow the two unused theme colors to be recognized by Lapce.
> fix: Utilize active/inactive tab colors from theme

- lapce-ui/src/editor/tab.rs
This PR simulates clicking the close button on all the tabs, so the modified ones will ask for confirmation.
> Fix closing modified file when closing split

- lapce-core/src/editor.rs
The `Append` command will no longer move down to the next line when it is used on an empty line.
> Fixed a bug with the 'Append' command (Fixes #1193)

- lapce-core/src/editor.rs
This PR fixes #1226 and includes a drive-by cleanup of `insert_new_line`
> Don't restore cursor mode on undo

- lapce-data/src/config.rs
- lapce-data/src/data.rs
- lapce-data/src/document.rs
- lapce-data/src/editor.rs
- lapce-data/src/settings.rs
- lapce-ui/src/completion.rs
- lapce-ui/src/editor.rs
- lapce-ui/src/editor/bread_crumb.rs
- lapce-ui/src/editor/gutter.rs
- lapce-ui/src/editor/view.rs
- lapce-ui/src/hover.rs
- lapce-ui/src/picker.rs
- lapce-ui/src/problem.rs
- lapce-ui/src/settings.rs
Closes #1230
1.35 might be too tight, so we might want to either make it configurable directly, or provide a few presets. I think this is VSCode's default and I personally find this a good, comfortable spacing.
This PR also removes the assumption that problem panel lines are 25px high.
> Automatic line height

- Cargo.toml
**Removed**:
- `resolver = "2"` is unnecessary due to in the 2021 edition `resolver` are by default is `2`. 
**Added**:
- Set default crate to run by `cargo run/r` command.
> Minor changes of root `Cargo.toml`.

- lapce-data/src/proxy.rs
Fixes issue when `{user}@{host}:{port}` results in too long socket path (max: ~100 characters)
`%C` is a SHA1 hash of `%l%h%p%r`
too long socket paths can happen if someone uses for example gitpod.io, e.g.:
`/Users/pj/.ssh/cm-lapce-lapce-dvqmoe3x0a0@lapce-lapce-dvqmoe3x0a0.ssh.ws-eu64.gitpod.io:22.F2aSCVIZ0IHmNSrh`
using `%C`
`/Users/pj/.ssh/cm_067698ecd110d603843a371f498e878e5d18fbaa=`
> fix: too long socket

- lapce-ui/src/editor/tab.rs
Fix crash when closing editor when no tabs have unsaved changes
changes
```rs
let active = &tab.children[tab.active];
```
to 
```rs
if let Some(active) = tab.children.get(tab.active) {
```
> Check whether index exists when using EnsureEditorTabActiveVisible

- lapce-data/src/command.rs
- lapce-data/src/completion.rs
- lapce-data/src/data.rs
- lapce-data/src/editor.rs
- lapce-data/src/lib.rs
- lapce-data/src/list.rs
- lapce-data/src/palette.rs
- lapce-ui/src/completion.rs
- lapce-ui/src/lib.rs
- lapce-ui/src/list.rs
- lapce-ui/src/palette.rs
- lapce-ui/src/tab.rs
This PR adds a `List` widget, which can be used for displaying lists like the palette or the completion. It changes the current implementations to use the `List` widget.  
The general idea is that the `List` widget has some `items` that it renders. This is an `im::Vector` to make it cheap to clone, or replace (such as filtering it from the containing widget). It is given the focus commands (for list movement) by the containing widget. If it receives `ListSelect`, then it sends an event to the containing widget that an item was selected (and it sends that event if an entry was clicked), letting them handle it (and also decide whether to close the list at all).  
With this, it will be easier to make simple lists. I plan on using it to implement a dropdown button element that we can use for …
> Unify Palette/Completion with List widget

- defaults/settings.toml
- lapce-data/src/config.rs
- lapce-data/src/document.rs
Possible implementation for #277.
I have added the option to for case sensitivity and "whole words only" for select_next_current.
To be persistent the options also affect select_all_current.
While working on it I found 2 bugs regarding select_all_current.
The first one occured because the wrong selection was used for `cursor.set_insert()`, I fixed this.
For the other one I created a new issue #1237
> feat: improved multicursor selection

- lapce-ui/src/editor/tab.rs
- lapce-ui/src/tab.rs
View tab dragging currently does nothing.
It originally broke 61f91c7635d3be37df03f110926fd322fe7a3adb
It currently does not work due to the  mouseUp event happening before 
```rs
self.main_split.event(ctx, event, data, env);
```
If anyone knows, I would love to understand why the event callback has to occur after that line
> fix view tab drag-drop

- lapce-proxy/src/plugin/catalog.rs
On handle_server_request no method was called to communicate with the server, so there is no callback executed, if there are no plugins installed.
The calls are always (as I can see) based on plugins.
So if there are no plugins, just execute the callback directly, without making a request to the server.
Fixes #1128
> Fix save-delay: Call callback of handle_server_request even though no plugins exist

- lapce-ui/src/split.rs
Should give an idea to users that those can be clicked
> fix: use link colour for empty editor buttons

- Cargo.lock
- lapce-data/Cargo.toml
- lapce-proxy/Cargo.toml
- lapce-proxy/src/plugin/lsp.rs
- lapce-proxy/src/plugin/mod.rs
- lapce-proxy/src/plugin/psp.rs
- lapce-proxy/src/plugin/wasi.rs
- lapce-ui/Cargo.toml
The current implementation of the JSONRpc communication between Lapce and plugins or language servers assumes that all ids are integers, or strings that can be parsed as integers. However, the specification does not require that the strings be in any specific format.  
This was encountered because the Julia language server sends strings containing GUIDs, which are not representable as integers.  
~~I had to make a separate `HashId` structure, rather than using the `jsonrpc_lite::Id` structure because the latter does not derive `Hash` - which is needed for the `HashMap`.~~ I opened an issue on the `jsonrpc_lite` for deriving Hash, and they added it very quickly. So, the version for jsonrpc_lite is bumped up in all the places that use it.
> Make PSP/LSP api use number and string identifiers

- rust-toolchain.toml
Without this change, some OS'es such as ArchLinux
will fail to build this project by default.
You would first need to run a specific rustup command to set your default toolchain,
that you as a Rust developer should know,
and only then the project would build using your
downloaded default toolchain.
Specifying the channel explicitly as done in this commit allows for Lapce to be build-able on a completely fresh (or isolated for security reasons) home directory, for those Operating Systems.
> Add rust-toolchain file

- lapce-core/src/buffer/mod.rs
- lapce-core/src/editor.rs
- lapce-core/src/word.rs
Closes #778. The solution provided in #863 PR doesn't work correctly, because the logic for backward word movement is a bit different from backward word deletion.
For instance, in this case (`|` matches cursor position):
```rust
fn main() {}
|
```
Pressing `Ctrl` + `←` should place the cursor in the position:
```rust
fn main() |{}
```
But, the `Ctrl` + `Backspace` should transform code like this:
```rust
fn main() {}|
```
The function `prev_boundary` is working correctly, so its logic cannot be changed. Instead, I've created the function `prev_deletion_boundary`, which calculates the correct position for the cursor.
The new backward word deletion logic (`|` - cursor position, `◦` - space symbol):
<table><tr>
<th>Code</th>
<th>After transformation</th>
<th>Description</th>
</tr>
<tr>
<td> …
> fix: backward word deletion respect whitespaces

- Cargo.lock
- lapce-core/Cargo.toml
The required changes have been merged upstream: https://github.com/vantreeseba/tree-sitter-haxe/pull/7. The fork is now out of date with other improvements so this PR updates the link to point to the upstream repo.
> Use upstream repo for tree-sitter-haxe

- lapce-data/src/proxy.rs
when file paths include symbols such as `@` they are not being correctly converted from urls to paths.
Currently:
`node_modules/%40types/...` is parsed as `node_modules/%40types/...`
instead of `node_modules/@types/...`
I added a unwrap_or in the case that it fails, we default to the previous implementation. This may be slightly overkill but I do know everywhere where path_from_url is being used
> fix incorrect path when going from url -> pathbuf

- defaults/settings.toml
- lapce-data/src/config.rs
- lapce-data/src/document.rs
- lapce-data/src/history.rs
- lapce-ui/src/editor.rs
Adding simple logic for whitespace rendering. Rendering logic is similar to VSCode.
Notably this doesn't take selected text into account. So this doesn't implement the `selection` whitespace rendering option.
Feature request: https://github.com/lapce/lapce/issues/249
> Render whitespace

- lapce-data/src/editor.rs
- lapce-proxy/src/dispatch.rs
This PR makes the suggestions I mentioned in #1233 functional. For `<modname>/mod.rs`, the directory also needs to be created, so I changed the CreateFile implementation to call `std::fs::create_dir_all` on the directory first. I also changed the CreateDirectory implementation, even if unused by LSP, for consistency.
> feat: handle LSP ResourceOp

- defaults/keymaps-common.toml
- lapce-core/src/command.rs
- lapce-core/src/editor.rs
`P` behaves like `p` but instead of inserting after the cursor `P` inserts before the cursor. `P` moves the cursor one to the left before pasting. This move does not occur if the cursor is at the beginning of the line and therefore behaves like vims `P`.
> Added vims paste before 'P'

- lapce-core/src/editor.rs
Fixed a bug where the paste before command pasted after the selection, instead of before, when the line contains only one character. The bug is also mentioned in the original pull request of the paste before command #1251
The command no longer moves the cursor to the left and then pastes, but instead pastes using a Cursor::Insert. This results in (hopefully) all the desired behavior, and I am not aware of any problems with using this approach. But feel free to correct me.
> Fixed a bug in vims paste before command

- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-data/src/lib.rs
- lapce-data/src/source_control.rs
- lapce-data/src/title.rs
- lapce-ui/src/completion.rs
- lapce-ui/src/list.rs
- lapce-ui/src/palette.rs
- lapce-ui/src/tab.rs
- lapce-ui/src/title.rs
This replaces the source control branch selector with a `List` widget, which allows: limiting the space it takes, adding more information (such as deviation from HEAD) in the future, and being more consistent.  
There could probably be some improvements in the appearance. It has no visual icons of extra information like the palette/completion, and so can appear a bit bland.
> Replace Branch-Selector dropdown with a List

- defaults/keymaps-common.toml
- lapce-core/src/command.rs
- lapce-core/src/editor.rs
Closes #1060
I miss my old idea of placing markers in test strings to also test cursor positions... oh well, trust me, they are mostly correct.
PR contains a drive-by cleanup
> Add duplicate_line_up/down commands

- lapce-rpc/src/proxy.rs
#1336 removed the block around variable for the `if let`.  
However, `if let Some(handler) = self.pending.lock().remove(&id)` would drop the lock at the end of the statement, which is after the if statement has ran.    
(The easiest way to trigger the hand for me was to remove or create a file in the file listing)
> Fix proxy hang due to held lock

- lapce-core/src/syntax/edit.rs
This fixes a crash when using workspace edit code actions which would extend past the end of the file. (There was also probably some weirdness there for unicode characters due to the bug)  
The issue was that the alternative translation from deltas to treesitter edits wasn't taking into account that the parts assumed the previous entries were applied. This would work roughly fine when in the middle of a file and using them, but would cause issues if they would try indexing past the end.  
This isn't as efficient for it as I would like, but it works. I think it would be possible to rework the edits to not have to create a new `Rope` each time, though I'd prefer to put that off for another time and just fix this crash.
> Fix edit crash

- lapce-ui/src/keymap.rs
Characters now get unshifted when creating keyboard shortcuts from the UI. Fixes #1312
> Cases get handled correctly when generating keyboard shortcuts from UI

- lapce-ui/src/editor.rs
- lapce-ui/src/editor/gutter.rs
cc #1296 - while this PR doesn't render caret, at least the first line is no longer always overdrawn. Also fixes a weirdness with the shadow.
This PR also optimizes background clearing when multiple sticky lines are visible. Nothing major, but still.
In general, I'm not pleased with how this PR looks but my brain doesn't work this late. Suggestions are welcome.
Before:
1px of overlap above shadow (on a high-DPI display, Surface Laptop Studio):
First line is always hidden below a sticky header:
After:
First line is no longer sticky except if scrolled:
Overlap is gone:
> Sticky header fixes

- lapce-data/src/editor.rs
This PR fix an issue where cursor position was not correctly positioned after applying postfix completion. 
```rust
fn main() {"a".let}
//-------------- ^
"." at offset 15 trigger a `let` postfix  
```
Lsp server send a `CompletionItem` containing the following
- `text edit` 
- starting offset: `15` 
- end offset: `18`
- snippet: `let $0 = "a";` (to replace the postfix identifier `.let`)
- `additional_text_edits`
- starting offset: `11` 
- end offset: `15`
- snippet: `""` (to replace the postfixed expression `"a"`)
Previously the additional edit was not taken into account when updating the tabstop selection start offset. This ended in tabstop offset being apply to the main textEdit, instead of the additional one. Resulting in a wrong cursor position, potentially out of bound if we are …
> fix: fix tabstop for postfix completions

- defaults/keymaps-common.toml
- lapce-core/src/command.rs
- lapce-core/src/cursor.rs
- lapce-data/src/command.rs
- lapce-data/src/document.rs
- lapce-data/src/editor.rs
- lapce-data/src/lib.rs
- lapce-data/src/selection_range.rs
- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/plugin/mod.rs
- lapce-proxy/src/plugin/psp.rs
- lapce-rpc/src/proxy.rs
- lapce-ui/src/editor.rs
This PR add syntax aware selection (see: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_selectionRange)  
**Example:**
Note: I had to implement a `get_selection` function on `Cursor` which might seems strange but was needed to compare the current selection state with the active `textDocument/selectionRange` and reset the document state whenever the selection change. 
Also the current implementation support only single cursor selection but I think multiple cursor selection range might work with the lsp api. This could be implemented in a future PR. 
Let me know if anything needs to be changed.
> feat(lsp): implement syntax aware selection

- defaults/settings.toml
- lapce-data/src/config.rs
- lapce-ui/src/editor/view.rs
This add an `autosave-interval` key to editor config, allowing to set up autosave. 
The config setting default to zero, which disable auto-saving. 
Closes #248
> feat(editor): add autosave configuration

- lapce-core/src/syntax/edit.rs
When a suggestion by the auto-completion is accepted, lapce crashes. Let's imagine a scenario that we type in 3 letters ("com" of "compile") and accept a suggestion with the following delta, which is neither a simple insert nor a simple delete.
Copy(0, 1230), # Insertion position is 1230
Insert("compile_only(exercise)"), # Accepted suggestion of length 22
Copy(1233, 6140). # The 3-letter hint for the auto-completion
When we factor this delta into insertions and deletions we get the following insert-only delta
Copy(0, 1230),
Insert("compile_only(exercise)"),
Copy(1230, 6140),
and segments representing the deletions
{len: 1230, count: 0},
{len: 3, count: 1},
{len: 4907, count: 0}.
In this scenario `shift` is 22 and `CountMatcher::Zero` matches the zero counts of deletion segments yielding …
> Fix auto-completion crash

- lapce-core/src/language.rs
> Add rust enums to sticky headers list

- lapce-data/src/terminal.rs
- lapce-ui/src/terminal.rs
Escape search string to create safe regex search within the terminal. Otherwise regex meta characters within the search string could freeze the whole editor.
Closes #1183
> Fix regex search within the terminal

- .github/workflows/ci.yml
Add code coverage to CI builds, this probably needs a maintainer to create a codecov account with lapce org  and authorize the github app.
> test: add code coverage CI action

- lapce-core/src/syntax/edit.rs
Iterator with matcher `CounterMatcher::NonZero` yields correct intervals for deletion edits. Remove faulty interval calculations for deletions.
Closes #1379
> Fix deletion edit intervals

- lapce-data/src/hover.rs
- lapce-proxy/src/plugin/mod.rs
- lapce-ui/src/hover.rs
Changes:
- fixes hover hints (currently broken on master
- adds support for multiple hover items
- adds padding at top of hover box
- filters out empty hints
Before:
After:
(the syntax highlighting being broken isn't related to this PR)
> Fix hover hints + show multiple hover hint items

- lapce-data/src/plugin.rs
This fixes installing themes on master.  
It would error due to passing `true` instead of `false`, like it had been in the past.
> Indicate to download_volt that plugins without wasm files should not have wasm files

- lapce-data/src/update.rs
- lapce-ui/src/app.rs
cc #1351
I think this will only fix portable Lapce because the install directory might be read-only, but we'll see.
This PR fixes the issue that an exe can't delete itself, which makes self-update on Windows fail on the extract step.
> Try to fix windows self-update

- defaults/keymaps-common.toml
- defaults/keymaps-nonmacos.toml
These are probably less known, but AFAIK they work in Gtk apps, VS, VS Code and even older IDEs like Delphi and Turbo/Borland Pascal. Probably inherited from WordStar.
I _think_ I've seen `Shift-Del` working like Backspace once, but never as Del.
CC @MinusGix from https://github.com/lapce/lapce/issues/662
> Add keybindings for `Shift-Del`, `Shift-Ins`, `Ctrl-Ins`

- Cargo.lock
- lapce-ui/Cargo.toml
- lapce-ui/src/app.rs
This PR captures and logs panics as errors. No backtrace is captured right now but it can be enabled using the `with-backtrace` feature flag and some configuring on the log-panic side.
> Log panics with full backtrace as errors

- lapce-core/src/editor.rs
- lapce-core/src/syntax/util.rs
Code was editing the region before comparing it to the previously inserted region.
Also add doc to matching_pair_direction function.
This closes #1374
> Fix multiple cursor offset after inserting opening pair

- lapce-data/src/data.rs
This fixes a bug where Ctrl+N to create a new scratch file would replace the current open editortab, uncaring of whether there was edits or not.
> Check if get_editor request is non-scratch before early-returning

- lapce-data/src/document.rs
- lapce-ui/src/editor/view.rs
semantic token highlighting from the lsp does not return all the highlights, instead we can combine it with the highlighting from tree sitter for a more complete experience
Before:
After:
> Merge semantic and syntax highlighting

- lapce-data/src/data.rs
- lapce-proxy/src/lib.rs
technically previous version works, but there is some weird behaviour with double quotes (at least on Windows)
```rs
} else if v.contains(&sep) {
joined.push(b'"' as u16);
joined.extend_from_slice(&v[..]);
joined.push(b'"' as u16);
```
https://github.com/rust-lang/rust/blob/33d351972ad9c43bc30e87edd2765de9a4898629/library/std/src/sys/windows/os.rs#L212
> fix: correct joining PATH

- lapce-data/src/config.rs
- lapce-data/src/editor.rs
- lapce-ui/src/terminal.rs
Fixes #1002.
I was having this issue last night:
With my current changes:
> Correct terminal font sizing

- lapce-core/src/language.rs
Add Hashicorp Terraform to Hashicorp language syntax
> fix: add terraform extension to HCL syntax

- lapce-ui/src/editor/view.rs
To reproduce the bug: 
- set an autosave interval in lapce settings
- search text with ctrl+f
- try to scroll with mouse wheel
> fix(view): autosave periodically resetting scroll

- defaults/settings.toml
- lapce-data/src/config.rs
- lapce-ui/src/search.rs
> Trim whitespace from search results

- defaults/settings.toml
- lapce-data/src/atomic_soft_tabs.rs
- lapce-data/src/config.rs
- lapce-data/src/document.rs
- lapce-data/src/lib.rs
This adds an editor setting to treat soft tabs (i.e. spaces pretending to be tabs) as if they were real tabs, for the purposes of mouse selection and left/right movement.
This feature is known as "sticky tabs" in VSCode and "atomic tabstops" in Atom.
Fixes #1402
I have tested this manually but not added any unit tests (thought I would get some feedback first before putting in a ton of effort).
Also it uses the tab width setting but this is not synchronised with the indent style, so it may need to be changed a bit when #782 is fixed.
> Add atomic soft tabs feature

- lapce-ui/src/app.rs
When lapce attempts to launch sub-processes (i.e. a LSP) that depend on environment variables like a customized `PATH` it will fail as long as it has been launched from the GUI (at least on macOS). 
This is due to the fact that i.e. macOS does not load the user's shell environment when launching an app. This can be mitigated by starting a login shell and extracting all environment variables from it. A strategy described in [this comment](https://github.com/atom/atom/issues/18318#issuecomment-439175987) on the Atom Editor project.
I have tested this on macOS, and it resolved all issues of lapce not being able to find LSP executables like `pylsp`. For Linux, I do not know if it is actually necessary or if the correct environment is available to lapce there.
> Load shell environment when launching from GUI

- lapce-data/src/document.rs
- lapce-ui/src/editor/view.rs
- lapce-ui/src/settings.rs
- lapce-ui/src/tab.rs
This PR splits up the `LapceSettingsItem` code into two separate structures for the String/Number input and the Checkbox. This makes it easier to add future item-kinds, and makes the code more manageable.  
There's now two structures, `InputSettingsItem` and `CheckBoxSettingsItem`. They have a common `SettingsItemInfo` structure which keeps track (and does the drawing) of the setting name/description.
- The first commit removes some code that was completely unused. The fields that it modified weren't paid attention to.
- Moves the code for special handling last-idle-timer with `BufferContent::SettingsValue` from `view.rs` into `settings.rs`
- This simplifies `BufferContent::SettingsValue` due to not …
> Split up SettingItem code

- CHANGELOG.md
- extra/proxy.sh
parallel isn't required and might be missing on some hosts fixes #1504
> fix: remove -Z

- CHANGELOG.md
- defaults/settings.toml
- lapce-data/src/config.rs
- lapce-ui/src/editor/view.rs
This is the minimum number of visible lines above and below the cursor. The default is 1 as per the editors current behavior.
- [ x] Added an entry to `CHANGELOG.md` if this change could be valuable to users
> Feat: Add setting Cursor Surrounding Lines (#1474)

- CHANGELOG.md
- defaults/keymaps-common.toml
- lapce-data/src/editor.rs
> fix(search): use esc to close search regardless of current mode

- defaults/keymaps-common.toml
- lapce-core/src/command.rs
- lapce-core/src/editor.rs
> feature: add vim shift+c to delete remainder of line

- CHANGELOG.md
- lapce-core/src/word.rs
As mentioned in the issue #1529, the Ctrl+Arrow keys behave slightly incorrectly, especially with regard to indentation where Ctrl+Left moves the cursor to the top line when it should move the cursor to the beginning of the line and the next time it should move to the top line
I don't know now but it looks like CHANGEMOD.md has been automated so I don't know if I should add an entry.
> Improve Ctrl+Left-Arrow Keys behavior

- lapce-ui/src/settings.rs
This fixes a bug in my PR for handling settings which we don't currently have widgets for, but are still wanting to be rendered in the settings menu as options. (This occurred in plugins)  
This is just how it behaved before, displaying the name and description of the setting but without a way to edit it (without going into the setting.toml file).
> Add support for empty setting items

- lapce-core/src/editor.rs
when text is selected, and [, (, {, ", ' is typed, it wrapped the selected text with that character pair
https://user-images.githubusercontent.com/18101008/194603893-00ddcfd6-1c7f-4d7b-9c85-4cc0e15f1c8e.mov
> Wrap selected text with brackets/quotes

- lapce-ui/src/editor/tab_header_content.rs
When running the editor in debug mode like `cargo run`, the editor will become sluggish and this crash will happen. A lot.
Visually, it looks like some details are not loaded at the same time (like file paths).
> Fix overflow crash when editor is sluggish

- CHANGELOG.md
- lapce-ui/src/editor/tab_header_content.rs
A basic editor tab context menu with common tab close operations. For issue #736.
Implemented actions:
- Close tab
- Close other tabs
- Close tabs to the left
- Close tabs to the right
> Basic Tab Context Menu for #736

- lapce-data/src/editor.rs
- lapce-proxy/src/plugin/lsp.rs
Lapce-vue use the [volar](https://github.com/johnsoncodehk/volar) lsp server, volar response the goto definition request via [locationLink](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#locationLink), But This not
be implemented by Lapce，This causes vue can't go to definition (xiaoxin-sky/lapce-vue/issues/5). So add code to support 
handle locationLink response.
**preview**
> feat: add goto definition and typeDefinition via link support

- lapce-ui/src/palette.rs
> fix: use proper colour for symbols

- lapce-core/src/language.rs
> Detect the .Containerfile file extension as a Dockerfile

- CHANGELOG.md
- Cargo.lock
- lapce-core/Cargo.toml
- lapce-core/queries/erlang/highlights.scm
- lapce-core/src/language.rs
- lapce-core/src/syntax/highlight.rs
- lapce-ui/Cargo.toml
> Add syntax highlighting for erlang.

- lapce-ui/src/editor/view.rs
I don't think this should take into account the width of the inline diagnosis when focusing the cursor, otherwise it will cause  #1611 issue，So I delete the diagnosis col.
> fix(editor): diagnosis cause cursor x calculate error

- CHANGELOG.md
- lapce-data/src/palette.rs
As reported in #1606, for large numbers of PaletteItems (5k+) `im::Vector` causes a stackoverflow by recursively calling a sort function. This PR collects the `im::Vector` into a `Vec` and uses `std`'s sorting implementation instead, which does not exhibit this behaviour. 
I've added a unit test to guard against this regressing.
> fix: stackoverflow on sorting large number of PaletteItems

- docs/building-from-source.md
> Add g++ in Ubuntu building from source guide

- CHANGELOG.md
- defaults/dark-theme.toml
- defaults/light-theme.toml
- defaults/settings.toml
- icons/codicons/add.svg
- lapce-data/src/config.rs
- lapce-data/src/svg.rs
- lapce-ui/src/app.rs
- lapce-ui/src/editor/tab.rs
- lapce-ui/src/editor/tab_header.rs
- lapce-ui/src/editor/tab_header_content.rs
- lapce-ui/src/find.rs
- lapce-ui/src/plugin.rs
- lapce-ui/src/search.rs
- lapce-ui/src/settings.rs
- lapce-ui/src/source_control.rs
- lapce-ui/src/status.rs
- lapce-ui/src/tab.rs
`feat: add tab in/active, add primary button colours`
`fix: include svg name when unwrapping`
`feat: add hover effect for source control panel`
`feat: replace manual drawing of checkbox with icons`
Closes #828 
Fixes https://github.com/lapce/lapce/issues/1485
Closes #1213
> feat: add tab in/active, add primary button colours

- CHANGELOG.md
- defaults/keymaps-common.toml
- lapce-core/src/command.rs
- lapce-data/src/editor.rs
Issue: #1621
Added a new keyboard shortcut, that triggers the hover effect at the cursor location. Very useful for people that use vim-like bindings. The suggested shortcut, `g h`, is what is used by vscode's popular vim plugin, but some other popular defaults might be `ctrl + k`, `k`, `K` among others can be seen in the wild.
As a future improvement we might want to change how mouse events dismiss the hover as currently any mouse event that isn't over the cursor position or hover triggers the hover to become inactive.
> feat: added show hover keyboard shortcut

- CHANGELOG.md
- lapce-core/src/language.rs
- lapce-proxy/src/buffer.rs
Registers `kts` files to the Kotlin language.
> Fix kts files not being recognized

- CHANGELOG.md
- lapce-ui/src/app.rs
> Fix: new windows would never be created after closing all

- CHANGELOG.md
- lapce-core/src/language.rs
> fix: use correct python identation

- lapce-ui/src/app.rs
> fix: drop stdin/stdout to not pollute terminal

- CHANGELOG.md
- lapce-ui/src/search.rs
This PR removes a random margin and the background fill from the search panel input. This change fixes a visual issue when the search panel is placed to the left or the right panels.
Before:
After removing margin:
After removing background:
> Fix visual bug in search panel

- CHANGELOG.md
- lapce-data/src/data.rs
- lapce-data/src/palette.rs
- lapce-ui/src/palette.rs
- lapce-ui/src/status.rs
This PR adds the keybinding for a command as the hint in the palette. Fixes #1683. This will make it easier for users to know the keybinding for a command they might be using often.  
It pays attention to what mode the user is in, so it won't recommend completely incorrect keybinds.
----
Could be improved with some better alignment of the keybindings?
I think this could also be improved by taking into account `when` the keybind can be used.
> Display the keybinding of a command within the palette

- CHANGELOG.md
- defaults/settings.toml
- lapce-core/src/command.rs
- lapce-data/src/config.rs
- lapce-data/src/editor.rs
- lapce-ui/src/editor/view.rs
This PR does two things:  
- Adds a command to save without formatting. This is in other editors. It is also generally useful (ex: large files where formatting is slow; or where you're occasionally editing a library file which doesn't use the same formatting as the rest of your code, like in C/C++)  
- Allows disabling formatting on autosave. Fixes #1650.  I set it to true by default, though it should perhaps be false by default since formatting on autosave can be annoying?  
It would be beneficial to allow 'forcing' a save. Other editors allow saving the file even if there are no edits. This would allow manual saving to then apply formatting for users with autosave enabled.
> Add save without formatting; Allow toggling of formatting for autosave

- .github/workflows/release.yml
It seems that I missed it originally
> ci: use edge branch for alpinelinux

- lapce-core/src/syntax/mod.rs
Fixes #1739   
Getting the root node of the tree and then finding a descendent for an offset would give a zero-sized node if the file is empty. This avoids that by checking whether there is any text in the file before accessing text at an index.  
It also adds this check to `find_enclosing_pair`, though I believe its caller avoids the issue by a separate check.
> Fix enclosing parentheses crash

- CHANGELOG.md
- lapce-proxy/src/dispatch.rs
There was a bug where searching in a workspace with files with large one-liner text would cause the editor to die (sometimes crash, sometimes visual artifacts due to creating a too large text layout and maybe messing with GPU memory or something). A common example would be minified javascript files, which are on a singular line and are quite massive.  
The issue was that the search would respond with the *entire* line's text, which could be a lot (ex: one of my files was 500kb of text in a single line)! This wouldn't be too bad by itself, though it would probably stress search performance if you had a lot of them, but the main issue comes from trying to render it. It would try creating a text layout, which would then cause issues due to it being so large.  
The fix is just to take a part …
> Limit search response size to avoid crash/perf issues

- CHANGELOG.md
- defaults/keymaps-common.toml
- lapce-core/src/command.rs
- lapce-core/src/editor.rs
This PR adds the following keybindings:
- `C W` and `C E`: Change word (delete_word_and_insert)
- `Shift+S` and `C C`: Change line (delete_line_and_insert) (keeps indentation)
- `G F`: Alternative to easily show quick fixes in normal mode (not vim default)
This contributes to closing #700 and #772 (but does not close them fully!)
> Add vim motions cw, ce, cc, S, and QOL modal bind gf

- CHANGELOG.md
- lapce-core/src/language.rs
- lapce-core/src/syntax/highlight.rs
- lapce-core/src/syntax/mod.rs
- lapce-data/src/document.rs
- lapce-data/src/markdown/mod.rs
THIS IS NOT A FULL FIX! It only fixes the *crash*, but not the underlying issue, as that is somewhere in the dependencies and I'm unable to find out how to fix it. The error will still be logged, but will not crash lapce.
I might look into the issue further, but suggest adding this band-aid so we at least don't get a crash.
Example of a logged error: `[2022-11-30][08:31:11][lapce_core::language][ERROR] Encountered QueryError { row: 52, column: 3, offset: 702, message: "expansion_flags", kind: NodeType } while trying to construct HighlightConfiguration for bash` - all information from the panic message is still present after this fix.
Shell scripts, and potentially other languages, make lapce panic when opened. This is explained further in the issue this PR closes.
Closes: #1762
Opens: …
> (band-aid) fix opening some file types crashing lapce

- lapce-core/src/language.rs
- lapce-core/src/syntax/highlight.rs
- lapce-core/src/syntax/mod.rs
- lapce-data/src/document.rs
- lapce-data/src/history.rs
- lapce-data/src/markdown/mod.rs
This is a follow-up to the syntax highlighting issues #1762 #1764 #1768 #1769 #1771.
This PR adds proper and visible failure handling of any future encounter with invalid syntax highlighting .scm files. When such a file is invalid, as soon as an associated file is opened, there will be a dialog saying 
The error will also be logged.
All the info from the panic is there, but without the confusion of "Why did lapce just crash???".
> Add error dialog for invalid syntax highlighting schemes

- lapce-ui/src/keymap.rs
With this PR, the keybindings which doesn't have a message/description will be `Capital case`d, instead of showing the `kebab_cased` name.
This is my first PR, let me know what you guys think
**Before**
**After**
> format keybinding name on settings to Capital case.

- lapce-ui/src/settings.rs
It currently goes to "Core Settings" rather than "Keybindings".
> Fix "Open Keyboard Shortcuts" enum.

- CHANGELOG.md
- lapce-data/src/editor.rs
- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/plugin/lsp.rs
- lapce-proxy/src/plugin/mod.rs
- lapce-rpc/src/proxy.rs
This will fix the following LSP-related issues: 
- Java LS does not show "Surround with try/catch" and similar issue-related actions
- All language servers don't always update code actions when the document was changed
- Rust LS sometimes highlights a line with a fix suggestion, but is unable to actually provide it in code actions
This PR updates the capabilities and code action requests to fully match LSP spec.
> Fix some LSP bugs causing code actions to not show up correctly

- lapce-core/src/language.rs
Java's indentation is almost always 4 spaces, so I think using 4 spaces as the default in Lapce as well makes a lot of sense.
> Use more standardized java indentation

- defaults/dark-theme.toml
- defaults/light-theme.toml
- defaults/settings.toml
- lapce-data/src/config.rs
- lapce-ui/src/editor.rs
- Added `editor.sticky_header_background` to allow different color for sticky header, defaults to $black in base
> Add sticky header theming option

- lapce-ui/src/editor.rs
This PR fixes small annoyances with scope and bracket highlighting, like drawing over sticky headers and drawing the scope highlights in code lens mode.
> minor fixes to scope and bracket highlight

- CHANGELOG.md
- lapce-ui/src/plugin.rs
__Description__
This pull request allows the user to right click on a plugin to access its settings.
- [ x] Added an entry to `CHANGELOG.md` if this change could be valuable to users
> Plugin settings shown on right click

- lapce-ui/src/status.rs
> fix: hide language/text details on non-editor tabs

- lapce-ui/src/tab.rs
Currently, clicking on a diff in the source control sidebar will cause it to replace the current editor (even if it is unsaved and/or a scratch file). This PR changes the code to not replace the currently opened file.  
(Question: Was the behavior of jump_to or this specific command changed some time ago? I don't remember opening the diff doing this a long while ago, but it started doing it sometime in the last couple months I believe)
> Don't use the active editor's view id for opening file diff

- lapce-data/src/document.rs
- lapce-ui/src/editor/view.rs
> Remove unnecessary `Arc<String>` indirection in `Document.ime_text` in favor of `Arc<str>`

- lapce-core/src/syntax/mod.rs
- lapce-core/src/syntax/util.rs
Splitted from #1796. That (#1796) pull request is so large it looks like it will never be merged, so I decided to break it down into smaller pieces.
This pull request performs one of the most important parts of improving program performance by changing a function that is constantly called in the program:
- removes many unnecessary multiple allocations of vectors (strings) to store one character in `lapce_core::syntax::Syntax::find_matching_pair`.
> Remove a lot of small vector allocation in `find_matching_pair`

- lapce-core/src/buffer/mod.rs
- lapce-core/src/char_buffer.rs
- lapce-core/src/lib.rs
- lapce-data/src/document.rs
Splitted from #1796. That (#1796) pull request is so large it looks like it will never be merged, so I decided to break it down into smaller pieces.
This pull request performs one of the most important parts of improving program performance by changing a function that is constantly called in the program:
- removes many unnecessary multiple allocations of vectors (strings) to store one character needed to use the `lapce_core::syntax::Syntax::find_tag` function.
To do this, I wrote a helper structure to store a single character `&str` on the stack instead of on the heap (I think this will be a useful structure both now and later).
And well, since this is a structure for storing a "string slice", then it must be done correctly so that it can be compared with other string structures, …
> Remove a lot of small vector allocation for `lapce_core::syntax::find_tag`

- Cargo.lock
- lapce-core/Cargo.toml
- lapce-core/queries/julia/highlights.scm
- lapce-core/queries/julia/injections.scm
- lapce-core/src/language.rs
- lapce-ui/src/editor.rs
This PR updates the julia queries (while giving credit to helix for the queries) 
Also fixes the indent guide for C/C++, Julia, Go, probably some other languages (and doesn't break already working Rust)
> Update julia queries, fix indent guide

- lapce-ui/src/settings.rs
This pull request does what was described in the `TODO`, and allocates and collects `name_text` only if `self.name_text.is_none()`
> Remove vec allocation in `SettingsItemInfo::name`

- Cargo.lock
- lapce-ui/Cargo.toml
- lapce-ui/src/settings.rs
This pull request does the following:
- Changes the structure of `LapceSettingsPanel::children` to use `hashbrown::HashMap`. This was done because the `std::collections::HashMap::drain_filter` method is not yet stable. Also, this should make things a lot faster with `LapceSettingsPanel::children`, since `hashbrown::HashMap` uses [`aHash`](https://github.com/tkaitchuck/ahash) by default, which is much faster than `SipHash 1-3` hash function [`used`](https://doc.rust-lang.org/src/std/collections/hash/map.rs.html#3142) in the default library (https://github.com/tkaitchuck/aHash/blob/master/FAQ.md#how-is-ahash-so-fast).
- Removes unnecessary creation of an intermediate vector `Vec<LapceSettingsKind>` (for which we have to go through all the keys and clone them).
- Corrects the search for a …
> Rewrite some parts of `LapceSettingsPanel::update_plugins`

- lapce-proxy/src/plugin/wasi.rs
I think there is a mistake in this place. This structure is created directly from the passed `volt_id: String` (https://github.com/lapce/lapce/blob/master/lapce-proxy/src/plugin/psp.rs#L215). It is further included in the [`PluginCatalog`](https://github.com/lapce/lapce/blob/master/lapce-proxy/src/plugin/catalog.rs#L36) structure. Finally, the `PluginCatalog` structure actively uses `volt_id` comparisons among themselves, for example [`here`](https://github.com/lapce/lapce/blob/master/lapce-proxy/src/plugin/catalog.rs#L366 ). However, the comparison is not made with the `VoltMetadata.name` field, but with the result of calling the [`VoltMetadata::id`](https://github.com/lapce/lapce/blob/master/lapce-rpc/src/plugin.rs#L76) function that are not equivalent.
This was discovered while working …
> Fix bug in `lapce_proxy::plugin::wasi::start_volt`

- lapce-ui/src/title.rs
Optimize the UI: add borders to SourceControlBranches.
Before:
After:
> Add borders to SourceControlBranches

- lapce-ui/src/settings.rs
We only need to clone the contents of the vector, not the vector itself.
> Remove cloning of the `colors` vector in `lapce_ui::settings::ThemeSection::update_items`

- lapce-data/src/document.rs
I noticed that the code was using lots of iterator adapters, and so the iterator adapters nested within the closures could be moved to the 'first layer'.  
This is a purely stylistic change, though I included a few comments in the area, but I believe that it improves readability of what the code is doing.
> Minor: get rid of unneeded nesting in phantom text code

- CHANGELOG.md
- lapce-data/src/document.rs
Fixes #1908   
(Where `|` is the cursor and `|H|` is a selection)  
Before: `|H|ello` -> right arrow key -> `He|llo`
`|H|ello` -> right arrow key -> `H|ello`  
This matches other applications better.  
It would be nice to have tests for this, but I didn't see testing code for the document movement commands?
> Fix cursor movement on selections with arrow keys

- lapce-rpc/src/file.rs
- lapce-ui/src/picker.rs
This is absolutely unnecessary as I don't think the code is very hot, but I was rather confused by how it works and I also didn't like the duplication.
This PR now avoids allocations previously used when re-joining the stripped prefix, at the cost of counting path components. Also, I think the resulting implementation is cleaner and the added (although, by default, disabled) tests are also a bonus.
> Improve `get_file_node[_mut]` efficiency

- lapce-ui/src/settings.rs
This pull request simplifies the `lapce_ui::settings::ThemeSection::new` function by removing the allocation of two intermediate vectors (one for `Vec<&str>`, the second inside `Itertools::sorted` method).
Also, since the colors are just `String`s and it's not important to preserve their order, the `Vec::sort_unstable` method is now used instead of the `Vec::sort` method (inside Itertools::sorted method), since this method is usually faster and does not require any additional allocations.
> Simplifying `lapce_ui::settings::ThemeSection::new`

- CHANGELOG.md
- Cargo.lock
- lapce-data/src/data.rs
- lapce-data/src/editor.rs
- lapce-data/src/palette.rs
- lapce-data/src/source_control.rs
- lapce-proxy/src/dispatch.rs
- lapce-ui/Cargo.toml
- lapce-ui/src/editor/tab_header_content.rs
- lapce-ui/src/explorer.rs
- lapce-ui/src/palette.rs
- lapce-ui/src/source_control.rs
- lapce-ui/src/tab.rs
Hi there! I'm enjoying using Lapce and excited to contribute to the project. This PR upates the styling of file names in the file explorer, file palette, and editor tab headers to reflect their curreng git/VCS status. I found this feature really useful in Atom (RIP). I've been using this locally for several days, and it has been accurate and stable so far.
Screenshot showing updated styling:  
Notes:
- no new system calls were needed; the data was already present on `LapceTabData.file_diffs`, it just needed to be tweaked a little to be accessible where needed
- `LapceTabData.file_diffs` is currently a `Vec<(FileDiff, bool)>`; this changes it to a `HashMap<PathBuf, FileDiff>` (for easy lookup by path) and adds a new `file_list: Vec<(PathBuf, bool)>` to support the `int` based indexing …
> Highlight git/VCS modified files in explorer, palette, and buffer tabs

- lapce-ui/src/explorer.rs
- lapce-ui/src/panel.rs
- lapce-ui/src/plugin.rs
Partially solves: https://github.com/lapce/lapce/issues/1398
> Open editors list can now be collapsed by clicking it

- CHANGELOG.md
- lapce-proxy/src/dispatch.rs
Fixes #1750   
The issue was that the new file was not registered, thus causing future attempts to update the file to error.
> Register buffer when saving-as a new file

- lapce-data/src/command.rs
- lapce-data/src/data.rs
- lapce-data/src/document.rs
- lapce-data/src/editor.rs
- lapce-data/src/explorer.rs
- lapce-data/src/history.rs
- lapce-data/src/hover.rs
- lapce-data/src/keypress/mod.rs
- lapce-data/src/palette.rs
- lapce-data/src/proxy.rs
- lapce-data/src/source_control.rs
- lapce-ui/src/editor/view.rs
- lapce-ui/src/hover.rs
- lapce-ui/src/palette.rs
- lapce-ui/src/settings.rs
- lapce-ui/src/source_control.rs
- lapce-ui/src/split.rs
- lapce-ui/src/tab.rs
- lapce-ui/src/window.rs
This PR adds documentation to various parts of the code to hopefully make it easier to quickly get an idea what is going on in the various functions while jumping around the codebase.  
There is also some stylistic changes, but nothing which should change behavior. Several of the `LapceUICommand` were expanded into enum-structs, so that the fields are named, because that is typically clearer (and standardizes the names, since some places use different names for the same thing!)  
I added comments on most `LapceUICommand` entries as well.  
Some `LapceUICommand` commands were removed as they're no longer referenced anywhere, and the like.
> Add docs; style-changes; remove unused commands

- lapce-ui/src/editor.rs
remove redundant context menus in input box, fix: https://github.com/lapce/lapce/issues/1952
file editor:
input box:
> fix: redundant context menus in input box

- lapce-data/src/rename.rs
- lapce-ui/src/editor.rs
- lapce-ui/src/tab.rs
disable trigger hover when renaming，only trigger hover when focus on editor, fix: https://github.com/lapce/lapce/issues/1951
> fix: trigger hover when renaming

- CHANGELOG.md
- defaults/settings.toml
- lapce-data/src/completion.rs
- lapce-data/src/config.rs
- lapce-data/src/document.rs
- lapce-data/src/editor.rs
- lapce-ui/src/completion.rs
Adds the ability to view the expansion from completion as phantom text where the cursor is.  
(VSCode has this feature as well, under the name 'Suggestion Preview'.)  
(Might be nice to make snippets mark the places in the completion lens)
- This is disabled by default, since VSCode disables it by default. I could imagine enabling it by default, but since it is not typical it may be distracting for most users since they aren't used to it.
- The completion lens would appear in multiple editor views of the same document. I don't think this is really a problem, and making it only appear in the active document would require some modification of the code to have some per-editorview document textlayouts?
- Multiline completion items are cut off at the moment, because we don't have support for …
> Implement completion lens

- CHANGELOG.md
- lapce-data/src/command.rs
- lapce-data/src/explorer.rs
- lapce-proxy/src/dispatch.rs
- lapce-rpc/src/proxy.rs
- lapce-ui/src/explorer.rs
- lapce-ui/src/tab.rs
This PR implements duplicating files in the fs tree context menu.
> Implement file duplication

- Cargo.toml
#1940 forgot to include the `serde` feature requirement. Lapce would still compile, but running `lapce-core`/`lapce-rpc` in isolation (via tests) would fail to compile due to the missing feature.
> Add serde feature req to indexmap dep

- CHANGELOG.md
- Cargo.lock
- defaults/settings.toml
- icons/codicons/refresh.svg
- lapce-data/Cargo.toml
- lapce-data/src/command.rs
- lapce-data/src/config.rs
- lapce-data/src/data.rs
- lapce-data/src/hover.rs
- lapce-data/src/images.rs
- lapce-data/src/lib.rs
- lapce-data/src/markdown/layout_content.rs
- lapce-data/src/markdown/mod.rs
- lapce-data/src/plugin.rs
- lapce-ui/src/completion.rs
- lapce-ui/src/hover.rs
- lapce-ui/src/plugin.rs
- lapce-ui/src/signature.rs
- lapce-ui/src/tab.rs
This PR implements rendering of images in markdown views (hover, completion documentation, signature, and plugin readmes).  
- The loading icon it shows is a bit weird, because typically you see them spinning  
- Sometimes the images don't load??? 
- I had this most often with the plugin readme (I put an image in my Aleph theme plugin's readme for testing). 
- I note that I have the same issue with plugin icons sometimes not loading, despite that they should be in the local cache folder by now. I'd think this was some github throttling (are those icons even hosted on github pages?), but it also happened for a local image (if less often??). I'm very confused. 
- The positioning of images is off. This is mostly due to the code not paying attention to whether the user did a hard line break …
> Implement rendering of images in markdown views

- lapce-ui/src/editor/tab.rs
- lapce-ui/src/editor/tab_header_content.rs
- Tab separators are drawn outside the tab
- Active tab underline is properly aligned to have padding of 2px from both sides
> fix: align width and tab separator correctly + refactor

- lapce-data/src/editor.rs
- lapce-ui/src/find.rs
- lapce-ui/src/search.rs
1. Not highlighting the case-sensitive button when hovering over it.
2. Not toggling case-insensitive button when text is empty.
> Fix some visual issues in local find box

- lapce-data/src/config.rs
This fixes some hanging causes by a feedback loop when listening to config files/folders.
Apparently, we are performing some changes when we listen to a file.
Presumably we are modifying some kind of metadata which triggers another notify causing the feedback loop.
I checked strace and we seem to only be performing `readlink` on `/home/hbina/.local/share/lapce-stable/*`.
```
statx(AT_FDCWD, "/home/hbina/.config/lapce-stable", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFDIR|0775, stx_size=4096, ...}) = 0
statx(AT_FDCWD, "/home/hbina/.config/lapce-stable/keymaps.toml", AT_STATX_SYNC_AS_STAT, STATX_ALL, {stx_mask=STATX_ALL|STATX_MNT_ID, stx_attributes=0, stx_mode=S_IFREG|0664, stx_size=62, ...}) = 0
openat(AT_FDCWD, …
```
> Only be notified of content changes in file

- lapce-data/src/editor.rs
`editor.compare` needs to be set in addition to `editor.view`. Otherwise, the size of the editor (the scroll area) is computed wrong.
> fix: ToggleHistory command

- lapce-proxy/src/dispatch.rs
Instead of spawning a new thread for every keystroke.
> Limit global search to 1 worker thread

- CHANGELOG.md
- lapce-data/src/document.rs
This follows up on #1911: the up/down keys should also move relative to the selection.
> Fix cursor movement on selections with arrow up/down keys

- CHANGELOG.md
- lapce-ui/src/editor.rs
Fixes https://github.com/lapce/lapce/issues/1949
Implementation suggested by https://github.com/lapce/lapce/issues/1949#issuecomment-1376658407. I have confirmed that with this patch I can right click to rename a symbol.
> Add 'Rename Symbol' option on right-click

- CHANGELOG.md
- lapce-proxy/src/dispatch.rs
- lapce-rpc/src/core.rs
For SSH sessions, the remote user's home directory never actually being sent to the editor. This means the file picker defaults to the file system root, which is not ideal.
> send user HOME dir from proxy to editor

- lapce-proxy/src/plugin/psp.rs
This will never hang because `rx` dies immediately after. It should have better performance characteristics because unbounded channels have a lot more book keeping that it needs to manage.
> Use bounded channel of 1 when responding to plugin rpc requests

- defaults/keymaps-nonmacos.toml
- lapce-data/src/document.rs
2 issues:
1. it overlapped with select all current.
2. it never overwrites the selection of the cursor.
Fixes: https://github.com/lapce/lapce/issues/2025
> Fix select current line not working

- CHANGELOG.md
- lapce-data/src/proxy.rs
> fix: remove ssh timeout option on windows

- defaults/settings.toml
- lapce-data/src/config.rs
- lapce-ui/src/tab.rs
It's extremely annoying when it flies to multiple places with each and every keystroke
> Add an option to disable moving the focus area when you type

- CHANGELOG.md
- defaults/keymaps-macos.toml
- defaults/keymaps-nonmacos.toml
- lapce-core/src/command.rs
- lapce-core/src/editor.rs
> feat: add command and keybinds to delete line

- lapce-proxy/src/plugin/lsp.rs
- lapce-proxy/src/plugin/mod.rs
- lapce-proxy/src/plugin/psp.rs
- lapce-proxy/src/plugin/wasi.rs
As of now, plugins are merely there to spawn the actual LSP by way of `host/startLspServer` command and then it does _nothing_ because it never registered any capabilities and lapce itself never cared about the response from the init request. This changes that.
1. Use volt activation filters for the document filters.
2. Extract out the client capabilities struct to a function and pass it to the plugin as well.
This does require the plugin themselves to reply to the host init request like here: https://github.com/lapce/lapce-plugin-rust/pull/17
> Enable plugins to act as LSP themselves

- defaults/settings.toml
- lapce-core/src/buffer/mod.rs
- lapce-data/src/command.rs
- lapce-data/src/config.rs
- lapce-data/src/data.rs
- lapce-data/src/document.rs
- lapce-data/src/history.rs
- lapce-ui/src/tab.rs
issue: https://github.com/lapce/lapce/issues/2029
> feat: configurable diff context lines

- lapce-data/src/data.rs
Fix issue https://github.com/lapce/lapce/issues/2124
Check content history version change and EditorView change in OpenFile and OpenFileDiff.
> fix cannot open file when diff already opened

- CHANGELOG.md
- lapce-data/src/document.rs
Do not auto close parentheses/matching pairs when typing in settings, search fields, commit messages, ...
Fixes #2155
> fix: Do not auto close matching pairs in inappropriate inputs

- lapce-ui/src/search.rs
Allow folding file content in global search results
Issue: https://github.com/lapce/lapce/issues/2213
> feat: allow folding file content in global search results

- lapce-data/src/document.rs
- lapce-proxy/src/buffer.rs
Since the file doesn't exist, it is going to fail. Thus aborting the save procedure.
> Fix attempting to canonicalize a path when saving a new file

- lapce-data/src/command.rs
> remove duplicate command 'GotoLocation'

- defaults/keymaps-nonmacos.toml
#2071 added this binding, but it's redundant with the existing one (for cut). Worse, the result is that two lines are removed instead of a single one.
I think it's better to cut instead of deleting because that's what every editor I've seen does. And `Cut` without a selection, already cuts the whole line, as it does everywhere else.
> Remove duplicate binding for Shift-Delete

- lapce-data/src/data.rs
- lapce-data/src/document.rs
- lapce-data/src/settings.rs
- lapce-ui/src/editor/view.rs
- lapce-ui/src/settings.rs
Feature: [Allow filtering on the settings view](https://github.com/lapce/lapce/issues/2283)
Filter setting items and show matches count
> feat: filter settings

- lapce-ui/src/settings.rs
This just adds a placehoder text in the settings filter input, to make it clear that it's a text field (which was added in https://github.com/lapce/lapce/pull/2289)
> Add placeholder text to filter input in settings

- lapce-core/src/language.rs
- lapce-proxy/src/buffer.rs
Fixes #2296.
I've tested with a local build, seems to work fine. Basically I did the same thing as [this PR](https://github.com/lapce/lapce/pull/1603).
> Enable XML syntax highlighting for csproj files

- lapce-proxy/src/terminal.rs
Not setting the `TERM` variable causes weird graphical behavior in the integrated terminal. See #1695.
> fix: set TERM for flatpak

- Cargo.lock
- lapce-app/Cargo.toml
- lapce-app/src/app.rs
Ports the CLI to the floem version of Lapce.  
So you can now do `lapce ./some-folder` or `lapce ./file1.txt ./file2.txt`.  
This does not port the 'open in existing editor code', that is tracked by #2376.
> Reimpl CLI interface

- CHANGELOG.md
- defaults/keymaps-common.toml
- lapce-core/src/command.rs
- lapce-data/src/data.rs
- lapce-data/src/editor.rs
Adds CreateMark and GoToMark functionality, but only the local version: e.g. within the current buffer. (no global marks yet).
Will add an entry to the changelog.md if everything is fine with MR
> Feature: Add basic Vim marks feature

- lapce-app/src/config/editor.rs
- lapce-app/src/doc.rs
- lapce-app/src/editor.rs
- lapce-app/src/editor/movement.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/main_split.rs
- lapce-app/src/palette.rs
- lapce-app/src/window_tab.rs
- lapce-core/src/buffer/mod.rs
- lapce-core/src/buffer/rope_text.rs
- lapce-core/src/soft_tab.rs
This PR breaks the text layout logic and movement logic out of the `Document` structure.  
Text layouts and functions related to points / offsets are moved to the `EditorViewData` structure that is put within `EditorData`.  
This is necessary for some linewrapping configurations, such as when the editor should wrap at the editor width and thus there should be separate lines. As well, having the views like this would allow other alternative representations of the same document more easily (git views?)  
This also moves the movement logic in `Document` out into its own file and simplifies what pieces of logic are actually needed. This will make it easier to test.  
Various `Buffer` functions had their implementations moved to `RopeText`, since they did not depend on the details of `Buffer`. …
> Move text layout logic out of Document

- CHANGELOG.md
- lapce-app/src/completion.rs
- lapce-app/src/config/editor.rs
- lapce-app/src/doc.rs
- lapce-app/src/editor.rs
- lapce-app/src/window_tab.rs
- lapce-core/src/buffer/rope_text.rs
This PR reimplements completion lens from #1968, with similar limitations  
- No multiline (need multiline phantom text)
- Doesn't display every possible way of displaying a completion item. Ex: If you type `r` and there's a suggestion for p**r**intln!()', then it won't display that as then lens since it doesn't start with 'r'. 
There is also various added comments to the completion logic, and some rearranging of logic.  
I've changed the `config` font size functions to fallback, which I believe is the more correct option based on the docs we have for them. As well, using `font_size` directly when `error lens font size == 0` has the issue that then error lens font size won't be clamped to a reasonable value like `font_size()` does, which this fixes.
------
I'm a bit uncertain that storing …
> Impl completion lens

- lapce-app/src/window_tab.rs
This dispatches focus commands properly.  
For example, using "Save" in the palette would not work due to this not being hooked up. Now that the command is sent to the right place, the palette command works properly.  
I tried to roughly imitate the logic in [lapce-data/data.rs](https://github.com/lapce/lapce/blob/b89c76931b5665742c5d0ae648e636cc9732b400/lapce-data/src/data.rs#L2187). I'm not certain of what general way to send a focus command to the current `focus` would be.
> Dispatch cmd properly

- Cargo.lock
- lapce-app/Cargo.toml
- lapce-app/src/app.rs
- lapce-app/src/command.rs
- lapce-app/src/config.rs
- lapce-app/src/editor.rs
- lapce-app/src/palette.rs
- lapce-app/src/palette/item.rs
- lapce-app/src/palette/kind.rs
- lapce-app/src/panel/data.rs
- lapce-app/src/window_tab.rs
This PR's focus is reimplementing a variety of the missing workbench commands.  
- `OpenFile`
- `RevealActiveFileInFileExplorer`
- `ChangeColorTheme` / `ChangeIconTheme`
- This required some minor changes in how palette works.
- It also changes the config to sort the theme names, which will make the ordering consistent between palette and settings dropdown
- `Open{Settings,Logs}{File,Directory}` / `OpenKeyboardShortcutsFile` / `Open{Proxy,Themes,Plugins}Directory`
- We don't have the keyboard shortcuts menu reimplemented, so `OpenKeyboardShortcuts` is not implemented.
- `SaveAll`
- `TogglePanel{Left,Right,Bottom}Visual`
- `SourceControlInit`, I'd wait on the others until there's a panel
Other:
- Modifies `config` color/icon theme lists to be `im::Vector` to make them cheaper to clone. …
> Reimplement various workbench commands

- lapce-app/src/app.rs
- lapce-app/src/code_action.rs
- lapce-app/src/editor.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/file_explorer/node.rs
- lapce-app/src/keypress.rs
- lapce-app/src/lib.rs
- lapce-app/src/listener.rs
- lapce-app/src/palette.rs
- lapce-app/src/panel/debug_view.rs
- lapce-app/src/panel/global_search_view.rs
- lapce-app/src/panel/problem_view.rs
- lapce-app/src/rename.rs
- lapce-app/src/terminal/data.rs
- lapce-app/src/title.rs
- lapce-app/src/window.rs
- lapce-app/src/window_tab.rs
Uses the listener ~~from https://github.com/lapce/floem/pull/55~~ for command receiving.  
This simplifies some of the code, removing the need to use `Some` in all the locations, and makes it more obvious what the command fields are for.  
~~The CI build will fail since this needs to be updated to point at the right commit!~~
> Use Listener for commands

- .github/workflows/release.yml
caused by https://git.alpinelinux.org/aports/commit/?id=cab9b787b39387f0b3d30d218b0739c3e21aefb8
should be fixed in rust at some point https://github.com/rust-lang/rust/pull/106246
> ci: use stable alpine release

- lapce-app/src/about.rs
- lapce-app/src/app.rs
- lapce-app/src/command.rs
- lapce-app/src/config.rs
- lapce-app/src/lib.rs
- lapce-app/src/title.rs
- lapce-app/src/web_link.rs
- lapce-app/src/window_tab.rs
Implemented the "about lapce" popup for the floem ui. Progress for #2417.
Opening the popup greys out the rest of the editor, just like in the druid version. Clicking anywhere on the greyed-out area, or pressing the "close modal" key closes the popup.
> Re-implemented "About Lapce" popup.

- CHANGELOG.md
- extra/linux/dev.lapce.lapce.desktop
Fixes #2494, it seems that there needs to be a `%F` to be able to use Lapce as an option.
> Show Lapce as an option when doing "Open With..." on Linux

- CHANGELOG.md
- lapce-app/src/editor.rs
- lapce-app/src/editor/movement.rs
- lapce-app/src/keypress.rs
- lapce-core/src/editor.rs
- lapce-core/src/mode.rs
Adds multi-line yank and delete for vim-motions, `3yy`, `5dd` f.e. 
Achieved by only taking the count from the keypress state if the command was indeed executed, and only marks the command as executed when a change is committed. 
The behavior of something like `3dj` is the same as the previous behaviour on `dj`.
I made an exception to the clippy too many args on one function, I could pack that into a struct, tuple, or whatever, depending on if that's preferred.
> Vim motion multi-line yank and delete

- lapce.spec
Fixes build on Fedora and other rpm-based distros.
> Add libxkbcommon-x11-devel as a dependency in lapce.spec

- Cargo.lock
- Cargo.toml
- lapce-app/Cargo.toml
See also lapce/floem#93
This makes it possible to test Glazier's native Wayland support in Lapce, without force-enabling it for all users, as it isn't yet ready. This still hangs for me (in release mode), but it appears to mostly work in debug mode. I believe this hang is still the one tracked in Smithay/calloop#127
I'm not sure why it fails in release despite working in debug mode - I guess it must be a race condition due to Lapce's multi-threading. Anyway, that's less important to debug
> Add a feature to enable Wayland support

- lapce-app/src/app.rs
- lapce-app/src/main_split.rs
- lapce-app/src/terminal/panel.rs
- lapce-app/src/window.rs
- lapce-app/src/window_tab.rs
Allows specifying bindings that use `mouseforward`, `mouseback` and `mousemiddle`.
Does not allow specifying bindings that use the primary two mouse buttons.
Closes #2572.
I haven't added an entry to `CHANGELOG.md`, but can do if you'd like.
> Allow binding mouse buttons to commands

- lapce-app/src/panel/plugin_view.rs
- lapce-app/src/title.rs
> Popout menus now appear beneath their buttons, instead of at (0, 0)

- lapce-app/src/command.rs
- lapce-app/src/file_explorer/node.rs
- lapce-app/src/file_explorer/view.rs
- lapce-app/src/window_tab.rs
Closes #2575, altough the part with the settings and keymaps is not implemented, as I'm not sure if this is a wanted addition.
> feat: open files in new tab on middle click

- lapce-app/src/doc.rs
- lapce-app/src/editor/view.rs
- lapce-core/src/buffer/rope_text.rs
- lapce-core/src/syntax/mod.rs
- lapce-core/src/word.rs
Highlight enclosing brackets when `highlight_matching_brackets` is enabled.
Draw lines delineating the enclosing scope when `highlight_scope_lines` is enabled.
Currently only draws the highlights and scope lines for one cursor, even if there are multiple cursors.
Currently doesn't draw highlights or scope lines on the sticky header.
Relates to #2417.
> Add support for highlighting enclosing brackets

- lapce-core/src/buffer/mod.rs
- lapce-core/src/editor.rs
- lapce-core/src/selection.rs
If the number of lines in the copy buffer is divisible by the number of selection regions, partition the copy buffer into groups of equal numbers of lines and paste one group at each selection region.
Closes #2625.
> Implement per cursor copy and paste

- CHANGELOG.md
- lapce-proxy/src/plugin/mod.rs
Previously, Lapce was not sending the right LSP capabilities, leading to language servers like the Zig Language Server to not send any diagnostics.
> Send diagnostics capabilities for LSP

- Cargo.lock
- lapce-proxy/Cargo.toml
Dependency was removed as part of terminal profiles feature, since we don't have to figure out the binary path anymore
> fix: drop unused "which" dependency

- lapce-app/src/config.rs
- lapce-app/src/config/editor.rs
- lapce-app/src/config/terminal.rs
- lapce-app/src/terminal/view.rs
The terminal font height settings are different then the editor settings. This PR changes the calculation of the terminal font height so the setting now behaves the same as setting the editor font height.
This PR also adds a contrast checker for the terminal, which switches the foreground color to the terminal background color if the contrast is bad.
> Terminal font height setting

- defaults/keymaps-common.toml
Added keybindings that are often used in macOS systems or the emacs editor to navigate UP or DOWN via `CTRL+P` and `CTRL+N` respectively.
I made sure to ignore these keybindings in case the `list_focus` mode is enabled, so the navigation in this mode is not overwritten by the added keybindings.
Please let me know if I need to make any modifications or improvements.
> Added navigation keybindings

- CHANGELOG.md
- lapce-app/src/main_split.rs
- lapce-proxy/src/buffer.rs
Fixes #2753 
When a `Buffer` in proxy is created it tries reading the file's contents, but it would mark the buffer as read-only if it failed. This would disallow saving.
This PR just makes it so that if the error is simply 'not found' then the `Buffer` is not marked as read-only.   
(Also it adds a log for errors on saving, which seems useful to have)  
An alternative method that could instead be used would be to have a separate proxy command for instantiating a new file which then manually sets `read_only = false`, but I think this method fits better. We should probably err on the side of letting users try to save files usually, even if the filesystem refuses.
> Don't mark nonexistent files as read only

- lapce-app/src/command.rs
- lapce-app/src/window_tab.rs
This adds a command to open the Floem Inspector, which can be handy to investigate performance and layout issues.
> Add UI inspector command

- lapce-app/src/about.rs
- lapce-app/src/config/color.rs
- lapce-app/src/config/icon.rs
- lapce-core/src/language.rs
This removes 219 warnings with Rust 1.74.0.
All changes are from `cargo fix`.
See https://github.com/rust-lang/rust/issues/115010
> Add explicit static lifetime to consts

- lapce-app/src/editor.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/editor/view_data.rs
- lapce-app/src/panel/source_control_view.rs
- lapce-core/src/cursor.rs
* Block cursors were rendered with a fixed width, rather than the width of the current character, when after an inlay hint and using a variable width font.
* In visual normal mode, the selection highlight didn't extend past the end of the current line when the cursor was past the end of the line.
* In visual normal mode, if there was an inlay hint after the end of the current line and the cursor was past the end of the line, the cursor was rendered after the inlay hint.
* In visual normal and block modes, when selecting backwards to the first character after an inlay hint, the selection highlight extended leftward of the cursor to include the inlay hint.
* When there were multiple cursors on the same line, only one was rendered.
* The selection highlight for visual block mode excluded the …
> Reworked cursor rendering, fixing several bugs

- lapce-app/src/doc.rs
- lapce-app/src/main_split.rs
- lapce-proxy/src/buffer.rs
- lapce-proxy/src/dispatch.rs
- lapce-rpc/src/proxy.rs
On some operations we can end up with a file opened that has no actual directory. The prime case is when you do `Run and Debug`, it opens `.lapce/run.toml` and fills it out if the file is empty. However, we can't actually *save* the file if we did not already have a `.lapce` folder.  
This makes the default behavior of saving create all parent directories (though it can be configured via a flag on the `Save` commands, if we ever want to put that as a setting).
> create_dir_all when saving

- CHANGELOG.md
- lapce-app/src/editor.rs
Along with a few other `FocusCommand`s (`ToggleCaseSensitive`, `GlobalSearchRefresh`, `SearchInView`, and 23 more), `SaveWithoutFormatting` was not being handled. This pr adds handling for `SaveWithoutFormatting` and sets the catch-all match arm to be `_ => unimplemented!()`
> fix: save without formatting now calls save.

- Cargo.lock
- lapce-app/Cargo.toml
- lapce-app/src/doc.rs
After #2794 and #2660, I also made a clipboard PR. It supports Wayland and uses the clipboard protocol for GUI applications there, so the clipboard should reliably work in containers like Flatpak in the future without extra permissions. Fixes https://github.com/lapce/lapce/issues/2787, https://github.com/lapce/lapce/issues/2768, https://github.com/lapce/lapce/issues/2676.
It requires the corresponding PR in floem (https://github.com/lapce/floem/pull/203).
> bump floem and use floem::Clipboard

- lapce-core/src/language.rs
> fix: hide inline grammars

- Cargo.lock
- lapce-app/Cargo.toml
- lapce-app/src/completion.rs
- lapce-app/src/doc.rs
- lapce-app/src/editor.rs
- lapce-app/src/editor/gutter.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/editor/view_data.rs
- lapce-app/src/main_split.rs
- lapce-app/src/palette.rs
- lapce-app/src/status.rs
- lapce-app/src/window_tab.rs
- lapce-core/src/editor.rs
- lapce-core/src/language.rs
This PR is part of extracting the editor code into a crate for users of Floem.
Goals:
- Make `Document`/`Editor`/etc. less dependent on Lapce-specific behaviors
- Allowing using whatever 'backend' of saving/loading files, such as purely locally
- Syntax highlighting
- Phantom text
- Allow more testing & bench marking
- Currently many pieces of the code are annoying to test
- Ex: Movement would be a great place to test, but currently hard due to how closely it is linked to various other parts of the code (like `CommonData` + `EditorViewData`)
- Ex: Editing the file is a great place to benchmark, with definite areas where it is slower than needed
- Ideally, make the code simpler!
The extraction will be done over multiple PRs, to avoid ending up with one massive PR and allowing discussion of …
> Doc backend

- Cargo.lock
- Cargo.toml
- defaults/keymaps-common.toml
- defaults/settings.toml
- lapce-app/src/completion.rs
- lapce-app/src/config/editor.rs
- lapce-app/src/doc.rs
- lapce-app/src/doc/phantom_text.rs
- lapce-app/src/editor.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/inline_completion.rs
- lapce-app/src/keypress/condition.rs
- lapce-app/src/lib.rs
- lapce-app/src/window_tab.rs
- lapce-core/src/command.rs
- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/plugin/lsp.rs
- lapce-proxy/src/plugin/mod.rs
- lapce-proxy/src/plugin/psp.rs
- lapce-proxy/src/plugin/wasi.rs
- lapce-rpc/src/proxy.rs
This PR implements Inline Completion support.
Inline completions are a 3.18 (upcoming) LSP feature which allows language serves to provide completion text within the editor. 
The primary usecase for this is Github Copilot-like extensions which I have implemented at https://github.com/MinusGix/lapce-copilot/ , thus fixing #1081.
This PR has to use a fork of lsp-types as they don't yet support inline-completion. I've created a PR to that repo with support. I've put the fork of lsp-types on the Lapce organization.  
I added a `[patch.crates-io]` for lsp-types so that we won't get two versions of lsp-types from psp-types (which I'm not updating currently).  
(Though, Github Copilot doesn't support Inline Completion by itself - it has a custom request for that. The lapce-copilot plugin just …
> Add inline completion support

- lapce-app/src/config/editor.rs
- lapce-app/src/doc.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/editor/view_data.rs
Continuation of #2836 
- Completely removes dependency on `common: Rc<CommonData>` for `Document`
- Changes `render_whitespace` to use an enum rather than a string so it is a more reasonable API
- Moved find onto proxy
- I think it would be good to have a decent default find impl in floem-editor, but it would need some adaption work that doesn't need to be done immediately
- Introduce `LineStyling` onto `Document`
- I want to use something like this for `VisualLines` as well most likely
- Moves autosave duration onto backend
- Add a function for creating preedit phantom text, currently encouraging implementors of `Backend` to add it seems the best way
> Doc backend continued

- lapce-app/src/about.rs
- lapce-app/src/alert.rs
- lapce-app/src/app.rs
- lapce-app/src/config.rs
- lapce-app/src/doc.rs
- lapce-app/src/editor/diff.rs
- lapce-app/src/editor/gutter.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/editor_tab.rs
- lapce-app/src/file_explorer/view.rs
- lapce-app/src/keymap.rs
- lapce-app/src/markdown.rs
- lapce-app/src/panel/debug_view.rs
- lapce-app/src/panel/global_search_view.rs
- lapce-app/src/panel/plugin_view.rs
- lapce-app/src/panel/problem_view.rs
- lapce-app/src/panel/source_control_view.rs
- lapce-app/src/panel/terminal_view.rs
- lapce-app/src/panel/view.rs
- lapce-app/src/plugin.rs
- lapce-app/src/settings.rs
- lapce-app/src/status.rs
- lapce-app/src/terminal/view.rs
- lapce-app/src/text_area.rs
- lapce-app/src/text_input.rs
- lapce-app/src/title.rs
This PR changes `get_color`/`get_style_color` -> `color`/`style_color`, and changes the return from `&Color` -> `Color`.  
The aim for this was mostly to make performing these very common operations simpler. This fits other getter-style functions, like we use `terminal_font_family`/`font_size`/`symbol_svg` instead of prefixing `get` on them.
> Refactor color handling

- lapce-app/src/doc.rs
- lapce-app/src/doc/phantom_text.rs
- lapce-app/src/editor.rs
- lapce-app/src/editor/visual_line.rs
This PR removes the `LapceConfig` parameter to `do_insert` and asks the backend about what auto closing/surround configuration it has. Forgot to do this in previous PR.
It also removes the `DiagnosticSeverity` from the `PhantomTextLine`, as that is LSP originating and only really useful for Lapce because of us processing diagnostics.
> Remove LapceConfig from do_insert

- Cargo.toml
> build(deps): lock lsp-types to patch versions only

- lapce-app/src/command.rs
- lapce-app/src/file_explorer/data.rs
- lapce-app/src/file_explorer/node.rs
- lapce-app/src/file_explorer/view.rs
- lapce-app/src/window_tab.rs
- lapce-proxy/src/dispatch.rs
- lapce-rpc/src/file.rs
- lapce-rpc/src/proxy.rs
Implement functionality for renaming files and directories, accessible by right clicking the item in the file explorer and selecting "Rename...".
There was already some functionality in `lapce-proxy` for renaming paths, but there was no UI for using it. This PR adds a UI, and also makes some changes to the existing functionality:
* When renaming a file, any buffers affected by the rename are updated to use the new path.
* Non existing ancestor directories of the new path are created on rename.
* A new request, `TestCreateAtPath`, is added to allow querying whether a rename will succeed without performing it (not all failure reasons are covered - for example, it is not checked whether the user has permission to create a file in the target directory).
Note that this functionality can be …
> Implement path renaming from the file explorer

- CHANGELOG.md
- lapce-app/src/app.rs
- lapce-app/src/editor.rs
- lapce-app/src/main_split.rs
- lapce-core/src/cursor.rs
- lapce-core/src/selection.rs
- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/plugin/catalog.rs
- lapce-proxy/src/plugin/dap.rs
This pull request enables Lapce to see untracked files in a fresh git repository. See issue #2779. 
After applying this fix, I've noticed that files that have no history will have an empty diff like this: 
It does seem like a different scope of fix and in a different area. There's a pull request that does seem to be related to this: https://github.com/lapce/lapce/pull/2017 . I am not sure about the implications here, and would love to see this being addressed/discussed separately.
> fix: detect git changes when no commit in repository

- CHANGELOG.md
- lapce-app/src/app.rs
- lapce-app/src/command.rs
- lapce-app/src/config.rs
- lapce-app/src/config/icon_theme.rs
- lapce-app/src/editor.rs
- lapce-app/src/editor/diff.rs
- lapce-app/src/editor_tab.rs
- lapce-app/src/file_explorer/data.rs
- lapce-app/src/main_split.rs
- lapce-app/src/palette.rs
- lapce-app/src/palette/kind.rs
- lapce-app/src/window_tab.rs
The user can either:
* Select the files to compare by right clicking on them in the file explorer.
* Invoke the `diff_files` command and select the files to compare from the palette.
Fix double clicking on an unconfirmed diff editor tab not confirming it.
> Implement comparing files in the diff editor

- CHANGELOG.md
- lapce-app/src/keymap.rs
Allows searching for shortcuts (e.g. "ctrl+p") and when conditions (e.g. "in_snippet") in the keyboard shortcuts overview
> Improve search in keyboard shortcuts overview

- CHANGELOG.md
- Cargo.lock
- defaults/settings.toml
- lapce-app/Cargo.toml
- lapce-app/src/config/editor.rs
- lapce-app/src/file_explorer/data.rs
This PR fixes #811 by providing a `files_exclude` string option which using blob patterns to blacklist files and directories.
Currently using default value of `"**/{.git,.svn,.hg,CVS,.DS_Store,Thumbs.db}"` (Referenced from VSCode)
> Feat: add `files_exclude` option (Fixes #811)

- Cargo.toml
The README lists the license as Apache-2.0, but the `Cargo.toml` doesn't
contain license metadata. Add the license to `Cargo.toml` as well.
> Cargo.toml: Add license to metadata

- CHANGELOG.md
- lapce-app/src/command.rs
- lapce-app/src/file_explorer/data.rs
- lapce-app/src/file_explorer/node.rs
- lapce-app/src/file_explorer/view.rs
- lapce-app/src/keypress.rs
- lapce-app/src/text_input.rs
- lapce-app/src/window_tab.rs
- lapce-rpc/src/file.rs
This PR is primarily for adding back the file explorer context menu items.  
Fixes #2873  #2953   
Commits:  
- Add some comments, use `let Some(x) = ... else { return; }` to avoid some over-indented code
- Remove unused `id` field.  
The `id` field was not used anywhere.  
While it could have been useful in some cases (ex: logic that wants to simply know when the file explorer was updated), I'm not sure it would have been that useful as it is changed before the updating of the explorer. It would be simple enough to add back in later, with whatever form is useful when actually needed.  
-  Initial adding of missing context menu commands
- Main commit, actually implement new file / new directory / duplicate
- Also fixes a bug we apparently had where typing in the input box would cause …
> Remaining file explorer context menu entries

- CHANGELOG.md
- lapce-app/src/app.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/window.rs
Fixes #3012   
The issue was that `find_view` stops the pointer down event from propagating up to `app_view`, and so `app_view` lost the focus. Our current code dispatches (all?) keybinds from `app_view` to the locations, and so if `app_view` lost the focus then the find view would never receive the inputs (because it doesn't actually take the focus for itself).  
(The reason the `find_view` stops the input is because `app_view` also dispatches pointer down events! And so its naive code would let the pointer-down go through the find view and click on the editor itself)  
My fix for this is to simply store the `app_view_id` similarly to other stored ids so that the find view can manually focus it when clicked.  
-----
I'd like a better solution to this manual management of the focus, but I …
> Focus on app_view so that find receives keypresses

- lapce-app/src/app.rs
This makes so that when opening Lapce (or creating a new window), the focus will be on the main view, allowing typing in the editor or opening the palette to automatically work.
> Focus on app_view when creating the view

- defaults/keymaps-common.toml
- defaults/keymaps-macos.toml
- defaults/keymaps-nonmacos.toml
This changes what #2698 added to instead put the up/down in insert mode into the MacOS file, as Ctrl+n/Ctrl+p are not for movement on Windows/Linux. (Ctrl+n is typically used for new file, which we already have bound)  
This also moves Ctrl+b/Ctrl+f movement to MacOS too, though I need someone who actually uses MacOS to say whether those are standard. (Not that you can use Ctrl+f in insert mode since the find command takes precedence)   
But I move Ctrl+n/Ctrl+p/Ctrl+b/Ctrl+f to `normal` mode for nonmacos, though nvim seems to only allow Ctrl+n/Ctrl+p?  
(Overall I'm kinda confused about which keybinds go where, but at least Ctrl+n/Ctrl+p in insert mode should be MacOS specific)
> Move line up/down keybinds in insert to macos

- lapce-app/src/app.rs
- lapce-app/src/config.rs
- lapce-app/src/plugin.rs
- lapce-app/src/proxy.rs
- lapce-app/src/terminal/data.rs
- lapce-app/src/terminal/panel.rs
- lapce-app/src/terminal/tab.rs
- lapce-app/src/window.rs
- lapce-app/src/window_tab.rs
- lapce-proxy/src/dispatch.rs
- lapce-proxy/src/plugin/catalog.rs
- lapce-proxy/src/plugin/wasi.rs
- lapce-rpc/src/proxy.rs
This PR adds a command line flag for launching with a specific folder as an extra plugin. This is intended to be used for plugin/theme development, as it serves as a much nicer alternative to either developing inside the plugins folder or copying your project to that folder everytime.
Though this isn't perfect, it gets the essential part.
One thing I'd like to have in the future is automatically switching to the in-development color theme, and having that setting disconnected from saving the config. (Or perhaps make so when you launch lapce with a plugin-development flag it uses a different config file)
> Add plugin-path for launching with a plugin in a folder

- CHANGELOG.md
- defaults/icon-theme.toml
- lapce-app/src/app.rs
- lapce-app/src/config/icon.rs
- lapce-app/src/file_explorer/view.rs
- lapce-app/src/panel/debug_view.rs
- lapce-app/src/panel/plugin_view.rs
- lapce-app/src/panel/problem_view.rs
- lapce-app/src/panel/source_control_view.rs
- lapce-app/src/panel/view.rs
This PR allows you to fold panel sections. It also introduces a `PanelBuilder` structure to share the logic between different panels, which can hopefully be extended in the future to allow resizing panel sections.
~~This does have an issue when folding the panel when it is on the bottom that I'm not 100% on how to fix. It makes so the one that is folded takes more space...~~
> Foldable panel sections

- CHANGELOG.md
- defaults/settings.toml
- lapce-app/src/config/ui.rs
- lapce-app/src/file_explorer/view.rs
- lapce-app/src/panel/view.rs
Fixes #2268 and the first half of #3063
> Add setting to toggle open editors section

- CHANGELOG.md
- lapce-app/src/file_explorer/view.rs
- lapce-rpc/src/file.rs
- lapce-rpc/src/source_control.rs
(Re)implements  color highlighting if the file has been changed/renamed/added according to source control.
Implements part of #3044
> Add text color if file is changed according to source control

- Cargo.lock
- lapce-app/src/app.rs
- lapce-app/src/doc.rs
- lapce-app/src/editor.rs
- lapce-app/src/editor/diff.rs
- lapce-app/src/editor/gutter.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/editor_tab.rs
- lapce-app/src/file_explorer/data.rs
- lapce-app/src/file_explorer/view.rs
- lapce-app/src/global_search.rs
- lapce-app/src/keymap.rs
- lapce-app/src/keypress.rs
- lapce-app/src/main_split.rs
- lapce-app/src/palette.rs
- lapce-app/src/panel/global_search_view.rs
- lapce-app/src/panel/plugin_view.rs
- lapce-app/src/plugin.rs
- lapce-app/src/rename.rs
- lapce-app/src/settings.rs
- lapce-app/src/source_control.rs
- lapce-app/src/status.rs
- lapce-app/src/text_input.rs
- lapce-app/src/window_tab.rs
Adds `Editors` structure instead of passing around a `RwSignal<im::Hashmap<EditorId, Rc<EditorData>>>` everywhere. Also removes that inner `Rc` as its unneeded because `EditorData` shares the held information.  
Second commit adds functions to `Editors` to construct the actual editors. All callers should use those instead, and are modified to use that. This fixes multiple bugs that occur due to unregistered editors.  
Text inputs are also modified to have a `TextInputBuilder` for auto-registration/deregistration for inputs that are created when the view is created (like in settings), while also supporting stored editors (like search panel input). I think the builder is better than adding more utility …
> Editors struct

- lapce-app/src/editor.rs
- lapce-app/src/keypress.rs
Hi, I just heard of **lapce** and I am gonna give it a try.
As a maintainer of itertools, I was curious of your usage of itertools and eventually found two small simplifications related to it:
- Remove a TODO. I suppose a method `concat_with_separator(sep)` could be useful.
- Remove 3 needless `.to_string()`.
> Two small `itertools` simplifications

- CHANGELOG.md
- lapce-app/src/config.rs
Fixes #3070   
This is a hacky fix which special-cases it.  
I think it would be better to have a more general saving(&loading) setup for fields that need more custom logic, but not implementing it here.
> Fix terminal default profile saving incorrectly

- lapce-app/src/terminal/view.rs
Right-clicking in the terminal directly copy the selected text without needing to retrieve it.
> Fix the issue where the copied text might be empty.

- deny.toml
* this add support for checking licenses with cargo deny check
* cargo deny can also check for security issues and unmaintained/yanked crates
see also: https://github.com/lapce/structdesc/pull/2
> cargo-deny: init

- lapce-app/src/about.rs
- lapce-app/src/alert.rs
- lapce-app/src/app.rs
- lapce-app/src/editor/diff.rs
- lapce-app/src/editor/gutter.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/panel/view.rs
- lapce-app/src/status.rs
- lapce-app/src/title.rs
I also trimmed a few extra containers that were there from when floem couldn't stack styles. I checked that both sets of styles weren't conflicting and removed the extra container. There are probably quite a few more of these that can be removed.
> Add debug names, trim extra containers

- lapce-app/src/status.rs
The position of the middle buttons in the status bar is not fixed when the progress messages are too long. `flex-wrap` is used to wrap the extra messages outside the view.
> fix progress view overflow

- lapce-app/src/app.rs
- lapce-app/src/app/logging.rs
- lapce-app/src/command.rs
- lapce-app/src/main_split.rs
- lapce-app/src/window_tab.rs
- Fixes loading env on Linux where desktop environment sets PWD envvar
- Add Windows support for load env to support direnv
- Add command to debug loaded environment
- Add default log level to match non lapce crates that can show useful info
Fixes #2923
> fix environment loading, add windows support, add show env command

- lapce-app/src/terminal/view.rs
No number of columns can also match, then jump to
> 1. terminal: The default number of jump columns is 0

- lapce-app/src/terminal/view.rs
The effect is as follows:
https://github.com/user-attachments/assets/285aeb43-5462-43d0-957f-7812ccccb740
> Terminal ctrl + click to jump: Support path contains '-' and toml file

- lapce-app/src/doc.rs
- lapce-app/src/window_tab.rs
- lapce-proxy/src/plugin/mod.rs
- lapce-proxy/src/plugin/psp.rs
- lapce-rpc/src/core.rs
support rust-analyzer's notification ["experimental/serverStatus".](https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/lsp-extensions.md#server-status)
When the lsp is loaded, the corresponding document can request "textDocument/semanticTokens/full"  in order to achieve highlighting.
The effect is as follows:
https://github.com/user-attachments/assets/78610da8-90d6-4eaf-8d8d-3af6c7b65ce2
> support rust-analyzer's notification "experimental/serverStatus".

- lapce-app/src/app.rs
- lapce-app/src/editor_tab.rs
- lapce-app/src/file_explorer/view.rs
- If the editor tab close button is set to off, the file icon will now show the warn color to represent the pristine state
- Editor tab content has a tooltip that will show the full file path
- tabs now have cursor Pointer and apply HOVER_BACKGROUND on hover
Also fixed:
- Editor tab height was not connected to the config
> Improve editor tabs

- lapce-app/src/editor.rs
if not, there may be overflow when you click.
> Avoid overflow.

- lapce-app/src/keymap.rs
- lapce-app/src/keypress.rs
- lapce-app/src/keypress/key.rs
- lapce-app/src/keypress/press.rs
1. Add `repeat` field to filter out long press
2. Add SystemTime to filter out excessively long intervals.
> Fix some issues with the shortcuts.

- lapce-app/src/window_tab.rs
> 1. When receiving a DapStopped event, display the Debug panel.

- lapce-app/src/doc.rs
- lapce-app/src/editor/view.rs
- lapce-app/src/find.rs
- lapce-app/src/panel/references_view.rs
2. Jump only when triggered by changes in the search string, and limit the jump to one time.
> 1. Automatically jump to the first position.

- lapce-core/src/language.rs
- added sh extension to bash Syntax highlighting
- sh extension is what most bash scripts use
- initially this is how it is implemented #690
- was removed in [6c85e94]
fixes #3621
> fix! bash Syntax highlighting

- lapce-app/src/plugin.rs
It was quite difficult to figure out which view was eating pointer events. Perhaps the author of lapce/floem#761 has a point.
I don't understand why `pointer_events_none()` only has to be set on one of the empty views. Is this behavior really intended?
> Fix pointer events getting ignored in the plugin info view.

- CHANGELOG.md
- lapce-core/src/language.rs
> Use Diff syntax for files with .diff/.patch extensions by default.
